### ISSUE TITLE
Node cache isn't clearing properly when changing files.

### ISSUE THREAD

**Issue by ratherrandomaccname9000** [chaiNNer-org/chaiNNer#1011]
When I load chaiNNer project while having other one already open the name of the output file in "Save Image" node transfers between projects, which is incorrect behaviour.
0.12.7 win 10

**Comment by theflyingzamboni** [comment]
@joeyballentine This is part of what I meant in discord when I said that it's never worked for me to open multiple instances of chaiNNer. Though I thought the intent was that there was only meant to be one instance open at a time.

**Comment by theflyingzamboni** [comment]
Oh, my bad. When you said the other one was already open, I thought you meant you were opening a second instance and loading a chain to that one.

**Comment by theflyingzamboni** [comment]
@ratherrandomaccname9000 Just spoke with someone having this same issue with the text append node. Can you confirm something for me? Are the two chains you had this issue with based on the same chain? That is, did you save the second chain from the first? And if you create a chain with a save node, save it, select File -> New, create another chain with a save node, save that, and then switch between the two, does the problem persist? Or do they retain the correct info?

**Comment by ratherrandomaccname9000** [comment]
Alright, two answer your first question, dont remember. However very likely because I do have a habit of saving file into some new name and working from that.

I did your little experiment and save node output files are indeed correct. So you might be onto something. I tested them both during the same session and restart and they worked fine.

**Comment by theflyingzamboni** [comment]
@joeyballentine Could you change the name of this issue? This bug seems to be happening because the node cache isn't clearing properly when changing files, so if two files share a node with the same ID, any changes to one node are reflected in the other if you switch chains without closing chaiNNer first.

**Comment by ratherrandomaccname9000** [comment]
Hope that name is fine now, if you want something specific let me know.

**Comment by RunDevelopment** [comment]
I just tested it and the issue seems to be fixed. 

This was most likely fixed by #1217.
