### ISSUE TITLE
Add more resizing filters

### ISSUE THREAD

**Issue by emarron** [chaiNNer-org/chaiNNer#1035]
Add more resizing filters because more options = better.
These are the two types I think would be neat to add:

- general resizers which are used pre or post super-resolution model.
- pixel art scalers which are used independently of the super-resolution models. 

So these are the general resizers already in chaiNNer:

- Nearest Neighbor (point)
- Box
- Bilinear (triangle)
- Bicubic (cubic or catrom??)
- Lanczos

Already in Pillow:

- Hamming

Can be implemented pretty easily:
[Basically everything on this page](https://imagemagick.org/Usage/filter/)
[comparison of filters](https://imagemagick.org/Usage/filter/montage_enlarge.png)
Most desirable of these is probably:

- mitchell
- spline
- lagrange

These are all simple algo to implement as I can just cannibalize the image magic [ 'resize.c'](https://github.com/ImageMagick/ImageMagick/blob/8a1428072f5f24f83113a0b29a330941485cd541/MagickCore/resize.c). I'm guessing adding imagemagick with [wand](https://github.com/emcconville/wand) ctype binding is not desirable.

More complex:
Pixel art scaling algorithms. 
These are different from above, as the above can resize with n scalar, where n = (0 , infinity), these are usually restricted to a single scalar greater than 1. [Wikipedia has a good list](https://en.wikipedia.org/wiki/Pixel-art_scaling_algorithms). I'm guessing this might need its own node?

==

Let me know what you think.

**Comment by Athari** [comment]
Any Hermite fans here? 😁 Blurry or not, it doesn't introduce ringing, and the only currently available option without ringing is bilinear. Not a massive difference in a lot of cases, but still.

**Comment by RunDevelopment** [comment]
Resolved by #2398.
