### ISSUE TITLE
Google Colab (or others) as chaiNNer remote backend environment.

### ISSUE THREAD

**Issue by iamwavecut** [chaiNNer-org/chaiNNer#1037]
**Motivation**
My GPU is kinda sucks, and often busy, but I love playing with chaiNNer.

**Description**
Allow Google Colab (or any other remote Jupyter notebook instance) as chaiNNer backend.

**Alternatives**
dunno, separately distributed backend package?

**Comment by joeyballentine** [comment]
This probably is not possible. The only way I can think of that would work would be to run in the CLI mode that @RunDevelopment is working on. The only thing is, after setting up a chain locally, running it on colab will yield different file paths. We'd need to figure out some way to be able to swap those out. Maybe we could have another export mode like the current "export for sharing" where it saves all paths as just relative paths for the base dir name, and then you'd just have to set up the colab to have those paths. We can think about it.

**Comment by RunDevelopment** [comment]
Superseded by #1875.
