### ISSUE TITLE
Add suffix option in "Save Image" node

### ISSUE THREAD

**Issue by sagar297** [chaiNNer-org/chaiNNer#1043]
If I connect "Image Directory" and "Image Name' from "Load Image" node to the "Base Directory" and "Image Name" of "Save Image" node, it overwrites the original image, so every time I want to change the image in "Load Image" node I have to manually change the name in "Save Image" node. if you add suffix option in the "Save Image" node it can be done automatically.

**Comment by joeyballentine** [comment]
This is what the text append and text pattern nodes are for
