### ISSUE TITLE
Resize an image while preserving it's proportion

### ISSUE THREAD

**Issue by hurodal** [chaiNNer-org/chaiNNer#1052]
**Motivation**
I'm trying to use Chainner to apply watermarks to images but there are still some issues

**Description**
The first step is to downsize the original image so it fits into a 900x900 px size. This means if its landscape oriented the width should be kept and if its portrait oriented, the height should be kept. But now I cannot find a simple way to do it.
If I use RESIZE (RESOLUTION) it just ignores the proportion so the final image is 900x900 and if I use RESIZE TO SIDE I have to manually tell if its landscape or portrait.
A simple checkbox "Preserve proportion" and/or an additional option in the dropdown list "Width & Height" should do the job perfectly...
In fact this new feature would make RESIZE (RESOLUTION) node useless because with the other you can make it

Thanks!

**Comment by hurodal** [comment]
I figured out a way to do this with a not so complicated net:

![image](https://user-images.githubusercontent.com/113827730/193539540-e065bece-620b-4f24-aa0d-61b989c36dc3.png)

As you can see, I had to enter 90000 to set 900px for long side because after dividing I got 0.45 and then when loading this as a percentage it became 0.45% instead of 45%.

**Comment by RunDevelopment** [comment]
The Resize (Target) Node is what you're looking for. The node is a bit convoluted, but used like this, it does what you want:

![image](https://user-images.githubusercontent.com/20878432/193569095-18c8dadb-c9b7-43c4-8810-ff5071fa0904.png)

This will upsample any image smaller than 900x900 and downsample any image larger than 900x900.

**Comment by RunDevelopment** [comment]
I'm going to close this now, because Resize (Target) does what you are asking for.

Feel free to comment in case I misunderstood you, and we'll reopen this issue.
