### ISSUE TITLE
CMYK in Change colorspace

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#1054]
See the discord message [here](https://discord.com/channels/930865462852591648/930865780663398451/1026401147973546044).

The requester wants conversions to and from CMYK. This might be quite difficult because [CMYK doesn't really represent the same spectrum as RGB](https://en.wikipedia.org/wiki/CMYK_color_model#Conversion). However, even an approximate conversion might be useful.

**Comment by joeyballentine** [comment]
PIL has a way to do this https://stackoverflow.com/questions/60814081/how-to-convert-a-rgb-image-into-a-cmyk
