### ISSUE TITLE
missing onnxruntime-gpu

### ISSUE THREAD

**Issue by visjble** [chaiNNer-org/chaiNNer#1058]
**Information:**
- Chainner version: [e.g. 0.11.0] 0.13.0
- OS: [e.g. Windows 10, macOS 10.13] ubuntu 22.04

**Description**
I am trying to download all the dependencies but the onnxruntime-gpu is not avail

**Logs**
Logs help us to find the cause of many problems. To provide your logs, open Chainner and click _Help_ > _Open logs folder_ in the menu. Create a zip file with `main.log` and `renderer.log`, and [attach the zip file]([zipped.zip](https://github.com/chaiNNer-org/chaiNNer/files/9701238/zipped.zip)) to this issue.

Privacy information: Log files contain file paths of Chainner's application files and the files you processed with Chainner. These file paths may contain the name of your account (e.g. Users/michael/...). If your account is your real name, and you are not comfortable sharing, then do not upload your logs or replace all identifying text with something like "fake name".

**Comment by joeyballentine** [comment]
Is there a specific error you get if you open the console? There's a button for it on the top-ish right of the dependency manager

**Comment by visjble** [comment]
![Screenshot from 2022-10-03 14-34-32](https://user-images.githubusercontent.com/8854071/193691903-db70db5f-b3ed-416f-9c18-375ae6ff19f2.png)

**Comment by visjble** [comment]
https://files.pythonhosted.org/packages/b9/ce/234c2dc01a7f08dd7cd8b4f9a8ef97bfad98864cea30bf735b8387230963/onnxruntime_gpu-1.12.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Download at: 0%
Download at: 5%
Download at: 10%
...
Download at: 65%
Download at: 70%
Download at: 75%
Error: aborted

**Comment by joeyballentine** [comment]
Since it's download the python 3.8 version I'm assuming you have it set to use your system python. In that case, you should be able to download the wheel file manually and run the command to install it from the file: `python -m pip install /the/full/path/to/the/whl/file/you/downloaded.whl`, with the actual path obviously.

**Comment by visjble** [comment]
It worked, thanks Joey!!!!!!!!
