### ISSUE TITLE
Iterator percentage gets stuck

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#1079]
[We received a bug report on Discord](https://discord.com/channels/930865462852591648/930865725135011851/1029052457843691611) that iterator don't update their percentage correctly.

> the percentage of upscaling gets stuck totally after like 3-4 images upscaled at most (sometimes 2 too)

Here is the chain of that user:

![image](https://user-images.githubusercontent.com/20878432/194903455-b8603382-bc67-4dd2-8e8d-99248a8b27d9.png)

**Comment by joeyballentine** [comment]
Update from the user:

> (update) seems like fixed after i shortened the folders name it was taking images from... idk how that works but ayt ig

Seems like a long path issue, not sure we can do anything about that as it's an OS limitation afaik

**Comment by RunDevelopment** [comment]
Errors inside the iterator shouldn't cause the percentage to get stuck though.

**Comment by RunDevelopment** [comment]
#Fixed by 1730.
