### ISSUE TITLE
Input grouping 

### ISSUE THREAD

**Issue by joeyballentine** [chaiNNer-org/chaiNNer#1090]
Many nodes would benefit from un-chainable inputs being able to be "grouped" together into a single input. 

For example, the "to" and "from" of the color space conversion node could be a single input, made by grouping two dropdowns. The blend node could have multiple image inputs, grouped with a blend mode dropdown and possibly even an opacity slider. NCNN's bin and param files could be grouped as well (and later have linking logic) 

I'm sure there's a way we could define an easy API for this. Basically just have a GroupedInput class, where you pass in the inputs you want in that single input and how you want them positioned. Then on the frontend we would just need to respect that configuration.

This really would only work for inputs that don't have handles (dropdowns and file selections mainly) but it should be able to have at most one handle input (i.e. an image in the blend node idea) that would be able to function normally.

**Comment by RunDevelopment** [comment]
Resolved by #1139.
