### ISSUE TITLE
Slider input appearance change

### ISSUE THREAD

**Issue by joeyballentine** [chaiNNer-org/chaiNNer#1091]
When looking at photoshop's sliders, I realized we could make our sliders a bit better.

![hue-sat-properties-colorize png img](https://user-images.githubusercontent.com/34788790/195390935-eb478bb4-a70e-4a35-aecf-c78e4b1f25aa.png)

As you can see in Photoshop, the slider uses the full width, and the number input sits above it. The label is also left aligned. I think we should copy that design. 

This will require a bit of a refactor though, because currently labels are applied the same way on every non-generic input. This will have to be changed to the input itself handling the label, or at least having a prop that allows you to turn off the existing default one.

**Comment by RunDevelopment** [comment]
Will this actually look good in chainner though? Our number inputs are quite tall.

**Comment by joeyballentine** [comment]
![194981119-bdd2df5f-e92c-44d4-84f9-67e2ea711816](https://user-images.githubusercontent.com/34788790/195421774-79c15f19-5c4d-4c9a-a3ca-94a6920bd47d.png)

I feel like theres easily enough room for it. If not, we can just make the input a bit taller overall. But this helps a little bit with too things: 1) the width of the slider number inputs is too small for some numbers, and 2) sliders are a bit too small. With this change, both could be wider without actually changing the width of the node

**Comment by joeyballentine** [comment]
Not needed
