### ISSUE TITLE
GFPGAN doesn't work?

### ISSUE THREAD

**Issue by Kornform** [chaiNNer-org/chaiNNer#1094]
Hi, I hope someone can help me out.
I use chaiNNer for upscaling and that part works how intended. However chaiNNer should also support models like "GFPGAN" and when I use that model in chaiNNer it doesn't do anything.

When I make some face restorations in Google Collab "GFPGAN" I get pretty neat results and when doing it in chaiNNer it does nothing, although chaiNNer states the support of "GFPGAN" under "Model Architecture Support", so I'm just a little bit confused.

Am I doing something wrong?

**Comment by joeyballentine** [comment]
1. Make sure you have the newer extra pytorch dependencies (torchvision and facexlib) installed in the dependency manager 
2. Upscaling with GFPGAN is done via the "Face Upscale" node. If you don't see that there, that means you are missing the aforementioned dependencies

**Comment by Kornform** [comment]
Hey thank you for the answer. I reinstalled chaiNNer and the dependencies. I think I'm still missing the dependencies you mentioned. I attached a screenshot where you can see which dependencies I have installed. There is nothing more I could do from there as far I know. So I still can't access the "Face Upscale".

Can you tell me what I could do to fix this?

![image](https://user-images.githubusercontent.com/57677084/195444314-3cf7f937-37d3-423c-9183-6f5f2b2f8889.png)

**Comment by joeyballentine** [comment]
You are on version 0.12.7. GFPGAN was added in 0.13.0.

**Comment by Kornform** [comment]
OK. This time I used the Windows installer instead and that somehow worked for me. Now I have the required dependencies  you mentioned above.

**Comment by joeyballentine** [comment]
So GFPGAN is working for you now?

**Comment by Kornform** [comment]
> So GFPGAN is working for you now?

Yes it is now working for me :)

**Comment by joeyballentine** [comment]
Glad to hear it
