### ISSUE TITLE
Quitting with unsaved changes warning popup is inconsistent with all other applications

### ISSUE THREAD

**Issue by Athari** [chaiNNer-org/chaiNNer#1100]
## Description
The warning dialog about unsaved changes is inconsistent with all other such dialogs in all other applications. Key differences:

1. Hidden negative question ("Do not save?" instead of "Save?")
2. Different button order ("Don't save / Save" instead of "Save / Don't save / Cancel quitting")
3. Different default button ("Don't save" instead of "Save")
4. No Cancel button
5. File name isn't mentioned
6. Unnecessarily long text

Consistency is very important here because clicking the wrong button can lead to unexpected data loss. A lot of people don't read warning messages, especially when they're long, and click out of the decades old habit.

Furthermore, misclicking on the close button doesn't offer an option of canceling quitting. Considering chaiNNer doesn't load fast, restarting can be annoying. This is also important when custom action is needed, for example saving changes into a different file.

The dialog shoud be:

**Do you want to save changes to {chainName}?** *Yes / No / Cancel* (*Save / Don't save / Cancel*, if possible)

### Dialog of chaiNNer

![image](https://user-images.githubusercontent.com/1715107/195927204-210cbcbf-4079-44a0-a6de-c983cb2fff91.png)

**Do not save?** *Yes / No*

### Traditional approach

![image](https://user-images.githubusercontent.com/1715107/195927740-e93888c7-3529-446a-be3a-b5ef97c743e5.png)

**Save?** *Yes / No / Cancel*

### Modern approach

![image](https://user-images.githubusercontent.com/1715107/195927278-d501856a-2bea-4f8c-aabb-4efdbcbdd282.png)

**Save?** *Yes / No / Cancel*

### Advanced approach

![image](https://user-images.githubusercontent.com/1715107/195927598-4639ce94-8fd1-4183-a5ed-118f1e902ff1.png)

**Save?** *Yes / No / Cancel*

Note that in all cases, quitting isn't even mentioned. The important part of the question is to save or not.

## Official design guidelines

**Microsoft:** https://learn.microsoft.com/en-us/windows/win32/uxguide/mess-confirm
**Apple:** https://developer.apple.com/design/human-interface-guidelines/components/presentation/alerts/

## Information:
- Chainner version: 0.13.0
- OS: Windows 10

**Comment by joeyballentine** [comment]
Thank you for pointing this out, and for the detailed issue information. I'll definitely change this (most likely to the "modern" approach)
