### ISSUE TITLE
Is there a way to detect portrait/landscape?

### ISSUE THREAD

**Issue by caacoe** [chaiNNer-org/chaiNNer#1104]
I keep finding myself making two files, each separately for portrait and landscape. Is there a way to detect the orientation of an image and automatically run a different path of nodes?

Thanks.

**Comment by caacoe** [comment]
> Not at the moment. At some point we will include branching (we have an issue for it, #148) which when combined with some logical operators would be able to do this. But that won't exist for a while.

Cool, I look forward to it and totally off topic from my original post, face detection for assisted cropping :)

Thanks for the awesome software.

**Comment by theflyingzamboni** [comment]
@caacoe What is it that you needed to do here? Depending on what it is, it may be there's already an alternate means of accomplishing it.
