### ISSUE TITLE
open error

### ISSUE THREAD

**Issue by nanshanfeiwu** [chaiNNer-org/chaiNNer#1122]
Redownload still reports error
- OS: [ Windows 10]

chaiNNer has encountered a critical error:Failed to fetch
![QQ截图20221022142058](https://user-images.githubusercontent.com/105589928/197323852-af8c44bb-1688-4fb9-98fc-b03525758453.png)
[main.zip](https://github.com/chaiNNer-org/chaiNNer/files/9843708/main.zip)
How to deal with it?

**Comment by joeyballentine** [comment]
My best guess at what's happening is pip is failing to install the dependencies needed. Be sure you aren't blocking chaiNNer's access to the Internet

**Comment by nanshanfeiwu** [comment]
> My best guess at what's happening is pip is failing to install the dependencies needed. Be sure you aren't blocking chaiNNer's access to the Internet

Thank you for the reply, the program does not prohibit the Internet.
Then I'll reinstall the program

**Comment by nanshanfeiwu** [comment]
> > My best guess at what's happening is pip is failing to install the dependencies needed. Be sure you aren't blocking chaiNNer's access to the Internet
> 
> Thank you for the reply, the program does not prohibit the Internet. Then I'll reinstall the program

After re-downloading the file, I get an error after waiting for a few seconds in the loading main application screen, the component has been downloaded to the C drive, why does it get an error?
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/9843886/main.log)
![1](https://user-images.githubusercontent.com/105589928/197329730-ea802d83-96ec-495a-840a-154ece07c130.png)
![2](https://user-images.githubusercontent.com/105589928/197329732-f3e0e20a-0f33-4f79-8cf6-a7e16b924157.png)
![3](https://user-images.githubusercontent.com/105589928/197329736-76867bda-a9d4-4b0b-9a94-05470942784e.png)

**Comment by nanshanfeiwu** [comment]
> My best guess at what's happening is pip is failing to install the dependencies needed. Be sure you aren't blocking chaiNNer's access to the Internet

I found the reason for the error when opening the software, because my system is Chinese font, which is the reason.

![QQ截图20221022173812](https://user-images.githubusercontent.com/105589928/197333186-24c517e5-7e9a-4915-a445-cb120d5154cb.png)

But now the problem is that I can't download.
![QQ截图20221022175542](https://user-images.githubusercontent.com/105589928/197333228-c2e08a6d-6426-4374-ae7b-40d6e9d010bc.png)

**Comment by nanshanfeiwu** [comment]
> My best guess at what's happening is pip is failing to install the dependencies needed. Be sure you aren't blocking chaiNNer's access to the Internet

I found the reason why I can't download it. It is caused by VPN. Thank you for bringing such a great software. I hope to fix the software error caused by Chinese fonts in the system as soon as possible. Thank you again. I hope luck and health will always be with you.

**Comment by joeyballentine** [comment]
Glad you finally got it to work. I don't think we can really work around VPN/connection issues but I'll look into what we can do to maybe prevent other language characters from interfering with things.

**Comment by joeyballentine** [comment]
Going to close this and open a new issue with that text problem
