### ISSUE TITLE
Copy To Clipboard crashes backend when copying a single-channel image

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#1131]
OS: Win 10 64 bit
Chainner: latest/main

![image](https://user-images.githubusercontent.com/20878432/197409158-36056b99-f8c2-4947-9833-c677d05ca8a1.png)

Logs:

```
20:23:27.734 > Backend: [15876] [INFO] Running new executor...
20:23:27.928 > Python subprocess exited with code 3221225477 and signal null
```

So yeah, it just hard crashes the backend. RGB and RGBA images work, only grayscale images cause crashes.

**Comment by joeyballentine** [comment]
That probably means we need to convert to RGB before copying

**Comment by RunDevelopment** [comment]
https://stackoverflow.com/a/53369553/7595472

Wow. Exit code 3221225477 or 0xC0000005 means memory access violation. So it's a memory bug in some C library our clipboard code uses.
