### ISSUE TITLE
Fetch error

### ISSUE THREAD

**Issue by MaxiKitti** [chaiNNer-org/chaiNNer#1140]
- Chainner version: [0.13.1]
- OS: [Windows 11]

it started up normally at first then i installed all the dependencies due to having an intel cpu with both a rtx 2070 super from nvidia and a rx 6700 xt from amd which should support all them but i think i need to uninstall the dependences but...i cant find a way how to get rid of them

**Comment by joeyballentine** [comment]
There seems to be a pretty common issue right now where pytorch fails to import for people. How much ram do you have?

**Comment by joeyballentine** [comment]
> i cant find a way how to get rid of them

You can delete the `%appdata%/chaiNNer/python` folder and it will start up like a fresh install. If you could send over your logs (%appdata%/chaiNNer/logs) I could take a look at what error pytorch is spitting out and see if it's fixable.

**Comment by MiseryNewt** [comment]
I think I have the same issue. I wanted to download pytorch and after restarting it does this to me.
![image](https://user-images.githubusercontent.com/116898298/198644737-a3859db6-b7bb-4b65-afbe-8bca519a86e3.png)
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/9889224/main.log)
[renderer.log](https://github.com/chaiNNer-org/chaiNNer/files/9889225/renderer.log)

**Comment by joeyballentine** [comment]
```
OSError: [WinError 193] %1 nenï¿½ platnï¿½ aplikace typu Win32. Error loading "C:\Users\Misery\AppData\Roaming\chaiNNer\python\python\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies
```

Yep that's the same problem that other people are getting. If you're in the discord, I recommend following this discussion and attempting everything suggested here: https://discord.com/channels/930865462852591648/930875396277280788/1034244068101869638

This person's fix seemed to have been using version 0.13.0, and then it just kinda magically worked when they switched back. I have no idea why though

**Comment by joeyballentine** [comment]
Closing this since on discord you said you got it to work. The fix seems to just be to remove everything and install 0.14 again.

**Comment by joeyballentine** [comment]
Oh wait, the person who got it to work isn't the OP. @MaxiKitti, could you try uninstalling chaiNNer and manually removing the %appdata%/chaiNNer folder? Then install 0.14 again and download pytorch

**Comment by MaxiKitti** [comment]
> There seems to be a pretty common issue right now where pytorch fails to import for people. How much ram do you have?

i have 32gb total or 2 x 16gb of 3600mhz ram

**Comment by MaxiKitti** [comment]
> Oh wait, the person who got it to work isn't the OP. @MaxiKitti, could you try uninstalling chaiNNer and manually removing the %appdata%/chaiNNer folder? Then install 0.14 again and download pytorch

ill try it out when i can today

**Comment by MaxiKitti** [comment]
> Oh wait, the person who got it to work isn't the OP. @MaxiKitti, could you try uninstalling chaiNNer and manually removing the %appdata%/chaiNNer folder? Then install 0.14 again and download pytorch

deleting the %appdata% folder definately helped

**Comment by joeyballentine** [comment]
Going to close this as the issue seems to be resolved. let me know if that is not the case and I can reopen it
