### ISSUE TITLE
Error report: 

### ISSUE THREAD

**Issue by fantomac** [chaiNNer-org/chaiNNer#1146]
```
UnhandledRejection Error
```
ChaiNNer: chaiNNer 0.13.1
OS: macOS 10.18

**Comment by joeyballentine** [comment]
Could you send your logs? They should be located in the application support folder, in `Application Support/chaiNNer/logs`

**Comment by fantomac** [comment]
Hi, 
Thanks for replying 👍
I just needed to relaunch and eveything works fine now.
Sorry to bother you 😅

Tanks for you work !!!!

**Comment by joeyballentine** [comment]
Odd, but glad to hear it's working now!
