### ISSUE TITLE
Just an IMAGE OPEN and an IMAGE SAVE NODE

### ISSUE THREAD

**Issue by theogott** [chaiNNer-org/chaiNNer#1151]

**Comment by RunDevelopment** [comment]
I do not understand what bug you are trying to report. Could you please clarify? 

Load Image and Save Image work as expected.

![image](https://user-images.githubusercontent.com/20878432/198569583-ceef586e-5eac-4b43-a245-5e15758e059e.png)

**Comment by theogott** [comment]
Please delete this issue, i had a Problem with the second monitor.
