### ISSUE TITLE
Can't Install Pytorch?

### ISSUE THREAD

**Issue by disneytoy** [chaiNNer-org/chaiNNer#1152]
Hello!

Could you help. I am trying to install Pytorch via the install button. But it never processes.  It may be an internet issue on my side. Some port being blocked by my ISP. I have downloaded the Pytorch link Chainner was trying to install:

 https://download.pytorch.org/whl/cu113/torch-1.10.2%2Bcu113-cp39-cp39-win_amd64.whl

Is there a solution for me to manually install this to 3.9.7? I also have regular python 3.10 installed on my machine.  I have Anacaonda and PIP installed. I don't know how to install this package directly to Chainners integrated python 3.9.7.  (not 3.10)

Any help would be appreciated. I really want to try some GANS.

Thanks

Max

PS: When I've switched off the integrated Python to use my 3.10. It shows Pytorch and NCNN installed but I can't install ONXX!  Argg!
![chainner](https://user-images.githubusercontent.com/26030263/198629900-c2f9bd8c-b306-4339-bf6c-02d37e939efd.jpg)

**Comment by joeyballentine** [comment]
If you just want to use pytorch, you don't need to install onnx.

As for how to install pytorch to the integrated one manually (assuming you're on windows), run `%appdata%/chaiNNer/python/python/python.exe -m pip install path/to/the/whl/file.whl` with the path replaced with where the downloaded file is

**Comment by disneytoy** [comment]
I'll try that Thank you! Nice APP!
