### ISSUE TITLE
GPEN & CodeFormer support

### ISSUE THREAD

**Issue by joeyballentine** [chaiNNer-org/chaiNNer#1159]
It would be nice to add support for both GPEN and CodeFormer.

I know CodeFormer can be easily inserted into the existing code, but I'm not sure about GPEN.

**Comment by zelenooki87** [comment]
Is it feasible to integrate support for GPEN as well? CelebA-HQ dataset still holds the top benchmark on paperswithcode: https://paperswithcode.com/. With GPEN, it's possible to process very high-resolution images, even exceeding 100 megapixels, without encountering CUDA OOM errors.
