### ISSUE TITLE
Unable to install integrated Ffmpeg

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [chaiNNer-org/chaiNNer#1195]
chaiNNer-windows-x64-0.14.2
```
[Window Title]
Unable to install integrated Ffmpeg

[Content]
Chainner was unable to install FFMPEG. Please ensure that your computer is connected to the internet and that chainner has access to the network.

[Exit]
```
Why doesn't it even want to start?

**Comment by joeyballentine** [comment]
Hmmm, it definitely shouldn't be preventing startup just for that. Will look into it.

For now though, do you have a VPN/firewall or something that could cause it to not be able to connect to GitHub?

**Comment by 0x4E69676874466F78** [comment]
@joeyballentine I have a firewall, it's just weird not to let it run because of an optional dependency.
I have no problem downloading, but I stick to making sure that the software works properly in this situation.

**Comment by 0x4E69676874466F78** [comment]
@joeyballentine thanks!
