### ISSUE TITLE
Unable to copy text from warning message box

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [chaiNNer-org/chaiNNer#1197]
Neither CTRL+C at the modal window nor select text in it works.

Example:
![изображение](https://user-images.githubusercontent.com/4449851/200630468-ab754808-3df2-403d-8c4d-84cd04c932ec.png)

**Comment by RunDevelopment** [comment]
Is that really a necessary feature? Messages, that contain information that other might also need, have a "Copy To Clipboard" button.

However, maybe we could have something like a little copy icon next to the close x for any message?

**Comment by 0x4E69676874466F78** [comment]
@RunDevelopment 
In Windows, text of any properly designed window can be copied via CTRL+C

> Is this one of the messages you couldn't copy?

The messages of this window is copied without problems via CTRL+C

The window I could not copy was the one I showed in the first post here.

**Comment by RunDevelopment** [comment]
Wow. I did not know that you can do Ctrl+C on a native alert and get the entire contents of the alert as text.
