### ISSUE TITLE
Mac M1 arm MPS support

### ISSUE THREAD

**Issue by ioma8** [chaiNNer-org/chaiNNer#1218]
**Motivation**
Currently generating on Mac M1 is very slow due to using only CPU. However the pytorch-nightly supports running on MPS (aka Mac M1 "GPU") which, while used for example in Stable Diffusion is very fast. I have not found any info that this is currently being considered or done here. It could theoretically be as simple asi just switching the device in pytorch to the descriptor 'mps.' Or there might be some slight adjustments needed (some remaining methods in pytorch dont support mps so you need to convert data to cpu and back - but its minority of those and its possible they are not used in Chainner).

In the current state the Chainner is not usable for upscaling on the newest MacBook Pro M1 with 32 GB ram (upscaling simple image takes like 10 minutes) which is sad, so it should be added.

**Comment by joeyballentine** [comment]
You should be able to utilize your GPU currently by using NCNN. However, I do want to add MPS support. I'm just planning on waiting until the next version comes out of nightly to do so. Though, maybe i could still technically allow it if installed via system python manually. I'll see. If it's as easy as doing some sort of equivalent to .cuda_is_available() but for MPS it would be pretty easy

**Comment by ioma8** [comment]
> You should be able to utilize your GPU currently by using NCNN. However, I do want to add MPS support. I'm just planning on waiting until the next version comes out of nightly to do so. Though, maybe i could still technically allow it if installed via system python manually. I'll see. If it's as easy as doing some sort of equivalent to .cuda_is_available() but for MPS it would be pretty easy

Hey, NCNN should work, however from what I understand for being able to use NCNN I need also ONNX. And ONNX is currently not supported for Mac M1 in Chainner also.

**Comment by joeyballentine** [comment]
You only need onnx to do the conversion from onnx to ncnn. You actually can just export to onnx (which goes through pytorch), then convert using convertmodel.com to ncnn. It's a bit of a pain but it works. Hopefully onnx release m1 builds soon.

**Comment by ioma8** [comment]
> You only need onnx to do the conversion from onnx to ncnn. You actually can just export to onnx (which goes through pytorch), then convert using convertmodel.com to ncnn. It's a bit of a pain but it works. Hopefully onnx release m1 builds soon.

Thank you.

As for the mps detection - yes, the method is this:
```
        device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")

**Comment by joeyballentine** [comment]
Wow what good timing haha, I was literally just working on this. Any chance you'd be able to test my `MPS` branch? https://github.com/chaiNNer-org/chaiNNer/tree/mps

**Comment by joeyballentine** [comment]
We decided to merge this so it could be built in [today's nightly](https://github.com/chaiNNer-org/chaiNNer-nightly/releases/tag/2022.11.13), if you wouldn't mind testing it.
