### ISSUE TITLE
Resizable View Image node

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#1233]
[As requested on Discord](https://discord.com/channels/930865462852591648/930865780663398451/1041878176697159731), add a way to resize the View Image node.

**Comment by joeyballentine** [comment]
In order for this to be useful you're going to need to be ok with sending larger images to the frontend. I'd even argue right now we send too small images, and quite frankly previewing it only useful if you see the actual image and not a resized version

**Comment by joeyballentine** [comment]
turns out this actually duplicates #782
