### ISSUE TITLE
how do i upscale a video

### ISSUE THREAD

**Issue by BastianGVF** [chaiNNer-org/chaiNNer#1234]
i'm just confused that's all

**Comment by joeyballentine** [comment]
Use the video frame iterator, and connect the input node to an upscale image node. If you are unfamiliar with how the upscaling process works I recommend doing it with images first, then using the same setup inside the video iterator

**Comment by joeyballentine** [comment]
If you need an example, here is a community made example template: https://github.com/Kim2091/kim-chaiNNer-Templates/blob/main/Pytorch/Simple%20Video%20Iterator.chn

**Comment by BastianGVF** [comment]
thanks for the help!
