### ISSUE TITLE
where can i download RestoreFormer Model?

### ISSUE THREAD

**Issue by BahzBeih** [chaiNNer-org/chaiNNer#1235]
Peace, where can i download RestoreFormer Model? i downloaded models from :
https://github.com/wzhouxiff/RestoreFormer
https://drive.google.com/file/d/13ir-VvdDNOA3LeoNbx4Y530rvIheyhRM/view?usp=sharing

but when i try to load model i got this message:
 "Error
Model unsupported by chaiNNer. Please try another."

i'm using Alpha v0.14.2

**Comment by zelenooki87** [comment]
download them from gfpgan repo...

**Comment by joeyballentine** [comment]
https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/RestoreFormer.pth

Sorry, i keep forgetting to update the link in the readme. When i added support for this i didn't realize the official repo didn't have the same model file as GFPGAN's repo

**Comment by zelenooki87** [comment]
@joeyballentine joeyballentine
could you please add support for codeformer?
Thank you very much in advance!

**Comment by joeyballentine** [comment]
I plan to, yes

**Comment by EmmaWebGH** [comment]
Hi
Found this by googling. Is Codeformer supported yet? Tried to load it and it said it was incompatible...

**Comment by joeyballentine** [comment]
@EmmaWebGH  Yes it is. Where did you get the codeformer model? The one linked in the readme should work.

**Comment by EmmaWebGH** [comment]
@joeyballentine  Got it, thanks!
