### ISSUE TITLE
Swin2SR is not supported for NCNN conversion at this time

### ISSUE THREAD

**Issue by BahzBeih** [chaiNNer-org/chaiNNer#1238]
Peace, when i try to convert "Swin2SR_CompressedSR_X4_48" Model to NCNN model with chaiNNer Alpha v0.14.2 i got this error message:

An error occurred in a PyTorch Convert To NCNN node:

Swin2SR is not supported for NCNN conversion at this time.

Input values (partial):
• Data Type: fp32

i hope Swin2SR Models get NCNN conversion support soon, thanks a lot for this amazing program 👌👌👌

**Comment by joeyballentine** [comment]
This is out of our control. The NCNN devs refuse to add support for the operations necessary for this to be compatible with NCNN, so it's just not possible. Maybe if we bug them enough they would consider it, but i doubt it.

**Comment by BahzBeih** [comment]
> This is out of our control. The NCNN devs refuse to add support for the operations necessary for this to be compatible with NCNN, so it's just not possible. Maybe if we bug them enough they would consider it, but i doubt it.

thanks alot for your response, hope they add support for necessary operations soon because not all of us have NVidia GPUs , and using cpu is time consuming especially when trying to upscale videos :(
