### ISSUE TITLE
Can't seem to load any SwinIR or HAT models

### ISSUE THREAD

**Issue by dillfrescott** [chaiNNer-org/chaiNNer#1262]
I can't seem to load any SwinIR or HAT models in the newest version that was just released. But I downgraded to `v0.15.0` and I am able to load the models again.

Tested on Windows 11.

**Comment by joeyballentine** [comment]
We must have broke something then. Will look into it

**Comment by joeyballentine** [comment]
I think i know what caused this actually. I added a model loading restriction that prevents arbitrary code execution but i guess it blocks something these models need. Should hopefully be easy to fix if we can figure out what needs to be allowed

**Comment by dillfrescott** [comment]
Ah gotcha!
