### ISSUE TITLE
Disable presets with missing dependencies

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#1267]
If a user doesn't have pytorch installed, then they shouldn't be able to use the PyTorch preset.

In general, if a preset contains a node with an unknown schema id, disable that preset and try to display a good "error" message (e.g. "Installing PyTorch is required for <preset name>.")

Right now, users get this:
![image](https://user-images.githubusercontent.com/20878432/203812388-5353b34d-d765-4a13-813d-eb50f8495c39.png)

**Comment by joeyballentine** [comment]
The preset system was removed, so therefore this is no longer relevant
