### ISSUE TITLE
Iterator resizing is not recorded in history

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#1298]
You can't undo resizing an iterator.

Steps to reproduce:
1. Create an iterator node.
2. Fill it with nodes.
3. Resize the iterator such that it is smaller and has to rearrange its children to fit.
4. Ctrl+Z.

![image](https://user-images.githubusercontent.com/20878432/204368264-f1c6a02e-00da-418f-abd9-d2b5f3daf3e5.png)

**Comment by joeyballentine** [comment]
I feel like this will be something easier to address once you refactor global state

**Comment by theflyingzamboni** [comment]
Or irrelevant once iterators are reworked haha.
