### ISSUE TITLE
Can't install ncnn

### ISSUE THREAD

**Issue by LilMaim** [chaiNNer-org/chaiNNer#1319]
![sdfasdfvg](https://user-images.githubusercontent.com/114922940/204842389-f71e515b-e348-4f52-a0aa-b9ccbca5ffdd.jpg)

For some reason I get "missing dependencies" for ncnn  after instalation but it says it's installed and has only one package

**Comment by joeyballentine** [comment]
Probably means it's failing to load for some other reason, can you send your main.log file? Help > open logs folder

**Comment by LilMaim** [comment]
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/10124818/main.log)

**Comment by joeyballentine** [comment]
Unfortunately the only error it's giving is "DLL load failed while importing ncnn: The specified module could not be found."

So, my guess is it can't load vulkan. Are you sure you have a vulkan-compatible GPU + updated drivers?

**Comment by LilMaim** [comment]
I have a Radeon HD7850 but there is something strange with the drivers. It says its updated but then offers me the same update a couple days later. That is probably the cause. I will look into that.
Thank you very much for your time.

**Comment by joeyballentine** [comment]
That might just be with the open source drivers though, idk about official ones

**Comment by LilMaim** [comment]
Wow, thanks man. I'll try that.
