### ISSUE TITLE
image Iterator

### ISSUE THREAD

**Issue by hat3l0v3** [chaiNNer-org/chaiNNer#1325]
Hello, I have an issue. I found out that chaiNNer is working almost twice slower (in my case, with special models maybe) than Real-Esrgan. But it have cool features as ColorFix (that reduce color shifting after upscale).
So what I tried to do its - load upscaled image from 1st directory, reference image from 2nd directory and use ColorFix on them. But program does't allow me to do that. Something like that:
![color](https://user-images.githubusercontent.com/51430358/205200268-fe4b81dc-5c99-4cfb-b86b-de3fe9f5df95.png)
Or maybe there is another solution and I'm stupid?

**Comment by joeyballentine** [comment]
Ah, you have a misunderstanding as to how iterators are meant to be used. First of all, for this task you would want to use the image pairs iterator. Second of all, iterators are meant to have all the nodes you want to iterate over inside of them. They aren't just wrappers for individual nodes.

Example:

![image](https://user-images.githubusercontent.com/34788790/205201452-e2efd0ba-bd42-47f4-8466-cf8f8af30b76.png)

**Comment by hat3l0v3** [comment]
sorry. thankyou for your help

**Comment by joeyballentine** [comment]
No problem, and let me know if you have any other questions

**Comment by RunDevelopment** [comment]
I'm going to close this issue now. However, feel free to comment if you have any other questions.
