### ISSUE TITLE
Stuck on Splash screen when system python is set

### ISSUE THREAD

**Issue by limnibal** [chaiNNer-org/chaiNNer#1329]
On Nightly 2022.11.30 gets stuck on the splash screen when I set system python and corresponding exe (in my dml folder). 
Logs: 
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/10144060/main.log)

I don't use any VPN or special Firewall/Antivirus setup on that machine, just standard Win10pro and the Microsoft Defender.

Seems this is an issue with python loading the SSL package and cropped up on discord before  https://discord.com/channels/930865462852591648/930875396277280788/1029102995633352715

This was mentioned here https://github.com/chaiNNer-org/chaiNNer/pull/1283#issuecomment-1334809561

**Comment by joeyballentine** [comment]
Can you try the solution here: https://stackoverflow.com/questions/54175042/python-3-7-anaconda-environment-import-ssl-dll-load-fail-error

Seems like a conda-specific issue

**Comment by limnibal** [comment]
will try and feedback on monday
