### ISSUE TITLE
Critical Error  A critical error occurred while processing the node data returned by the backend. Error: Failed to fetch

### ISSUE THREAD

**Issue by Myoufer** [chaiNNer-org/chaiNNer#1335]
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/10147968/main.log)

**Comment by Myoufer** [comment]
Seems to be caused by proxy, disable it solved the problem

**Comment by Myoufer** [comment]
Then if the network in your region are having bad connection with pip, try change it's repository to a mirror close to you

**Comment by Myoufer** [comment]
And if you still trying to use proxy, have a look at this
https://github.com/python/cpython/pull/26307

**Comment by joeyballentine** [comment]
> Then if the network in your region are having bad connection with pip, try change it's repository to a mirror close to you

How would i do this? Is it just something i can add to the url?
