### ISSUE TITLE
The "Restart chaiNer" button skips the unsaved data dialog

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [chaiNNer-org/chaiNNer#1338]
and results in loss of data.

**Comment by RunDevelopment** [comment]
The Restart chainner button is kinda broken anyway in that we don't actually need to restart chainner. We should finally implement restarting just the backend.

**Comment by joeyballentine** [comment]
Don't forget there's also the restart button in settings, which is needed for applying certain settings like disabling hardware acceleration.

For the restart in the dependency manager, it should be fine to just restart the backend and refresh everything linked to the backend (nodes, etc)

**Comment by 0x4E69676874466F78** [comment]
@joeyballentine 
> Don't forget there's also the restart button in settings

Where else is it available? That's what I'm talking about.
Or do you mean Reload/Force Reload? (but they don't lost data)

**Comment by RunDevelopment** [comment]
#1348 removed one "Restart chaiNNer" button, so we got a bit of progress.
