### ISSUE TITLE
Unable to paste a copied/cut node(s) from the *iterator space outside of it

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [chaiNNer-org/chaiNNer#1355]
It keeps inserting inside the iterator no matter how hard I try.

**Comment by joeyballentine** [comment]
Ah, i know why this happens. I will attempt to fix it

**Comment by joeyballentine** [comment]
So it turns out this will be harder than I thought. Turns out it's difficult to tell the difference between copying just the interior nodes and copying the entire iterator
