### ISSUE TITLE
NCNN video card devices list missing NVIDIA device

### ISSUE THREAD

**Issue by iamwavecut** [chaiNNer-org/chaiNNer#1374]
**Information:**

- Chainner version:  0.16.0
- OS: Win 11 22H2

**Description**
My GeForce Integrated video card disappeared from NCNN devices in settings dropdown after updating to 0.16.0 (but may be earlier, as I used only Pytorch models during previous couple of builds). Pytorch and ONNX detects 3060 succesfully.
![image](https://user-images.githubusercontent.com/239034/206426187-c4643018-e36f-4d4f-a51c-2e872fec02cf.png)
![image](https://user-images.githubusercontent.com/239034/206427573-f1e90514-a54d-472c-b53c-0e58262b8d7a.png)
![image](https://user-images.githubusercontent.com/239034/206427622-b5bd4070-60cf-417d-a818-1109159a740b.png)

**Logs**
They're clear in this regard

**Comment by joeyballentine** [comment]
Nothing about the ncnn gpu list or ncnn version we use changed in 0.16, so if an update caused this it would have been a long time ago. Can you confirm what the last working version is?

**Comment by joeyballentine** [comment]
@iamwavecut did you figure out why this happened?
