### ISSUE TITLE
Many DDS DXT10 formats are not supported

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#141]
The underlying image library we use does not support many DDS DXT10 formats. 

This includes:
- ATI1 (legacy)
- ATI2 (legacy)
- BC1 (all variants)
- BC7 (all variants)

**Comment by iwubcode** [comment]
This is pretty critical for games.  Any idea what library Chainner would switch to?

**Comment by iwubcode** [comment]
@joeyballentine - just curious but what have you looked at so far?

**Comment by RunDevelopment** [comment]
>what have you looked at so far?

Me so far: all libraries in pypi.org with the dds tag. I also tried looking for C/C++ libraries, but couldn't find anything multiplatform (yet). DDS support seems to be fairly young over a Rust, so no luck there either.

**Comment by iwubcode** [comment]
@RunDevelopment - hmm, surprising there isn't anything.  I didn't look extensively but does wand not support those variants?  Pillow seemed like it supported BC7 but maybe not BC1.

**Comment by RunDevelopment** [comment]
Wand requires, well, [Wand to be installed](https://docs.wand-py.org/en/0.6.5/guide/install.html) onto the user's system, so it's not really useful to us even if it can read them.

**Comment by iwubcode** [comment]
@RunDevelopment - whoops, glossed over that.

As for C/C++ libraries, there are likely quite a few. I have heard good things about https://github.com/akb825/Cuttlefish .  I haven't used it personally however.  Nor do I really know what implications that would have triggering it from Chainner.

**Comment by RunDevelopment** [comment]
This seems interesting, but I'll have to test it. Cuttlefish uses [FreeImage](https://freeimage.sourceforge.io/features.html) to load DDS files and that library doesn't specify which DDS formats are supported.

**Comment by joeyballentine** [comment]
Could we just look at how some other programs deal with these formats, if they're open source, and just PR pillow with the ability to read them? I think that would be better than adding another dependency

**Comment by joeyballentine** [comment]
How about we just read the raw files into numpy and write a custom implementation for decoding the data into something usable?

**Comment by RunDevelopment** [comment]
I think you severely underestimate the complex of DDS formats, but please prove me wrong. It would be awesome if that worked.

**Comment by iwubcode** [comment]
@RunDevelopment - I don't know much about it but it looks like there were several dependencies that Cuttlefish was using.  I may be wrong but for instance the `ISPCTextureCompressor` seems to provide a fast speed up for CPUs that support it.

For outputting PNG, couldn't you continue to use whatever you're using now?

**Comment by RunDevelopment** [comment]
@iwubcode Sorry, that's not what I meant. I wanted to use Cuttlefish without making bindings for it, so I looked at the CLI. If the CLI was able to output PNGs, we could ask the CLI to convert DDS to PNG and then read the PNG. I was still just looking for a way to read DDS files.
