### ISSUE TITLE
ONNX fail

### ISSUE THREAD

**Issue by AntoineNFT** [chaiNNer-org/chaiNNer#1434]
unable to download ONNX in dependency manager on mac OS.
do you know if Chainner still works without ONNX?

<img width="733" alt="Capture d’écran 2022-12-25 à 07 58 53" src="https://user-images.githubusercontent.com/119852785/209459542-8eb2a6f8-865e-4c6d-b0ba-1f95f6ab407d.png">

chainner v0.16.1

**Comment by RunDevelopment** [comment]
The version of ONNX we use doesn't support Apple M1 macbooks. However, we will soon bring out an update that will bring M1 support for ONNX in chaiNNer.

> do you know if Chainner still works without ONNX?

Yes, chaiNNer still works without it. PyTorch, NCNN, and ONNX are all optional features, but you need at least one of them to upscale images. Typically, PyTorch is the best option for general upscaling (i.e. all models in the [upscale wiki model database](https://upscale.wiki/wiki/Model_Database) are models for PyTorch).

ONNX is only necessary when you want to use upscaling models ending with `.onnx`.

**Comment by AntoineNFT** [comment]
thanks you !!
and merry christmas

**Comment by joeyballentine** [comment]
Merry Christmas! Once the holidays are over I'll be releasing an update with that new onnx version. 

@RunDevelopment one thing I've been thinking about is i still think we should stop using the term "dependencies" for the optional stuff. Tons of people think they need all three of these.

**Comment by RunDevelopment** [comment]
> one thing I've been thinking about is i still think we should stop using the term "dependencies" for the optional stuff. Tons of people think they need all three of these.

Once we have packages, we might as well call it the "Package manager". When the user opens it the first time, we could show a little overlay explaining that packages add more nodes and are entirely optional.

**Comment by RunDevelopment** [comment]
ONNX should now be supported on M1. This includes load/running model and converting model to NCNN. 

The only caveat is that fewer models can be converted to NCNN, compared to ONNX on Windows or Linux. Most common models are supported, though.
