### ISSUE TITLE
There should be an IF Node to redirect the flow to different chains in certain cases

### ISSUE THREAD

**Issue by Vendrel** [chaiNNer-org/chaiNNer#1436]
For example, we need a certain resolution input.* If the actual input **image resolution is bigger** than expected then we must downscale it; it's a **simple resize node**. But **if smaller** than expected then an **AI upscaler path** should be applied. 

An **IF node could handle it**, without manually fitting the node system to the case.

Of course, the nodes the IF node doesn't give data to, **should act like Disabled Nodes** where Disabled Nodes **should act like Connections**; in this case: connections carrying no data, seamlessly.

Best! :)

*The actual case is: I want to make a 8K result. AI upscaler quadruples their inputs only so our input must be at 2K resolution. Thereby: >2K and <2K input images require a little different node configuration. An IF Node could make one configuration universal for these cases.

**Comment by joeyballentine** [comment]
We already have this planned: https://github.com/chaiNNer-org/chaiNNer/issues/148

**Comment by RunDevelopment** [comment]
Closing this now since progress is tracked in #148.
