### ISSUE TITLE
Support for M2

### ISSUE THREAD

**Issue by trancefusiondesign** [chaiNNer-org/chaiNNer#1438]
I just installed ChaiNNer on my new MacBook Pro M2 running Monterey. When I attempt to upscale, the process just runs indefinitely. Just wondering if ChaiNNer doesn't work on an M2. :)

**Comment by RunDevelopment** [comment]
What did you use for upscaling, PyTorch or NCNN? 

Also, does chaiNNer not work in general? If you replace the Upscale node with a Resize (Factor) node (just as a test), will it work?

**Comment by trancefusiondesign** [comment]
I got it to work. I neglected to add the PyTorch Convert to NCNN module. It works now.

On a sidenote, I am using the realesr-general-x4v3.pth model for upscaling animated artwork. Could you recommend a model for photorealistic artwork? I would appreciate it.

**Comment by trancefusiondesign** [comment]
BTW. It took 15 seconds to render on my M2 (base model with 8G RAM). I ran the same procedure on my Intel and it took 2 minutes. Super happy with the speed boost.

**Comment by RunDevelopment** [comment]
> I got it to work

Nice 👍 

> Could you recommend a model for photorealistic artwork?

We have a whole [model database](https://upscale.wiki/wiki/Model_Database) and someone made a website [comparing them all](https://phhofm.github.io/upscale/multimodels.html) as well as [some favorites](https://phhofm.github.io/upscale/favorites.html) :)

That being said, if you just need something quick, try out UltraSharp and UniScaleV2. Those are general-purpose models, so they are a good starting point. Those 2 models and most mentioned on the comparison website can be found in the model database.

**Comment by RunDevelopment** [comment]
I'm gonna close the issue now since you got it to work.
