### ISSUE TITLE
Error report: No open ports available

### ISSUE THREAD

**Issue by vikgen19** [chaiNNer-org/chaiNNer#1448]
```
UnhandledRejection Error: No open ports available
```
ChaiNNer: chaiNNer 0.16.1
OS: Windows NT 10.0.19045

**Comment by joeyballentine** [comment]
Does Windows NT do anything weird in regards to allowing/blocking programs from starting servers?

**Comment by joeyballentine** [comment]
Closing this issue as it had no follow-up
