### ISSUE TITLE
Reduced performance

### ISSUE THREAD

**Issue by Skandery** [chaiNNer-org/chaiNNer#1461]
**Description**
I noticed that the upscaling time increased from 0.14.2 to 0.15+ for somes models, especially with an AMD graphics card

I did several tests (on 10 images in batch):

With the model  "4x_eula_digimanga_bw_v2_nc1_307k" https://upscale.wiki/wiki/Model_Database#Manga

**RX 6800 XT**

_0.14.2 / 0.16.1
8 sec / 18 sec_

**RTX 3070**

_0.14.2 / 0.16.1
7 sec	/ 8  sec_

With "realesrgan-x4plus", the upscaling time is more or less the same

**RX 6800 XT**

0.14.2 / 0.16.1
8.5 sec   /  8.5 sec

**Information:**

- Chainner version: 0.15.0+
- OS: Windows 10

**Comment by joeyballentine** [comment]
Just to confirm, this is something you can consistently get when switching between versions?

**Comment by joeyballentine** [comment]
And the degraded AMD performance is with NCNN? And Nvidia with PyTorch?

**Comment by Skandery** [comment]
> Just to confirm, this is something you can consistently get when switching between versions?
I tried almost all the versions above the 0.15.0, they all have the same issue 

> And the degraded AMD performance is with NCNN? And Nvidia with PyTorch?
I tried both with NCNN, sorry, I forgot to mention that.

**Comment by joeyballentine** [comment]
I have no clue what could have caused that, afaik the only NCNN related thing that's changed since then is the fp16 thing, same as #1463

**Comment by theflyingzamboni** [comment]
It appears that it's OoMing and splitting much more on the current release than 0.14.2.

**Comment by theflyingzamboni** [comment]
Ohhh, I forgot that the issue was that *every* model was being run as fp16 previously. @Skandery can you make sure the model you're upscaling with is fp16?

**Comment by joeyballentine** [comment]
Maybe we should consider having a fp16 toggle in settings like we have for pytorch? Where it would always convert to fp16 before running the model

**Comment by theflyingzamboni** [comment]
Could, but I'm not sure what the point would be, since it's written right into the model and can be set when converting it in the first place.

**Comment by joeyballentine** [comment]
The point would be to avoid issues like this being posted, if that's the issue

**Comment by Skandery** [comment]
> Ohhh, I forgot that the issue was that _every_ model was being run as fp16 previously. @Skandery can you make sure the model you're upscaling with is fp16? If it's fp32, it will be slower now because fp32 models are now correctly run in fp32 mode instead of fp16 mode.

You are absolutely right, it's a fp32, that's the problem, I understand now, sorry for the false issue.

For fp16 model
v0.14 / v0.16
14sec / 14sec
8281ko / 8281ko

For fp32 model
v0.14 / v0.16
14sec / 27sec
8268ko/ 8120ko
