### ISSUE TITLE
"Load image" does not invalidate when file changes on disk

### ISSUE THREAD

**Issue by zopieux** [chaiNNer-org/chaiNNer#1467]
**Information:**

- Chainner version: 0.16.1
- OS: Windows

**Description**
1. Create a *Load image* node and an *Image preview* (just to have some output)
2. Select a file, say `foo.jpg`, run chaiNNer
3. Overwrite `foo.jpg` on disk
4. Select the same file in the hope to trigger a cache invalidation

**What happens:** the old image remains shown
**What should happen instead:** the new image should be loaded

The only way to clear the cache is to load a random *different* image, then `foo.jpg` again. Annoying :-)

I understand it can be tricky or even undesirable to watch for live filesystem updates but I'd suggest either:
1. rework the logic when the user picks a file: even if they pick the same file, proceed to load in case it changed on disk
2. add a refresh/reload button on the *Load image* node

Note this applies to all loading nodes that read from the disk.

**Logs**
Irrelevant, this is a caching issue.

**Comment by joeyballentine** [comment]
> The only way to clear the cache is to load a random different image, then foo.jpg again. Annoying :-)

nope, you can right click and select the refresh option, which was added specifically for this purpose.

I did try to implement file watching, but I couldn't get it to work properly, so the right click option was added instead.

**Comment by zopieux** [comment]
> nope, you can right click and select the refresh option, which was added specifically for this purpose.

Oh well, TIL. You mean *Refresh preview* right?

**Comment by joeyballentine** [comment]
Yes exactly. I guess we could be a bit more specific with that since it's not just refreshing the preview but actually rerunning and re-caching that node (starter nodes get cached)

**Comment by zopieux** [comment]
Yeah changing the wording sounds good.

**Comment by RunDevelopment** [comment]
Resolved by #1643.
