### ISSUE TITLE
Macos M1 NCNN issue

### ISSUE THREAD

**Issue by kasparovabi** [chaiNNer-org/chaiNNer#1474]
sometimes it works for 1 image then give errors and sometimes it gives error at the first attempt

Error

An error occurred in a NCNN Upscale Image node:

A critical error has occurred. You may need to restart chaiNNer in order for NCNN upscaling to start working again.

Input values (partial):
• Image: RGB image 1024x1024
• Tile Size: Auto (estimate)
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/10400784/main.log)
[renderer.log](https://github.com/chaiNNer-org/chaiNNer/files/10400785/renderer.log)

**Comment by kasparovabi** [comment]
i tried other versions as mentioned in other threads but didnt work neither

**Comment by joeyballentine** [comment]
Try setting a smaller tiling amount, and restart chainner before trying again
