### ISSUE TITLE
Watermark Module

### ISSUE THREAD

**Issue by M4CC** [chaiNNer-org/chaiNNer#1476]
**Motivation**
Would be really awesome to have a watermark module to slap watermarks automatically before the image is saved.

**Description**
Would be nice to have the following settings:
Image: gif/png with transparent background
Position: Top-right / Top-left / Bottom-Left / Bottom-Right

I think rotation and padding could be handled previously and baked into the watermark image itself. 
Opacity: % selector would be a nice to have.

**Alternatives**
For the time being I'm using another software to watermark images one by one.

**Comment by theflyingzamboni** [comment]
You could actually do this already with existing nodes if you want, though the positioning is more complicated (still possible) to get. I wonder if it wouldn't make more sense for us to add an Align Image node with horizontal and vertical position settings, and then make a preset for watermarking.

**Comment by 0x4E69676874466F78** [comment]
#984

**Comment by M4CC** [comment]
Oh, I see someone already created a flow for this! Thank you @0x4E69676874466F78 and @theflyingzamboni. Sorry for the duplicated thread!
