### ISSUE TITLE
Dependency manager not working, unable to download packages

### ISSUE THREAD

**Issue by polymood** [chaiNNer-org/chaiNNer#1497]
Hello, I have just installed chaiNNer. I have tried to install the packages in the dependency manager but nothing happens. The download never starts even after an hour. I have tried the following : 

- Running as administrator ❌ 
- Disabling my antivirus's Firewall ❌ 
- Creating rules for chainner.exe in Windows defender ❌ 

And I didn't find any useful information in the Issues tab.
I am running Windows 10 22H2, Nvidia GPU (RTX 2060)

**Comment by joeyballentine** [comment]
Can you send your log files? Help > open logs folder

**Comment by polymood** [comment]
[renderer.log](https://github.com/chaiNNer-org/chaiNNer/files/10468032/renderer.log)
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/10468033/main.log)

**Comment by polymood** [comment]
It seems to be downloading now. I have removed python from Path in the Environment Variables as well as the variables PYTHONHOME and PYTHONPATH

**Comment by RunDevelopment** [comment]
The dependency manager can now give you pip commands to run them yourself. This means that you no longer need to rely on the dependency manager and can install necessary dependencies yourself. So the issue should be closed now.
