### ISSUE TITLE
how to add already upscaled batch images as "upscaled background" to upscale face GFPGANv1.4

### ISSUE THREAD

**Issue by BahzBeih** [chaiNNer-org/chaiNNer#1512]
Peace, i already upscaled batch images with "topaz video enhance" and i want to use them as "upscaled background" to upscale faces with GFPGANv1.4, so how i can do this?

**Comment by joeyballentine** [comment]
You can use the "image pairs iterator" for this. Hook the originals up to the face upscale node, and hook the upscaled ones up to the upscaled background input in the face upscale node. Then save the results
