### ISSUE TITLE
add support to LDSR upscale model which based on stable diffusion v1.4

### ISSUE THREAD

**Issue by BahzBeih** [chaiNNer-org/chaiNNer#1513]
Peace, i hope you add support to LDSR upscale model which based on stable diffusion v1.4, i know stable diffusion is in the future plans, but i hope at least we have stable diffusion upscale model now 🤞🤞🤞
i think this is the model space on replicate.com
https://replicate.com/nightmareai/latent-sr

**Comment by 0x4E69676874466F78** [comment]
Duplicate: https://github.com/chaiNNer-org/chaiNNer/issues/925

**Comment by joeyballentine** [comment]
Closing because this is a duplicate. I still need to look into this at some point. If it requires all the same dependencies and code that SD does, then i probably won't implement it any time soon. But if it's similar to other models I've implemented, then i can probably do it soonish

**Comment by BahzBeih** [comment]
> Closing because this is a duplicate. I still need to look into this at some point. If it requires all the same dependencies and code that SD does, then i probably won't implement it any time soon. But if it's similar to other models I've implemented, then i can probably do it soonish

i really hope to see it supported, because this model results are very impressive 🤞🤞🤞
