### ISSUE TITLE
Don't close main application when opening the latest version page

### ISSUE THREAD

**Issue by s-ilent** [chaiNNer-org/chaiNNer#1517]
**Motivation**
When I open chaiNNer, it's typically because I have something I want to upscale or modify. And when the version is out of date, I'm interested to go and install the new update. 

However, the presence of a new version doesn't stop me from wanting to work on what I opened chaiNNer for. Visiting the page, downloading the install files, and running the installer takes longer than running some tests with existing graphs and both can be done at the same time up until the point of actually installing the new version. 

Having chaiNNer forcibly shutdown when you choose to visit the new version page is irritating.

**Description**
Please don't close chaiNNer when opening the page for the latest version. 

**Alternatives**
The existing dialogue could have a second button added to it, with the options changed to download, download and close, and ignore.

**Comment by joeyballentine** [comment]
This must be a bug. It shouldn't be closing chainner when you open the release page. I'll fix that
