### ISSUE TITLE
Implement SCUNet? (Practical Blind Denoising via Swin-Conv-UNet and Data Synthesis)

### ISSUE THREAD

**Issue by zelenooki87** [chaiNNer-org/chaiNNer#1524]
Hi.
Could you please implement this project into chainner?
"Practical Blind Denoising via Swin-Conv-UNet and Data Synthesis"
https://github.com/cszn/SCUNet

Better results than Swinir for denoising purpose, and real models doing blind denoising pretty well.

That would be great!

**Comment by joeyballentine** [comment]
Whoops, thought I already responded to this. Yeah I plan on implementing it at some point, but idk when. Possibly soon. It's been requested a lot.

**Comment by RunDevelopment** [comment]
Resolved by #2102.

**Comment by zelenooki87** [comment]
Could you please implament tile option for Scunet?
On photos >15Mpx I could not get it work on RTX 3090.
Thanks!
