### ISSUE TITLE
Fails to launch using Wayland on Linux

### ISSUE THREAD

**Issue by illode** [chaiNNer-org/chaiNNer#1527]
**Information:**

- Chainner version: any
- OS: Arch Linux

**Description**
Attempting to launch chaiNNer without X11 fails with:
```
❯ chainner
[647261:0201/095909.648082:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[647261:0201/095909.648114:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
[1]    647261 IOT instruction (core dumped)  chainner
```

Electron has supported wayland with the flags `--enable-features=UseOzonePlatform --ozone-platform=wayland` since ~v12 and `--ozone-platform-hint=auto` since ~v18. I also can't test to see if it works since there's no way to pass the arguments to electron.

**Comment by joeyballentine** [comment]
Someone with more Linux experience is going to need to fix this for us

**Comment by illode** [comment]
I don't know anything about packaging electron so I can't experiment much myself, but as far as I understand it should just work if we could pass the arguments electron itself.

Chromium, for instance, works if I just run it with `chromium --ozone-platform-hint=auto` or  `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland`. Discord Canary launches (then crashes) with `discord-canary --enable-features=UseOzonePlatform --ozone-platform=wayland`

If you're able to add them, or can tell me how to add them, I can test it out. Unfortunately, I don't really know how electron works, so I'm not sure how.

[Here's](https://github.com/electron/electron/issues/10915#issuecomment-789068112) an electron issue with more info.
