### ISSUE TITLE
Duplicating notes makes them bigger

### ISSUE THREAD

**Issue by PanZWarzywniaka** [chaiNNer-org/chaiNNer#1547]
**Information:**

- Chainner version: 0.17.0
- OS: Manjaro Linux

**Description**
1. Create a note
2. Duplicate it
![image](https://user-images.githubusercontent.com/38562250/218176399-365f8026-df8b-42d4-8f52-6425e213ad7a.png)

**Comment by joeyballentine** [comment]
Thanks for reminding me about this, this has needed to be fixed for a long time and i completely forgot about it

**Comment by PanZWarzywniaka** [comment]
It should be a quick fix, btw great project.

**Comment by theflyingzamboni** [comment]
Fixed by #1582
