### ISSUE TITLE
PyTorch Inpaint node error

### ISSUE THREAD

**Issue by noname8556** [chaiNNer-org/chaiNNer#1592]
**Information:**

- Chainner version: 0.18.0
- OS: Manjaro, Windows 10

**Description**
Error occurs with PyTorch Inpaint Node on both Manjaro and Windows. PyTorch is used in CPU mode. The error also occurs with other images, but not always. Log files are attached.

![overview](https://user-images.githubusercontent.com/126181578/220974991-eb43e4ae-f1d6-4738-a7f0-a7bf8611cd08.png)
[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/10816145/logs.zip)

**Comment by theflyingzamboni** [comment]
Yeah, I meant to add padding to the preprocessing but forgot. LaMa requires images to be divisible by 8. That's why it only errors on some images. I'll fix that soon.

**Comment by joeyballentine** [comment]
you should be able to re-use the padding code that's included with swinir, if you don't already have something
