### ISSUE TITLE
Is there a way to output images as PNG-8

### ISSUE THREAD

**Issue by nabileisa** [chaiNNer-org/chaiNNer#1620]
Hi, I have been experimenting with the application and I find it very useful , thank you for your had work.
I Have a question though,
 is their a way to output images as `PNG 8` ?
I looked throughout the application and couldn't find an answer so I thought I might ask here.

**Comment by RunDevelopment** [comment]
No, there is not. 

Right now, Save Image with PNG uses OpenCV's default settings. Those default settings use true color and auto-detect the number of channels (so e.g. it will only use 8 bit per pixel for grayscale images and 24 bit per pixel for RGB images). Unfortunately, OpenCV also doesn't provide us with [options](https://docs.opencv.org/4.7.0/d8/d6a/group__imgcodecs__flags.html#ga292d81be8d76901bff7988d18d2b42ac) to save in png8 mode.

That being said, PIL seems to support [more PNG encoding options](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#png-saving) ([png8 example](https://stackoverflow.com/questions/6114534/converting-png32-to-png8-with-pil-while-preserving-transparency)), so we could potentially add support for this if needed.

May I ask what you want png8 for? The main use for PNG is to be a lossless image format, so why compress colors down to a 256 color palette?

---

For those wondering [what png8 is](https://stackoverflow.com/a/22707268/7595472).

**Comment by nabileisa** [comment]
Thanks for the reply,
> May I ask what you want png8 for? The main use for PNG is to be a lossless image format, so why compress colors down to a 256 color palette?

My current use case is batch upscaling manga image files,
Manga is by design black and white so the additional colors in `PNG 24` are not needed, The idea was to use `PNG 8` which would provide the benefit of being much smaller than `PNG 24` while retaining decent quality and not having compression artifacts like jpeg, which would help with storage.

I would love if their was an option to choose in the `Save Image` node in the future same way that jpeg has the quality slider
But for now your reply set me on the right direction , 
If I apply  `change color space`  node from RGB to GRAY before  `Save Image` node, the image is saved as `PNG 8`

Additional question if you don't mind,
Is there a way to upscale to a specific image size or upscale factor when using the `Upscale Image` node and upscale models?
I have been using the `Resize to side` node to downscale to the needed resolution after the fact but that seem wasteful somehow.

**Comment by joeyballentine** [comment]
The way you are upscaling now is the way you have to do it. Upscaling models have fixed scales, so there isn't a way to set a desired output size. You just have to downscale after.

**Comment by nabileisa** [comment]
> The way you are upscaling now is the way you have to do it. Upscaling models have fixed scales, so there isn't a way to set a desired output size. You just have to downscale after.

Yeah , I thought as much , just wanted to make sure, 
The reason I asked was because [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) use same models but provide the ability to choose size or factor , but they probably do the downscaling automatically under the hood
Anyway thank you very much for the amazing  application and the quick replies
