### ISSUE TITLE
How to use load model?

### ISSUE THREAD

**Issue by thecosss** [chaiNNer-org/chaiNNer#1647]
I've installed all 3 dependencies but don't have a clue on how to use the Load model node. Where do I get the model file? For example RemBg.

**Comment by joeyballentine** [comment]
Links to supported models can be found in the readme. https://github.com/chaiNNer-org/chaiNNer#model-architecture-support

**Comment by ImOnDialup** [comment]
> Links to supported models can be found in the readme. https://github.com/chaiNNer-org/chaiNNer#model-architecture-support

That doesn't tell us how to load the model. I've installed Pytorch. I have the node open. I have no idea where pytorch is located in my files and no download location was specified, so it's useless to me.

**Comment by ImOnDialup** [comment]
> Links to supported models can be found in the readme. https://github.com/chaiNNer-org/chaiNNer#model-architecture-support

That doesn't tell us how to load the model. I'm following the instructions from https://github.com/chaiNNer-org/chaiNNer and I can't get any further than loading the model. I downloaded pytorch, and then that's it, no other instructions link that to upscaling the image and locating the file on the PC. We're artists, not programmers.

**Comment by joeyballentine** [comment]
First you download the models to wherever you want on your computer, then you click on the "select model" part of the load model node and select the file from your computer. You also do the same thing with load image. Then you connect both of those nodes to the upscale image node, and then connect that to the save image node. Then you select your output directory and name. There are good examples here: https://github.com/Kim2091/kim-chaiNNer-Templates

**Comment by joeyballentine** [comment]
Closing this as this should be covered by the node docs (if the op is seeing this, it's an unreleased feature, and hopefully my explanation helped)
