### ISSUE TITLE
pytorch  dont downloaded 

### ISSUE THREAD

**Issue by kingal2000** [chaiNNer-org/chaiNNer#1649]
my interent is bad for console download  i want root for 
manual  root to add downolad file cuda pytorch file or use windows commend line

**Comment by joeyballentine** [comment]
The integrated python path is `%appdata%/chaiNNer/python/python`

**Comment by RunDevelopment** [comment]
I'm going to close this issue now, because the dependency manager now has the tools to make manually installing PyTorch a lot easier.
