### ISSUE TITLE
How can I save an Image Sequence.

### ISSUE THREAD

**Issue by hansnolte** [chaiNNer-org/chaiNNer#1659]
Hello everyone.

I want to cutting out a person in a Video.
But since none of the existing "Video Types" supports an Alpha Channel, I wanted to save a PNG-Sequence.
But how?

A little tip would be nice.

Many greetings
Hans

**Comment by hansnolte** [comment]
Hi Joey,
really great Project and many thanks for your answer. 
I just joined today, so I have to feel my way through first.

**_"...you can use text append with the iterator's index..."_**

What is the the iterator's index?
With this setting the one image will be overwritten again and again.
![append](https://user-images.githubusercontent.com/7922627/225940522-b18dea2a-ad6e-4c6e-90b8-b3e1552cc3aa.jpg)

**Comment by joeyballentine** [comment]
"Frame Index" in the load frame as image node. That's the number of frame you're on. If you append that to the name, you'll have a sequence like pic-0, pic-1, pic-2, etc

**Comment by hansnolte** [comment]
Great, It works!
Many thanks Joey.

Bye
Hans
