### ISSUE TITLE
Resizing To Longest Side (Hight or Width) without oversizing?

### ISSUE THREAD

**Issue by MrDkVV** [chaiNNer-org/chaiNNer#1662]
**Motivation**
I would like to optimize the quality and normalize the size of the images in my folders.

**Description**
I use a 3840x2160 4K monitor. I would like have all the images in a folder resized to this. 

I was hoping to use a guided upscale, where the initial image would be resized using Lactose, then use guided upscaling to fill in the detail? Perhaps I'm getting a head of the AI technologies :) I'm new to this like everyone.

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/82465898/226535560-50d55cda-547f-4182-ac13-b12ea2f6966c.png">

**Alternatives**
All files in the folder have a different initial size. The only other options I see are to, 4x the initial image, then downscale them using Lactose and crop the final image.

**Comment by RunDevelopment** [comment]
This is not how guided upscaling works. The idea behind guided upscaling is that the source and guide images contain the same subject, but in different domains (=different aspects of the same thing). E.g. the source image could be a low-res depth map and the guide could be a high-res RGB image of a scene ([example](https://github.com/prs-eth/PixTransform/blob/master/imgs/Frontpage.png)), or the source image could be a low-res version of the guide image with some expensive filter applied to it ([example](https://people.csail.mit.edu/hasinoff/pubs/ChenEtAl16-bgu.pdf)). Importantly, source and guide must depict the same subject, so both images must have the same format. So any sort of cropping will make guided upscaling impossible, unless you do it to both the source and guide image equally.

So here's what I would do: Forget about guide upscale. Just 4x your input image, and then resize + crop down to 4k.

---

Also, the image sampling method you want is called Lanczos (after [its inventor](https://en.wikipedia.org/wiki/Cornelius_Lanczos)). We don't tolerate lactose here :)

**Comment by MrDkVV** [comment]
Hello @RunDevelopment ,


I have no AI or background, simply using your application on face value to 'chain' actions together to manipulate the images to my end expectations.

My expectations are the application lets me connect the dots it should work, or internally handle the mechanics... and not freak out and throw out conditional errors. 

So then if I'm understanding then really, I'm asking for the development of both input sources to be scaled internally to the software. I'll let your teams figure that out as I'm no programmer :)


Yes, doing resize + crop down to 4k as the alternative at this time, hopping for a better solution then overprocessing an image. 


Thank you again. 

---

We don't tolerate lactose here :) I don't Lanczos only cuz i don't English ether :)

**Comment by RunDevelopment** [comment]
> Yes, doing resize + crop down to 4k as the alternative at this time, hopping for a better solution then overprocessing an image.

Then it's probably not possible right now. You essentially want this, right:
- If image >= 4K, then crop + scale down.
- If image < 4K, then upscale + crop + scale down to 4K.

Unfortunately, this isn't possible right now. We do plan to make this (and more things like it) possible in the future, but there is still a lot of work to do before that. Sorry.

> My expectations are the application lets me connect the dots it should work, or internally handle the mechanics... and not freak out and throw out conditional errors.

Good point.

**Comment by RunDevelopment** [comment]
I'm going to close this now.

Progress towards conditional logic is tracked in #148, and the improving the user-friendliness of conditional errors in tracking in #1673.
