### ISSUE TITLE
Connect to Automatic1111? How does that work?

### ISSUE THREAD

**Issue by Ionaut** [chaiNNer-org/chaiNNer#1671]
I see it as not connected on the 'manage dependencies" modal. How to connect it?

**Comment by joeyballentine** [comment]
launch the webui with the `--api` flag. So like `./webui.bat --api`. Then open chaiNNer

**Comment by joeyballentine** [comment]
I am going to assume you got it to work, and will close this ticket. If you still need any help, feel free to reply here again.
