### ISSUE TITLE
Unable to install on Mac OS 10.15.7 Error: Failed to fetch

### ISSUE THREAD

**Issue by cindywilson888888** [chaiNNer-org/chaiNNer#1680]
Hi, I'm trying to install ChaiNNer on my Mac OS 10.15.7, but I cannot because "Critical Error: A critical error occurred while processing the node data returned by the backend. Error: Failed to fetch". I've read other bug reports addressing the same error but none was helpful for me. Please help me.
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11075581/main.log)

**Comment by joeyballentine** [comment]
Looks like at some point we added a dependency (google-re2) that doesn't have pre-built macos 10 whls. This means your Mac is trying to compile the package itself, but you don't have the necessary developer tools installed to do so.

So, this means to fix this you either need to upgrade to macos 11 or install the XCode Command Line Tools.

**Comment by cindywilson888888** [comment]
Thanks @joeyballentine  I installed the XCode Command Line Tools (my Mac OS 10.15.7 is up to date), but there was the same error notice. Anything else I can do?
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11083343/main.log)

**Comment by joeyballentine** [comment]
Hmmm.... Looks like it's still unable to build the package as it requires something from MacOS 11. We might need to just disable whatever functionality uses that package in order to get chaiNNer compatible with 10.15 again. Is there any chance you'd be able to update to 11?

**Comment by cindywilson888888** [comment]
I guess if it shows my mac is up to date, OS 11 won't be compatible to my mac?
![Screen Shot 2023-03-27 at 7 23 26 PM](https://user-images.githubusercontent.com/129038484/228088780-df013665-bd87-4019-a525-68c3164b3394.png)

**Comment by cindywilson888888** [comment]
Or do you think I should try any previous version of ChaiNNer that is compatible with 10.15?

**Comment by joeyballentine** [comment]
I don't remember exactly which version added that new dependency, but I think [v0.18.1](https://github.com/chaiNNer-org/chaiNNer/releases/tag/v0.18.1) should work for you. 

If not, [v0.17.1](https://github.com/chaiNNer-org/chaiNNer/releases/tag/v0.17.1) is most likely to work, barring some other kind of issue.

**Comment by Tob1G-P** [comment]
Hi @joeyballentine @cindywilson888888 
I'm getting the same error on Windows 10 "A critical error occurred while processing the node data returned by the backend. Error: Failed to fetch".
How can I fix that?
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11148886/main.log)

Thank you!
