### ISSUE TITLE
Pass a directory list to the image file iterator

### ISSUE THREAD

**Issue by William-Owen** [chaiNNer-org/chaiNNer#1682]
**Motivation**
I have several folders that contain image sequences that I want to run through an upscaler. This would be a great job to fire off overnight, but I can only do one directory at a time.

**Description**
I would like a directory list node to allow me to select multiple directories. This node would pass the directory name into the Image File Iterator, which would then process the files in those directories. The Directory list node could also expose a folder name that could be passed into the save file path, for example.

**Comment by joeyballentine** [comment]
Right now there's a few ways you'd be able to get this functionality (without us having to make code changes):

1) copy and paste the iterator, and change the directory for each. It will then run all of them in sequence 
2) put all the directories you want into a single directory, then select that one. The iterator looks in subdirectories (recursively)
