### ISSUE TITLE
Median Stack Node

### ISSUE THREAD

**Issue by joeyballentine** [chaiNNer-org/chaiNNer#1686]
A suggestion from a user on Discord.

An image median node. Basically, stack _n_ images (probably just 4 for now), sort each pixel, along the stack axis, and then take the middle one (or average of the middle two if an even number). This would probably be pretty inefficient to do pixel by pixel but I bet numpy has a function for this.

**Comment by RunDevelopment** [comment]
What's the median of a list of pixels? Let's say we have 3 pixels, how do we define what their median is? Do we calculate the median per RGB channel, do we do it in a perceptual color space, or do we define some selector function that turns each pixel into a single numerical value (e.g. lightness)?

**Comment by joeyballentine** [comment]
This is how it was described to me: https://discord.com/channels/930865462852591648/930865463318179952/1087449448906502224

**Comment by JustNoon** [comment]
In imagemagick and photoshop which is probably the gold standard, median is just intensity in RGB colorspace.

[This ](https://petapixel.com/2013/05/29/a-look-at-reducing-noise-in-photographs-using-median-blending/)is an excellent write-up on the subject.

**Comment by JustNoon** [comment]
Implemented in #1745
