### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by thibaudart** [chaiNNer-org/chaiNNer#1693]
**Motivation**
To run on remote server

**Description**
Create our chain locally and be able to deploy it on remote server where we have only terminal access.

**Comment by joeyballentine** [comment]
CLI mode is already a thing (though not really documented at all). @RunDevelopment

**Comment by thibaudart** [comment]
It s nice! If anyone have some information, it could be great. At least an example to call the cli.

**Comment by dnblank123** [comment]
chainner run -help ?

**Comment by RunDevelopment** [comment]
[CLI mode has been documented](https://github.com/chaiNNer-org/chaiNNer/blob/main/docs/cli.md), and remote backends are tracked in #1875.
