### ISSUE TITLE
chaiNNer doesn't finish loading

### ISSUE THREAD

**Issue by YarivTawili** [chaiNNer-org/chaiNNer#1694]
Hi, I tried both installation and portable (windows), in both cases when the chaiNNer is loading for the first time it got stuck at the end.
Log attached.
Thanks

[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11132371/main.log)

**Comment by joeyballentine** [comment]
Hi. This will be fixed in today's release. Sorry about this it was our of our control

**Comment by joeyballentine** [comment]
[The update has been released](https://github.com/chaiNNer-org/chaiNNer/releases/tag/v0.18.4). Please let me know if the issue is fixed for you.

**Comment by brezelseppel** [comment]
I had the same error, now with 0.18.4 the GUI loads and works fine. Thank you!

**Comment by joeyballentine** [comment]
👍

**Comment by YarivTawili** [comment]
Fixed for me too. Thanks!
