### ISSUE TITLE
Critical Error A critical error occurred while processing the node data returned by the backend. Error: Failed to fetch

### ISSUE THREAD

**Issue by skinnerjack** [chaiNNer-org/chaiNNer#1707]
**Information:**

- Chainner version: [e.g. 0.11.0]
- OS: [e.g. Windows 10, macOS 10.13]

**Description**
A clear and concise description of what the bug is and how to reproduce it.

**Logs**
Logs help us to find the cause of many problems. To provide your logs, open Chainner and click _Help_ > _Open logs folder_ in the menu. Create a zip file with `main.log` and `renderer.log`, and [attach the zip file](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) to this issue.

Privacy information: Log files contain file paths of Chainner's application files and the files you processed with Chainner. These file paths may contain the name of your account (e.g. Users/michael/...). If your account is your real name, and you are not comfortable sharing, then do not upload your logs or replace all identifying text with something like "fake name".

**Comment by skinnerjack** [comment]
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11165018/main.log)
![screenshot](https://user-images.githubusercontent.com/57181362/230238331-c36ee60a-41c8-4c02-b745-9b44e9ddf659.png)

**Comment by RunDevelopment** [comment]
This bug has been fixed in [v0.18.4](https://github.com/chaiNNer-org/chaiNNer/releases/tag/v0.18.4). Please update to the latest version of chaiNNer.

**Comment by joeyballentine** [comment]
@skinnerjack have you tried 0.18.4 or 0.18.5 yet?

**Comment by joeyballentine** [comment]
Going to assume this is fixed and close this issue.
