### ISSUE TITLE
Critical Error A critical error occurred while processing the node data returned by the backend. Error: Failed to fetch

### ISSUE THREAD

**Issue by Lumhub** [chaiNNer-org/chaiNNer#1709]
- Chainner version: [0.16.1.0]
- OS: [Windows 10 Pro x64]

Description:
Error happened when I was running the ChaiNNer exe file for the first time.
 
![ChaiNNer error log](https://user-images.githubusercontent.com/127354565/230244023-abaefc13-85d6-4364-af29-9beba1c2c1bf.jpg)

Logs:
ZIP Attached with Log file (Main)
[main.zip](https://github.com/chaiNNer-org/chaiNNer/files/11165277/main.zip)

**Comment by joeyballentine** [comment]
Please try the latest version of chaiNNer and report back

**Comment by joeyballentine** [comment]
@mr-afa on the latest version of chaiNNer?

**Comment by mr-afa** [comment]
@joeyballentine my bad, it's working on 0.18.5

**Comment by joeyballentine** [comment]
@mr-afa great 👍
@Lumhub please let us know if it works for you on a later version

**Comment by Lumhub** [comment]
@joeyballentine after installing the latest version (0.18.5), and after downloaded the suggested packages, I've tried a simple task (load image, upscale, re treined model and save image nodes) but the task stop progressing half way, giving the Failed To Fetch error after I stop.
A Pentium(R) Dual-Core CPU T4300 @ 2.10GHz with 4,00 GB, running W10Pro, with an old NVIDIA Geforce G105M, with only 512mb, probably can´t deal with this kind of graphic tasks. 
Thanks

**Comment by joeyballentine** [comment]
Yeah your system is probably just too old. You barely have any RAM (which is needed for doing basically any image tasks) and your GPU for sure can't do any upscaling.
