### ISSUE TITLE
Error - RealESRGAN_x4plus.pth us unsupported by chaiNNer

### ISSUE THREAD

**Issue by mongoose79** [chaiNNer-org/chaiNNer#1736]
chaiNNer version: Alpha v0.18.5
OS: Windows 10
![Chainner Error](https://user-images.githubusercontent.com/21357104/232117874-de3ce04e-f064-4b6b-8dcb-040a11d70bac.jpg)

Could you help please?

**Comment by joeyballentine** [comment]
Did it actually download the file? It would say this if the file is corrupt for example

**Comment by joeyballentine** [comment]
Ok, I'll check to see if we accidentally broke something

**Comment by mongoose79** [comment]
Thank you!

**Comment by joeyballentine** [comment]
It loads perfectly fine for me. Can you send your main.log file from Help > Open logs folder (menu bar)

**Comment by mongoose79** [comment]
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11236764/main.log)
Please look for: "[2023-04-14 19:36:31.718] [info]  Backend: [15532] [ERROR] Model RealESRGAN_x4plus.pth is unsupported by chaiNNer"

**Comment by joeyballentine** [comment]
What GPU do you have? It actually appears to be erroring from an out-of-vram error, which you really would only be getting on model load if you had an insanely small amount of vram

**Comment by mongoose79** [comment]
![Display adapter 1](https://user-images.githubusercontent.com/21357104/232154864-00c148a1-1a9e-4a8e-94e4-914d673e6504.jpg)
![Display adapter 2](https://user-images.githubusercontent.com/21357104/232154866-7e9e4bd5-5b82-4d6e-865f-f52225cb5412.jpg)

Is this enough info?

**Comment by joeyballentine** [comment]
Yes. You only have 2GB of VRAM, which is a very small amount. You aren't going to be able to easily do much upscaling. I'd recommend only loading one model at a time, and upscaling only small images.

**Comment by gabriele2000** [comment]
> Yes. You only have 2GB of VRAM, which is a very small amount. You aren't going to be able to easily do much upscaling. I'd recommend only loading one model at a time, and upscaling only small images.

It still doesn't fix the problem... @mongoose79 clearly has a different problem.
The problem happens before stuff even starts to upscale, so leave the VRAM thing alone.
I have 4GB of VRAM, previous versions would load that model, latest version wouldn't and I have double the amount as him.

**Comment by joeyballentine** [comment]
Oh interesting -- I'm not sure what would have broken that on 0.18.5 but I suppose it's good that 0.18.6 fixed it. I guess it makes sense that it worked for me, because I was using a dev build that was essentially 0.18.6

**Comment by gabriele2000** [comment]
> I was using a dev build that was essentially 0.18.6

You compiled it, right?
Asking because I never found any dev build here.

**Comment by joeyballentine** [comment]
Sorta yeah, just running the code while i was working on stuff

**Comment by mongoose79** [comment]
I get this error on 0.18.6:
![Error2](https://user-images.githubusercontent.com/21357104/233129862-e389f88c-b604-4bc7-9307-d2a078233f02.jpg)
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11274951/main.log)
[renderer.log](https://github.com/chaiNNer-org/chaiNNer/files/11274952/renderer.log)
Error

An error occurred in a Upscale Face node:

Failed to run Face Upscale.

Input values (partial):
• Image: Grayscale image 2478x1594
• Upscaled Background: Grayscale image 9912x6376
• Output Scale: 8x
• Weight: 0.7

**Comment by joeyballentine** [comment]
> RuntimeError: CUDA error: out of memory

You ran out of VRAM

**Comment by joeyballentine** [comment]
VRAM is your video memory (The V stands for Video). 

There is no way to "reduce the parameters" of this. It just uses too much VRAM for your GPU (2GB is not enough for this). With regular upscaling we do tiling to save VRAM if necessary, but that can't be done with face upscaling for obvious reasons. You also can't take advantage of FP16 since your GPU doesn't have tensor cores.

**Comment by mongoose79** [comment]
Thanks. What do you think about this graphics card: ASUS Phoenix RTX 3050 8GB GDDR6? I plan to buy it. Is this enough for such operations?

**Comment by joeyballentine** [comment]
Yes 8GB is plenty. It's how much I have on my GPU.

**Comment by mongoose79** [comment]
Now it works. Thank you very much for the help!
