### ISSUE TITLE
GPU selector sets wrong GPU

### ISSUE THREAD

**Issue by felipemeres** [chaiNNer-org/chaiNNer#1744]
**Information:**

- Chainner version: 0.18.6
- OS: Windows 11

**Description**
The GPU selection under Settings doesn't match the GPU order in nvidia-smi. I have a 4090 and a 3090, if I select the 4090 and run pytorch it's actually using the 3090 and vice-versa.

**Comment by joeyballentine** [comment]
That's weird, because we get that GPU order from Nvidia SMI. Though, i think i remember someone else having this same issue. It's quite possible the list is just backwards

**Comment by joeyballentine** [comment]
@RunDevelopment I'm going to do that with my dependency refactor :) 

I'll be completely getting rid of the SMI process on the frontend and replacing it with the pynvml package. I'm just waiting on @theflyingzamboni to get back to me on how that package works with an AMD GPU so i can handle that properly.
