### ISSUE TITLE
[Feature Request]: Something in Windows Installer to let you know it's installed.

### ISSUE THREAD

**Issue by Vendaciousness** [chaiNNer-org/chaiNNer#1746]
**Motivation**
Please explain the problem you're having/why you propose this feature. Ex. I'm always frustrated when [...]

When I downloaded and ran the Windows installer "chaiNNer-0.18.6-x64-windows-setup.exe", today, nothing happened--_I thought_. I assumed it was crashing, but saw that something called "updater.exe" was trying to access the internet, so I looked further. It wasn't until I checked the Issues list that I realized it had installed. It runs so fast, the thought didn't occur to me and there's no notification or anything, so I assumed it had crashed. 

**Description**
Group the installer and the stuff chaiNNer does on first run (installing dependencies) and make a window with something like:
"Installing chaNNer..." 
then when done successfully, something like: 
"Installation complete! Click "chaiNNer" in Start Menu to run." etc... 

Alternatively, you could make a note in the install instructions eluding to how the install works. This is a kinda small issue, but I don't want you guys to lose even a single user because he/she thought the program hadn't worked. Thank you for making this amazing tool!

**Comment by joeyballentine** [comment]
Yeah this is kinda an ongoing issue. When we added CLI mode, we accidentally broke it opening after install. We can't really fix it until we move CLI to it's own executable.

Unfortunately, i can't add dialog boxes either, because the squirrel electron installer sucks. So there's kinda nothing i can do, as far as i know

**Comment by Vendaciousness** [comment]
Oh well...  It's not like the software doesn't install or it's crashing, so no big deal, IMO.

**Comment by joeyballentine** [comment]
well, lots of people have been confused by this, so to me it is a big deal... I just can't do much about it. I'm currently looking into some electron stuff again to see if there's maybe a way I can do a platform-agnostic alert box rather than trying to do it through the windows stuff.

**Comment by joeyballentine** [comment]
I was putting it in the release notes for a while, but gave up because i was still getting people asking about it anyway. People tend to not read things 😆

Putting it in the readme is still a good idea though, I'll do that real quick
