### ISSUE TITLE
Model for Compress File size of images

### ISSUE THREAD

**Issue by AdamBlazer** [chaiNNer-org/chaiNNer#1749]
Hello,

are there some models for compressing File size of images, that i can run with chaiNNer ?

I use upscalling models for 4K,8K resolution, but the file sizes are too big and i would like to compress it. Now i use online image compressers like this - https://www.iloveimg.com/compress-image

Thank you very much, chaiNNer is really helpful :)

**Comment by joeyballentine** [comment]
No. Save as webp or jpeg if you want to compress your images. AI will not help you here.

**Comment by joeyballentine** [comment]
I will note that there have been attempts to use various AI techniques to compress images and video, but none of those are viable for actual use, and are all just research theory right now. 

Also, glad you like chaiNNer :) sorry for such a fast ticket closing, but it's just not something we can do

**Comment by AdamBlazer** [comment]
> No. Save as webp or jpeg if you want to compress your images. AI will not help you here.

Save as Jpeg and choose best compression work very well, thank you very much!
