### ISSUE TITLE
file iterator does not wait for Stable diffusion (external) before passing next image resulting in multiple saves of the same image while skipping images in the process

### ISSUE THREAD

**Issue by li1i9** [chaiNNer-org/chaiNNer#1751]
- Chainner version: v0.18.6
- OS: Windows 10 Pro 22H2
- GPU RTX 2070 Laptop

File iterator does not wait for Stable diffusion (external) before passing the next image resulting in multiple saves of the same image while skipping images in the process.

Here are I placed two images for the iterator to work with.
In the output folder I'm receiving two saves of picture 1. 
Picture 2 has just been skipped completely.
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11275359/main.log)

**Comment by joeyballentine** [comment]
Could you send a screenshot of your chain setup please?

**Comment by li1i9** [comment]
![2Capture](https://user-images.githubusercontent.com/128749309/233155707-278af5fd-2c94-4e1e-9351-4d5ca066f830.PNG)
![Capture](https://user-images.githubusercontent.com/128749309/233155722-825a0def-d1d2-4c2b-932b-c33ca6c0aa62.PNG)

**Comment by li1i9** [comment]
If you like, I can send a cleaned-out example because this one is a new setup I'm trying to make.

**Comment by li1i9** [comment]
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11284973/main.log)
[renderer.log](https://github.com/chaiNNer-org/chaiNNer/files/11284975/renderer.log)
![001](https://user-images.githubusercontent.com/128749309/233334768-b6f8b263-987d-41ea-870a-d843040f7dbf.PNG)
![002](https://user-images.githubusercontent.com/128749309/233334771-d2b4f928-4516-4b13-a859-07101c1b49a7.PNG)

**Comment by joeyballentine** [comment]
I wonder if this has something to do with the caching we do on those nodes. @adodge will have to look at this probably, but I'll take a look myself later today

**Comment by li1i9** [comment]
If you need any additional images or tests, just hit me up. :)
I'm happy to help.
