### ISSUE TITLE
Error report: Object has been destroyed

### ISSUE THREAD

**Issue by bedalton** [chaiNNer-org/chaiNNer#1752]
```
TypeError: Object has been destroyed

    at click (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:498857)
    at MenuItem.click (node:electron/js2c/browser_init:2:30166)
    at a._executeCommand (node:electron/js2c/browser_init:2:35562)
```

ChaiNNer: chaiNNer 0.18.6 (and I believe all versions I have used since starting using the app a month or two ago)
OS: macOS 10.18

Not sure if this is a duplicate of #1665, #1691 , and #1700 and/or if this was also fixed by #1723, but on macOS Ventura, (and on the version I was on before, I think Monterey)
If you:
1. Close the main window
2. Don't quit the app (as it keeps running and does not quit automatically)
3. Click on File->New for a new window

The app shows the error with the options: Report, Exit and Ignore; No option opens a new window

**Comment by joeyballentine** [comment]
Ah! Thank you for providing steps to recreate it, that totally makes sense for what's happening. 

So on MacOS, you can close the main window but it still runs? I didn't know it would do that. Are you able to open the window again after you close it?
