### ISSUE TITLE
error with video frame iterator

### ISSUE THREAD

**Issue by traplover4200** [chaiNNer-org/chaiNNer#1758]
there is my log file
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11302772/main.log)
chain file
[upscale_videos.txt](https://github.com/chaiNNer-org/chaiNNer/files/11302773/upscale_videos.txt)
the model im using is 4x-AnimeSharp

**Comment by joeyballentine** [comment]
can you try muxing the video to mkv or something outside of chaiNNer? Basically try converting it to another format to see if there's just some weird encoding thing going on

**Comment by traplover4200** [comment]
i try converting it to mkv
ffmpeg -i bible_black_1.mp4 -c copy bible_black_1.mkv
it still give me a error
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11303004/main.log)

**Comment by traplover4200** [comment]
ok it was not showing my gpu to get it to work i del the .config/chaiNNer/ folder and reopen chainner it is working
