### ISSUE TITLE
Logic conditions

### ISSUE THREAD

**Issue by FluffyDiscord** [chaiNNer-org/chaiNNer#1759]
**Motivation**
I would like to skip files, for example by their name - does the name end with XX, then skip current image, else continue the chain.

**Description**
Add nodes for expressions like IF/THEN/ELSE, OR, AND, SWITCH for text values like file name, eg. if text value starts with then do X else do Y

**Alternatives**
Pre-filter the input data outside chainner

**Comment by RunDevelopment** [comment]
Duplicate of #148.
