### ISSUE TITLE
issue is:

### ISSUE THREAD

**Issue by 4nn313W5** [chaiNNer-org/chaiNNer#1764]
Hi there, I'm trying to install ChaiNNer on Windows 11, but I cannot because "Critical Error: A critical error occurred while processing the node data returned by the backend. Error: Failed to fetch". Can anyone help?

**Comment by joeyballentine** [comment]
Can you open Help > open logs folder (or navigate to users/(you)/appdata/roaming/chaiNNer/logs) and send your main.log file

**Comment by RunDevelopment** [comment]
Closed due to inactivity.
