### ISSUE TITLE
Batch images with Stable Diffusion WebUI

### ISSUE THREAD

**Issue by dlbone** [chaiNNer-org/chaiNNer#1765]
**Information:**

- Chainner version: [e.g. 0.18.6]
- OS: [e.g. Windows 11]

**Description**
Using either Image File Iterator or Video Frame Iterator and combining that with the Image-To-Image node (from here: https://github.com/chaiNNer-org/chaiNNer/pull/1500) , it only processes the first image/frame over and over. This results in an output folder of all the same processed frame.  I'm using this version of Stable Diffusion WebUI: 
python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: N/A  •  gradio: 3.23.0  •  commit: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)  •  checkpoint: [2182245415](https://google.com/search?q=2182245415908822cbac065128a4c5144cc547d0701feb21241cb4e70bb5cf56)

Here is an example setup, the output video is just the same frame over and over.
![image](https://user-images.githubusercontent.com/8334124/234899473-390bb12c-193c-4970-b1dc-cc5e171e1c41.png)

Stable Diffusion WebUI looks like this:
![image](https://user-images.githubusercontent.com/8334124/234899592-e6f31aec-6fe3-4497-8013-6f2f53169a5b.png)

**Comment by joeyballentine** [comment]
Known issue that will be fixed by #1762
