### ISSUE TITLE
cant find ncnn upscale node

### ISSUE THREAD

**Issue by makc** [chaiNNer-org/chaiNNer#1772]
I have just installed win build today and then installed all the packages in dependencies window, but no ncnn upscale node. why could that be?

**Comment by joeyballentine** [comment]
does your gpu support vulkan?

**Comment by jamboska** [comment]
i have 6500xt (it support vulcan) but i can't see upscale node too.

**Comment by joeyballentine** [comment]
Can you both send me your main.log file? (Help > open logs folder)

**Comment by makc** [comment]
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11367110/main.log)

**Comment by joeyballentine** [comment]
@makc that's definitely your problem then. NCNN needs a Vulkan compatible GPU to work

**Comment by makc** [comment]
@joeyballentine right, but the node being there and giving an explicit error when attempted to be used sounds better than just missing with no explanation 🤷

**Comment by SolitudeSF** [comment]
after some update NCNN upscale node disappeared for me. i still have load/save/get scale nodes. Linux v0.18.8. with integrated python.

**Comment by RunDevelopment** [comment]
@SolitudeSF Could you send use your logs? In the menu, go to Help > Open Logs folder, and there you should find `main.log`.

**Comment by SolitudeSF** [comment]
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11568686/main.log)

**Comment by RunDevelopment** [comment]
Thanks for the logs. Here's the issue: `ModuleNotFoundError("No module named 'typing_extensions'")`. This means that we forgot to pull one of our dependencies for NCNN. I opened an issue for that (#1835).

In the meantime, installing ONNX (or PyTorch) in chaiNNer's dependency manager should fix the issue.
