### ISSUE TITLE
cannot open .exr files (fix included)

### ISSUE THREAD

**Issue by nxtdaydelivery** [chaiNNer-org/chaiNNer#1775]
**Information:**

- Chainner version: 0.18.5
- OS: Windows 11 Pro (Ryzen 5 3600X, RTX 3070)

**Description**
hi. so I recently tried to open a .exr file into this, but it failed. After inspecting the logs, I found it is because the OPENCV_IO_ENABLE_OPENEXR environment variable is not set to 1, and the codec requries it:
```[2023-05-03 16:42:47.095] [info]  Backend: [35080] [ERROR] Error reading image image from path "C:\Users\null\Saved Games\The Last of Us Part I\screenshots\shot.exr". Image may be corrupt.
Traceback (most recent call last):
  File "C:\Users\null\AppData\Local\chainner\app-0.18.5\resources\src\nodes\nodes\image\load_image.py", line 49, in _read_cv
    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\grfmt_exr.cpp:103: error: (-213:The function/feature is not implemented) imgcodecs: OpenEXR codec is disabled. You can enable it via 'OPENCV_IO_ENABLE_OPENEXR' option. Refer for details and cautions here: https://github.com/opencv/opencv/issues/21326 in function 'cv::initOpenEXR'
```

This can easily be fixed by either creating an environment variable (as I did) or by using something like `os.environ["OPENCV_IO_ENABLE_OPENEXR"]="1"`. I would PR this but I don't really have time, sorry lol

On a separate note, the .exr file I opened is in 64-bit depth (HDR) and additionally any 64-bit .png file for example appears very washed out, from what I assume to be bit conversion to 8 bit channels. Is there going to be any HDR support? if not, could there be some node to rectify the washing out associated with it?

thanks, and by the way I love chainner - great stuff guys!

**Comment by RunDevelopment** [comment]
Thank you for the report @nxtdaydelivery!

We are aware of the issue and the fix (see #1628). Unfortunately, EXR support in OpenCV is disabled by default for a very good reason. The library OpenCV uses to read .exr files has several known security vulnerabilities, so we cannot enable this feature flag without compromising the security of our users.

That being said, we have looked into making our own bindings for EXR libraries. Unfortunately, [the most likely candidate](https://github.com/johannesvollmer/exrs) doesn't support DWAA/DWAB compression ([yet](https://github.com/johannesvollmer/exrs/issues/197)). So it will probably take a little while until we can bring good EXR support to chaiNNer.

---

I'm closing this as a duplicate of #1628.
