### ISSUE TITLE
Fix Linux and Mac portable builds

### ISSUE THREAD

**Issue by joeyballentine** [chaiNNer-org/chaiNNer#1778]
This is something I noticed when a user sent a screenshot of their linux portable zip. The portable file I insert into the zip needs to be one directory further in, because for some strange reason its different than the windows one. Just posting this here so I don't forget

**Comment by RunDevelopment** [comment]
@joeyballentine Does this work now?

**Comment by joeyballentine** [comment]
It should, but i haven't gotten confirmation

**Comment by joeyballentine** [comment]
Still haven't gotten confirmation but also nobody has complained so I'm fine with closing this
