### ISSUE TITLE
Model File Iterator for .pth files

### ISSUE THREAD

**Issue by Selur** [chaiNNer-org/chaiNNer#1780]
**Motivation**
While converting a large number of files from .pth to .onnx it would be nice to be able to batch the process.

**Description**
Would be nice if analog to the 'Model File Iterator' for .onnx models, one for .pth models would exist, too.

**Comment by RunDevelopment** [comment]
You're in luck, chainner already has this. The nodes are called "Load Model (Iterator)" and we have them for PyTorch, NCNN, and ONNX.

**Comment by Selur** [comment]
Thanks! Totally overlooked it. 👍
