### ISSUE TITLE
Request: Option to Resize the upscaled image if the Width or Height are bigger than 8192.

### ISSUE THREAD

**Issue by DDarknessOne** [chaiNNer-org/chaiNNer#1783]

**Comment by joeyballentine** [comment]
While chaiNNer does not currently have branching, it does have the _Resize to Side_ node, which can do what you describe. I believe these settings would accomplish what you're looking for: 
![image](https://user-images.githubusercontent.com/34788790/236633623-f4fe053b-ae3e-4646-8f5d-374029e83541.png)
