### ISSUE TITLE
Resize to size but keep aspect ratio?

### ISSUE THREAD

**Issue by Eagle1337** [chaiNNer-org/chaiNNer#1784]
**Motivation**
If you do resize to side, especially when you're targeting a rough minimum resolution size you can end up with some slightly stretched images.

**Description**
So if you were to say resize to height to 1500px, it'll go to the closest possible without stretching the image.

**Alternatives**
I've mostly just done it with batches and done the math manually but it becomes a royal pain when there's multiple different image scales that you're working with.

**Comment by RunDevelopment** [comment]
Resize to side is supposed to keep the aspect ratio of the input image. Could you please show an example chain where the image is stretched?

**Comment by RunDevelopment** [comment]
Closed due to inactivity.
