### ISSUE TITLE
Can't download PyTorch (Win-0.18.7)

### ISSUE THREAD

**Issue by checon56** [chaiNNer-org/chaiNNer#1796]
Any version of the app get stuck while downloading PyTorch. Download stucks generally at 85%. Issue probably not easy to reproduce since I could download and install on another pc but with this one it just doesn't work.
![image](https://github.com/chaiNNer-org/chaiNNer/assets/83084160/31fedb95-c302-4135-90e6-5ab6a52bf85e)
_Stuck at 85%_

There's a  option to use PIP Directly. After some time it gives this error "Pip process exited with non-zero exit code 2"
![image](https://github.com/chaiNNer-org/chaiNNer/assets/83084160/84001422-95b9-476e-944c-c6f1ae03f9a9)
_Error message when trying to use Pip Directly_

**Comment by checon56** [comment]
> https://github.com/chaiNNer-org/chaiNNer/blob/main/troubleshooting.md#pytorch-is-failing-to-install-from-the-dependency-manager

this doesn't work

**Comment by joeyballentine** [comment]
Are you using a VPN?

**Comment by checon56** [comment]
> Are you using a VPN?

No.

**Comment by joeyballentine** [comment]
In what way is the command from the link you sent not working? Is it giving you a specific error? You might need to replace %appdata% part with an absolute path to your appdata/roaming folder

**Comment by checon56** [comment]
> In what way is the command from the link you sent not working? Is it giving you a specific error? You might need to replace %appdata% part with an absolute path to your appdata/roaming folder

I've downloaded the portable version so there's nothing in appdata. I've changed with the absolut path at the portable location and it was giving sintax error because I didn't put the double quotes `"path"` just the single quotes `'path'` like powershell (stupid mistake of mine). And the command ran, but gave the error.

I've installed PyTorch locally and installed without errors but with the command provided in the link gives this error:

> C:\Users\ADM>"D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\python.exe" -m pip install torch==1.10.2+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
> Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
> Collecting torch==1.10.2+cu113
>   Downloading https://download.pytorch.org/whl/cu113/torch-1.10.2%2Bcu113-cp39-cp39-win_amd64.whl (2442.3 MB)
>      |████████████████████████████    | 2140.7 MB 6.4 MB/s eta 0:00:48ERROR: Exception:
> Traceback (most recent call last):
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
>     yield
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
>     data = self._fp.read(amt) if not fp_closed else b""
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
>     data = self.__fp.read(amt)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\http\client.py", line 462, in read
>     n = self.readinto(b)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\http\client.py", line 506, in readinto
>     n = self.fp.readinto(b)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\socket.py", line 704, in readinto
>     return self._sock.recv_into(b)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\ssl.py", line 1241, in recv_into
>     return self.read(nbytes, buffer)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\ssl.py", line 1099, in read
>     return self._sslobj.read(len, buffer)
> socket.timeout: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
>     status = self.run(options, args)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
>     return func(self, options, args)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
>     requirement_set = resolver.resolve(
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
>     result = self._result = resolver.resolve(
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
>     state = resolution.resolve(requirements, max_rounds=max_rounds)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
>     self._add_to_criteria(self.state.criteria, r, parent=None)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
>     if not criterion.candidates:
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
>     return bool(self._sequence)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 140, in __bool__
>     return any(self)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 128, in <genexpr>
>     return (c for c in iterator if id(c) not in self._incompatible_ids)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 32, in _iter_built
>     candidate = func()
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 204, in _make_candidate_from_link
>     self._link_candidate_cache[link] = LinkCandidate(
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 295, in __init__
>     super().__init__(
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
>     self.dist = self._prepare()
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 227, in _prepare
>     dist = self._prepare_distribution()
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 305, in _prepare_distribution
>     return self._factory.preparer.prepare_linked_requirement(
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
>     return self._prepare_linked_requirement(req, parallel_builds)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\operations\prepare.py", line 550, in _prepare_linked_requirement
>     local_file = unpack_url(
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\operations\prepare.py", line 239, in unpack_url
>     file = get_http_url(
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\operations\prepare.py", line 102, in get_http_url
>     from_path, content_type = download(link, temp_dir.path)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\network\download.py", line 145, in __call__
>     for chunk in chunks:
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\cli\progress_bars.py", line 144, in iter
>     for x in it:
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
>     for chunk in response.raw.stream(
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
>     data = self.read(amt=amt, decode_content=decode_content)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
>     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\contextlib.py", line 137, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
>     raise ReadTimeoutError(self._pool, None, "Read timed out.")
> pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Read timed out.
> WARNING: You are using pip version 21.2.4; however, version 23.1.2 is available.
> You should consider upgrading via the 'D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\python\python\python.exe -m pip install --upgrade pip' command.

Don't know what that means yet

**Comment by joeyballentine** [comment]
Its timing out, so that means something with your connection to the pip servers is closing before it finishes. So, something is going on on your side that is killing the connection early. If it installs fine to your system python, consider switching on the "use system python" setting, which will use your systems python instead of chaiNNers

**Comment by checon56** [comment]
> Its timing out, so that means something with your connection to the pip servers is closing before it finishes. So, something is going on on your side that is killing the connection early. If it installs fine to your system python, consider switching on the "use system python" setting, which will use your systems python instead of chaiNNers

![image](https://github.com/chaiNNer-org/chaiNNer/assets/83084160/eff663da-70a2-4bc7-8b28-c23aec6cd099)

Switching to use system python breaks chaiNNer. Last lines from log read as follow

>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\resources\src\run.py", line 82, in <module>
>     api.registry.load_nodes(__file__)
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\resources\src\api.py", line 237, in load_nodes
>     importlib.import_module(module, package=None)
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "D:\Portable Programs\chaiNNer-windows-x64-0.18.7-portable\resources\src\packages\chaiNNer_pytorch\pytorch\io\load_model.py", line 6, in <module>
>     import torch
>   File "C:\Users\ADM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\__init__.py", line 133, in <module>
>     raise err
> OSError: [WinError 126] N�o foi poss�vel encontrar o m�dulo especificado (translates to: it was not possible to find the specified module). Error loading "C:\Users\ADM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.

The file actually exist so I don't know why it says that

**Comment by joeyballentine** [comment]
More and more I'm just starting to hate python.... 

So, in your /settings folder delete the use-system-python file to revert that setting.

Torch is just failing to load a .DLL file it needs. At this point I'm not sure what else to do besides manually download the .whl file and installing it locally.

If you download this: https://download.pytorch.org/whl/cu113/torch-1.10.2%2Bcu113-cp39-cp39-win_amd64.whl

Then you can run that earlier command, but substitute torch with the path of the .whl file. 

Sorry that this is so complicated. These are the worst because afaik there's nothing i can do to improve this, it just breaks for some people

**Comment by checon56** [comment]
> More and more I'm just starting to hate python....
> 
> So, in your /settings folder delete the use-system-python file to revert that setting.
> 
> Torch is just failing to load a .DLL file it needs. At this point I'm not sure what else to do besides manually download the .whl file and installing it locally.
> 
> If you download this: https://download.pytorch.org/whl/cu113/torch-1.10.2%2Bcu113-cp39-cp39-win_amd64.whl
> 
> Then you can run that earlier command, but substitute torch with the path of the .whl file.
> 
> Sorry that this is so complicated. These are the worst because afaik there's nothing i can do to improve this, it just breaks for some people

No problem. Thank you for all the help. This apps is awesome as I've used in my workplace pc. I'll try to solve with and will come back with a solution. Again, thank you

**Comment by checon56** [comment]
Got it! @joeyballentine 

Detailed steps below for newbie users:

- Manually download PyTorch.whl from https://download.pytorch.org/whl/cu113/torch-1.10.2%2Bcu113-cp39-cp39-win_amd64.whl
- Open CMD and run command below (if you're using the portable, replace %appdata% with the path where you put chaiNNer. If your path has spaces, it must be enclosed by double quotes)
- `%appdata%\chaiNNer\python\python\python.exe -m pip install REPLACE-WITH-PATH-TO-THE-FILE-YOUVE-DOWNLOADED`
- tip: you can copy the first half and drag and drop the file to the CMD window and the path will be pasted automatically. Alternatively you use `shift + ctrl + c`  to copy the entire path of the file and paste into cmd.
- Let it run and wait for message sucess
- open chaiNNer and download the final dependency (about 3mb will be downloaded)
- Done! Thanks to joeyballentine

**Comment by gvidas123** [comment]
just for reference you will have to find the correct download for your current python for chainner it is at Python 3.11 so you would need to download cp311 cp311
