### ISSUE TITLE
How to add custom header key in @react-nano/useEventSource? 

### ISSUE THREAD

**Issue by hylerrix** [chaiNNer-org/chaiNNer#1798]
**Motivation**
Hi, I'm trying to use [chaiNNer](https://github.com/chaiNNer-org/chaiNNer/tree/main) to build a workflow app, which uses react-nano to make the EventSource API call.

Now I want to add a custom header in the API call, how can I do it?

**Description**
I know the [EventSource API - MDN Page](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) doesn't support a way of injecting the header key, but I also found [event-source-polyfill](https://www.npmjs.com/package/event-source-polyfill) can do it by another way.

I'm not so good to merge the event-source-polyfill header injection function into @react-nano/use-event-source.

Can this repo support header key injection more than the official EventSource API?

Related code in chaiNNer:

```
export const useBackendEventSource = (
    port: number
): readonly [BackendEventSource | null, EventSourceStatus] => {
    return useEventSource(`http://localhost:${port}/sse`, true);
};
```

Which I wish:

```
export const useBackendEventSource = (
    port: number
): readonly [BackendEventSource | null, EventSourceStatus] => {
    return useEventSource(`http://localhost:${port}/sse`, true, { header: { AAA: 1 } });
};
```

See Also: https://github.com/Lusito/react-nano/issues/1

**Comment by RunDevelopment** [comment]
Alright, so firstly: this is a weird issue. The communication between frontend and backend is currently a pure implementation detail, so we do not make any guarantees, nor will we add guarantees in the future to better support projects that use chainner in unintended ways. Maybe I'm misunderstanding your issue, but it seems to me like you are repurposing chainner as the basis for another project.

Anyway, here's how I would add custom headers: [`useEventSource` supports providing a custom event source class](https://github.com/Lusito/react-nano/blob/3efa0ac8503688c2796a19504e07dd57eef2da18/packages/use-event-source/src/index.ts#LL9C1-L9C1). This means that we have fully control over the internal event source by providing this class. So assuming that your `EventSourcePolyfill` implements the [`EventSourceConstructor` interface](https://github.com/Lusito/react-nano/blob/3efa0ac8503688c2796a19504e07dd57eef2da18/packages/use-event-source/src/index.ts#L3), we can make a function that creates a dynamic class based on headers:
```ts
// (I'm not sure whether the return type of this function is correct.)
function createESClassWithHeader(header: Record<string, string>): typeof EventSourcePolyfill {
  return class ESClass extends EventSourcePolyfill {
    constructor(url: URL | string, options?: EventSourceOptions) {
      // TODO: options could be a boolean, so convert to object first
      super(url, { ...options, headers });
    }
  };
}
```

And use it like this:

```ts
const ESClass = useMemo(() => createESClassWithHeader(headers), [headers]);
useEventSource(url, true, ESClass);
```

**Comment by joeyballentine** [comment]
If you are repurposing chaiNNer for another project, don't forget that it is [GPLv3 licensed](https://github.com/chaiNNer-org/chaiNNer/blob/main/LICENSE), meaning you are required to make your code open source and GPLv3 licensed as well.

**Comment by RunDevelopment** [comment]
> Just one question: how could options be a boolean?

Oh, my bad. You're right. I was under the impression that options could either be a bool or an object, but that's not the case.

**Comment by Lusito** [comment]
Another thing to keep in mind: If `headers` in your example is not memoized as well, your useMemo will be completely useless.

**Comment by Lusito** [comment]
I've posted a detailed comment over at my repository: https://github.com/Lusito/react-nano/issues/1#issuecomment-1548563260

Hope this helps.

**Comment by hylerrix** [comment]
## PR

Thanks to @RunDevelopment and @Lusito 's help. Now I resolved this by creating a `createESClassWithHeaders ` function with so ease.

And made a pull request (https://github.com/Lusito/react-nano/pull/2) to [@react-nano/use-event-source](https://www.npmjs.com/package/@hyler-coop/use-event-source). Feel free to merge or not.

## License

> If you are repurposing chaiNNer for another project, don't forget that it is [GPLv3 licensed](https://github.com/chaiNNer-org/chaiNNer/blob/main/LICENSE), meaning you are required to make your code open source and GPLv3 licensed as well.

Thanks to @joeyballentine's reminder, we're in the experimental development stages, trying to use chaiNNer to build a cybersecurity test and Security R&D collaboration app for the Vehicles Industry now. And would like to open-source it when we're finally ready.

## Why I need this function

Here is a simple reason why we want to deliver a custom header key in EventStream API:

* When a user opens the same chaiNNer project multiple times, the backend needs to know a `Page ID` generated by the frontend browser and return the right answer to each page. Leave the page or refresh the page and the ID change.
* Cookie is not a good solution in this situation. Not only because it should be generated from the backend server, but also because we do not need these headers in every request, etc.

So we decide to deliver a custom header key in these requests which are in needed.

**Comment by joeyballentine** [comment]
> trying to use chaiNNer to build a cybersecurity test and Security R&D collaboration app for the Vehicles Industry now

chaiNNer has tons of very specific things related to image processing that I'm assuming you're ripping out, plus we have a lot of really bad code -- is there a reason you aren't just starting from scratch using react-flow? What about chaiNNer is worth turning it into something so vastly different?

**Comment by Lusito** [comment]
> Here is a simple reason why we want to deliver a custom header key in EventStream API:
> 
>     * When a user opens the same chaiNNer project multiple times, the backend needs to know a `Page ID` generated by the frontend browser and return the right answer to each page. Leave the page or refresh the page and the ID change.
> 
>     * Cookie is not a good solution in this situation. Not only because it should be generated from the backend server, but also because we do not need these headers in every request, etc.

So, if I get this correctly, you are not using the header for authentication, but to pass a value (the page id)? Why not pass it via path or via get parameters instead?

**Comment by hylerrix** [comment]
> So, if I get this correctly, you are not using the header for authentication, but to pass a value (the page id)? Why not pass it via path or via get parameters instead?

Yes, I'll try to use get parameters only in `/sse` request now. Even if I have already implemented the header injection by using EventSourcePolyfill. But considering the risk of using EventSourcePolyfill, I'm not continuing to use EventSourcePolyfill anymore.

Let me close this issue and thanks for all your comment and sharing!
