### ISSUE TITLE
Noise removal node

### ISSUE THREAD

**Issue by tomexx** [chaiNNer-org/chaiNNer#1807]
A node to remove noise (maybe using AI/ML too) would be great

**Comment by joeyballentine** [comment]
Noose removal specific networks have been suggested before and are planned to be added eventually, but FYI there are noise removal esrgan models that exist that work as-is

**Comment by tomexx** [comment]
> Noose removal specific networks have been suggested before and are planned to be added eventually, but FYI there are noise removal esrgan models that exist that work as-is

Thank you. But which node should I use. The upscale one?

**Comment by joeyballentine** [comment]
Yes. The Upscale Image node is really just a "run model" node that works with the specified architectures usually meant for SR. But these networks can be trained at 1x for things like noise removal.

**Comment by RunDevelopment** [comment]
Resolved by #1890
