### ISSUE TITLE
[FEATURE REQUEST] Please support FBCNN!

### ISSUE THREAD

**Issue by ghost** [chaiNNer-org/chaiNNer#1808]
JPEG Artifacts are very prevalent in today's modern society.

I want my JPEG artifacts crushed. This is very important. Please support [FBCNN](https://github.com/jiaxi-jiang/FBCNN)

**Comment by RunDevelopment** [comment]
In the meantime, there are a bunch of ESRGAN models that remove JPEG artifacts well. See https://openmodeldb.info/?t=jpeg+scale%3A1.

**Comment by RunDevelopment** [comment]
Implemented by https://github.com/chaiNNer-org/spandrel/pull/4.

This will be available in chainner soon.
