### ISSUE TITLE
Pixel Un_shuffle error

### ISSUE THREAD

**Issue by jeffreylm** [chaiNNer-org/chaiNNer#1810]
Here is the error I get when I try to convert Pytorch REAL-ESRGAN to NCNN. I use the official version. The conversion of the 4xPlus went perfectly well, but the 2xPlus gives this error.

To repeat this error simply convert the REAL_ESRGAN 2x Plus to NCNN with a save node.

Chainner 0.18.7
MAC os Monterey 12.6.5
Model from here: https://upscale.wiki/wiki/Official_Research_Models

Error

An error occurred in a PyTorch Convert To NCNN node:

Exporting the operator pixel_unshuffle to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

Input values (partial):
• Data Type: fp32

**Comment by joeyballentine** [comment]
This is because pixelunshuffle (used by the 2x variant of that model) is not supported by ONNX (the intermediary step between a pytorch model and an ncnn model). I don't think NCNN supports it either, so even if it could be converted to onnx it wouldn't be able to go to NCNN either. There isn't anything I can do about this.

**Comment by jeffreylm** [comment]
One thing I must mention. I noticed you said "ONNX", but it went from Pytorch Load --> Pytorch convert to NCNN --> NCNN Save Model

There was no ONNX node used, but yet there is a wording in the error referring to ONNX. Am I missing something?

**Comment by joeyballentine** [comment]
There is no directly converting from pytorch to NCNN. It goes through onnx first. The convert to NCNN node is just a shortcut to do pytorch -> onnx -> NCNN to make it a bit more convenient for users.

**Comment by jeffreylm** [comment]
OOh, ok. I was trying to get a 2x model of Real-ESRGAN to add it in the node tree. 
As I need to go from 1456x816 upscaled to --> 5824x3264 -->  11648x6,528 

By using a 2x model after the 4x model I can get there. Two 4x models behind each other will be to large. Is there another way?

**Comment by joeyballentine** [comment]
Downscale the first upscale by 50% and then do another 4x upscale

**Comment by jeffreylm** [comment]
And I take it I have to use the resize factor node. Am I correct?

**Comment by joeyballentine** [comment]
Yep!

**Comment by jeffreylm** [comment]
Joey, you have truly made an amazing piece of software, really. And to think this is still in alpha.

**Comment by joeyballentine** [comment]
Thanks :) it wasn't just me though, there have been lots of other contributors. Glad you like it!
