### ISSUE TITLE
allow manually setting opset version

### ISSUE THREAD

**Issue by hooke007** [chaiNNer-org/chaiNNer#1812]
**Motivation**
Currently it seems always use the fixed version of opset when converting pytorch models to onnx ones.
I once noticed some speed influence on different opset version of the same model.

**Description**
I wish I could set opset version explicitly.

**Alternatives**
N/a

**Comment by joeyballentine** [comment]
I think right now we're using the latest upset as supported by the pytorch version we use (opset 14, pytorch 1.10) Are you saying you get faster speeds using opset < 14? For later opsets we'll need to use a later version of pytorch, which i plan on doing once 2.1 comes out.

**Comment by hooke007** [comment]
> Are you saying you get faster speeds using opset < 14?

Not from this repo. I got faster speed with op14 than later one (15/16).

**Comment by joeyballentine** [comment]
chaiNNer uses opset 14

**Comment by hooke007** [comment]
I know. That's why I explained "Not from this repo"

**Comment by joeyballentine** [comment]
I'm just confused on why you want the ability to select the opset version here, when the opset we currently use is the fastest one?

**Comment by hooke007** [comment]
I mean, when you could support later versions, allow users to set previous one.

**Comment by joeyballentine** [comment]
Yes we can do that in the future
