### ISSUE TITLE
`--no-sandbox` Electron flag causes ChaiNNer to error

### ISSUE THREAD

**Issue by JeremyRand** [chaiNNer-org/chaiNNer#1818]
**Information:**

- Chainner version: v0.18.7
- OS: Debian Bullseye

**Description**

The `--no-sandbox` Electron flag is necessary on some platforms (e.g. ppc64le) where the Chromium sandbox is unavailable. Unfortunately, it seems that its presence confuses ChaiNNer.

**Steps to reproduce**

`./chainner --no-sandbox`

**Expected results**

ChaiNNer should launch the GUI as usual (Electron will disable the sandbox).

**Observed results**

`Unknown argument: sandbox`

**Logs**

Nothing is logged when ChaiNNer is launched in this way.

**Comment by joeyballentine** [comment]
This looks like something we'd need to manually add a argument for so we can handle it correctly. Thanks for bringing it to our attention.

**Comment by JeremyRand** [comment]
> Actually, after taking a look at the electron docs about sandboxing, it should already be disabled due to another setting we have enabled. Can you try running without that flag?

Hmm, is it disabled as part of the Electron binary or something in the app files? I get an Electron error about sandboxing being unsupported (with a suggestion to add the `--no-sandbox` flag) when running ChaiNNer on ppc64le using a distro-packaged Electron. (Obviously using ChaiNNer's bundled Electron binaries won't work on ppc64le.)

**Comment by joeyballentine** [comment]
Yeah i honestly have no idea what to do about this. We can try making it so we pass in any extra arbitrary arguments to the process but I'm not even sure it will fix this. As far as I'm aware we're already disabling sandboxing so if it's not working I'm not sure what to do about it. 

Also, i don't think chaiNNer would even work on PowerPC architecture. So many of our python dependencies are built for x64 only, or for arm64 and x64. Honestly I'm not sure I've ever even seen a PPC wheel file before. Are you generally able to install python dependencies outside of chaiNNer?

**Comment by joeyballentine** [comment]
> So I think if ChaiNNer just treats that flag as a no-op, it's likely to work.

In that case, it should be an easy fix. That just means it's out CLI mode arg parser throwing a fit about it. 

Glad to know it works without that. We'll try to get this resolved soon

**Comment by JeremyRand** [comment]
Great, thank you. If you want me to test a CI binary or something on my ppc64le system, I'm happy to do so, let me know.
