### ISSUE TITLE
Add `typing_extensions` to required dependencies

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#1835]
All upscaling nodes implicitly depend on `typing_extensions`, but we don't declare it as a dependency. PyTorch and ONNX probably just happen to transitively depend on it, and therefor include it.

This results in NCNN (without PyTorch and ONNX installed) not working. See here for the [full error log](https://github.com/chaiNNer-org/chaiNNer/issues/1772#issuecomment-1563426496).

**Comment by joeyballentine** [comment]
implemented by #1834
