### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by mkornish-accipiter** [chaiNNer-org/chaiNNer#1836]
**Information:**
- Chainner version: 0.18.9, but this issue also appeared in 0.18.8
- OS: Ubuntu 20.04.06 LTS running in a virtual machine
- Hardware: Intel Core i9, Nvidia Geforce RTX 3090 Ti, 40 gigs of RAM 
- Model used: [4x UltraSharp](https://mega.nz/folder/qZRBmaIY#nIG8KyWFcGNTuMX_XNbJ_g)

**Description**
Rather new chainner user, so I could be missing something here. 
Attempting to do some rather simple upscaling, the Chainner GUI shows an error and fails to run. Originally I was trying to daisy-chain three upscaling nodes together, but when that failed, I dropped it down to one. Still broke. 

The popup says "An unexpected error occured: TypeError: Failed to fetch." The terminal printout only displays one error message: "Python subprocess exited with code null and signal SIGILL'.

This issue appears both when I use the provided Python install and when I use the Python version that comes with Ubuntu by running `sudo apt install --upgrade python3 python3-pip`. I've tried looking through other issues presented here to no avail.

**Logs**
I tried wiping the log files to get more recent info, and these are from a single startup. Also attached is the chain file as a .txt rather than a .chn file.
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11576216/main.log)
[renderer.log](https://github.com/chaiNNer-org/chaiNNer/files/11576217/renderer.log)
[2ktest.txt](https://github.com/chaiNNer-org/chaiNNer/files/11576237/2ktest.txt)

**Comment by joeyballentine** [comment]
Unfortunately the logs don't give much information other than the backend is crashing without an error. Your system is more than enough to do this type of work so it's not that, it's gotta be a more technical thing. Are you able to use anything else that uses pytorch outside of chaiNNer? 

Also, what drivers do you have installed? IIRC Nvidia drivers are weird on Linux

**Comment by mkornish-accipiter** [comment]
There doesn't seem to be a problem with Torch, as running some demo code they have on their website does not cause me any issues even in CUDA mode.

You are correct about Nvidia drivers being weird on Linux. I am currently using 515.43.04, which Nvidia lists as "beta" on their website (despite being many versions behind Windows which is on 532). I will try running a production branch driver to see if that fixes it.

**Comment by mkornish-accipiter** [comment]
Update: The newest production branch Nvidia drivers for Linux that support the 3090 are 525.116.04. Installing those and re-attempting the test still fails with the same error.

**Comment by mkornish-accipiter** [comment]
It appears to be an intermittent issue with Pytorch. After restarting chaiNNer and rebuilding the chain to use NCNN, I was able to upscale a 512x512 image up to 32768x32768 (my original objective).
