### ISSUE TITLE
Q: Does 4x in 4x-UltraSharp refer to the area or the side (e.g. width/height) of the image?

### ISSUE THREAD

**Issue by off99555** [chaiNNer-org/chaiNNer#1850]
Just for clarification, is it upscaling image from 512x512 to 1024x1024 or 2048x2048?
It could be interpreted both ways depending on what 4x means:

1. if it refers to the side size e.g. width or height, then 4x increase in width and height then it should result in 2048x2048
2. if it refers to the area increase then 4x increase should result in 1024x1024
Which is it?

Thanks!

**Comment by joeyballentine** [comment]
The dimensions get multiplied by 4, so a 10x10 image becomes 40x40

**Comment by off99555** [comment]
Thanks. That's very helpful!
