### ISSUE TITLE
Add node to make 3 channel images into 1 channel?

### ISSUE THREAD

**Issue by hopelesscase** [chaiNNer-org/chaiNNer#1854]
**Motivation**
Specifically, I was hoping there could be a node to streamline the process to use with this model:
4x_eula_digimanga_bw_v2_nc1_307k

I looked online and all the results suggest python or opencv and to be perfectly honest… I have very basic knowledge of the first and none of the second.

If there's a way to do this and have it work with that model please tell me since I tried various things and only got errors. I assume it's because I didn't convert my RBG image properly.

**Description**
Load multi channel image(s) into a node → Add a 3 to 1 channel converter node → Add model → Process image → Save

**Alternatives**
Not sure about alternatives… I'd settle for a way to do it outside of chaiNNer, but I must be getting instructions mixed up since I barely know how to use python. It's not my forte...

**Comment by theflyingzamboni** [comment]
Use Change Colorspace.

**Comment by RunDevelopment** [comment]
@hopelesscase To elaborate a bit more: Change Colorspace can convert RGB images (3 channels) to Grayscale (1 channel). It does this by using the cvtColor function of OpenCV, so it most likely uses a weighted average of the RGB channels to derive the grayscale image.

If instead you want to select a single channels from an RGB image, use the Separate RGBA node.
