### ISSUE TITLE
There are no nodes that have an effect. Try to view or output images/files.

### ISSUE THREAD

**Issue by AImortisaisreda** [chaiNNer-org/chaiNNer#1870]
Everything is ok until I click on RUN, then that message appears?!
There are no nodes that have an effect. Try to view or output images/files.
HEEEEP!

**Comment by joeyballentine** [comment]
Can you send a screenshot of the chain you have set up? It sounds like you don't have any kind of view or save node at the end of it

**Comment by AImortisaisreda** [comment]
@ Thaaaaanks! You helped me! I forgot to add save image node :)
