### ISSUE TITLE
Error  when trying to upscale

### ISSUE THREAD

**Issue by ssebaa** [chaiNNer-org/chaiNNer#1871]
**Information:**

- Chainner version: [0.18.9]
- OS: [Windows 11]

**Description**
So I used 4xESRGAN.pth on 2k dds file to upscale into 8k dds file, last time I make it done with 2xESRGAN from 2k to 4k. I guess It's not possible to make it 8k from 2k base at least for now

**Logs**
Attached.

[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/11779580/logs.zip)

**Comment by ssebaa** [comment]
I'm getting: Error

An unexpected error occurred: TypeError: Failed to fetch

**Comment by joeyballentine** [comment]
What GPU do you have? It looks like the backend is crashing when you try to upscale, which may be due too too much ram usage if it's upscaling on CPU, but I'd need to know what your GPU is and whether you were using pytorch, ncnn, or onnx.

**Comment by ssebaa** [comment]
Radeon rx 6600XT which have no cuda so using pytorch on my ryzen 7 7800x3d to upscale that much is simply to much am I right? So I should use NCNN or ONNX I saw one of them is supporting my gpu but the question I have now is that is it affecting the quality?

**Comment by joeyballentine** [comment]
You should use NCNN as that will use your GPU. It doesn't affect the quality at all. You can even convert the model you were using on pytorch to NCNN entirely in chaiNNer. The output will be the same and it'll go much faster

**Comment by ssebaa** [comment]
Thank you for an explanation :D
