### ISSUE TITLE
Check that base directory exists before running a chain

### ISSUE THREAD

**Issue by GryllsAddons** [chaiNNer-org/chaiNNer#1904]
- Chainner version: 0.18.9
- OS: Windows 11

Description:
Currently Chainner does not check if the base directory for saving exists before running the chain. It would useful to check before the processing starts as if you have moved or deleted the directory before running an iterator, each instance will be processed without presenting an error. At the end of the process multiple error lines will be displayed in the error output as the directory does not exist.

Logs:
[main.zip](https://github.com/chaiNNer-org/chaiNNer/files/11929966/main.zip)

**Comment by RunDevelopment** [comment]
Could you please share the chain in question? I can reasonably guess that you used a Save Image node inside an iterator, but that would produce this kind of error, so I have no idea what your problem is.

**Comment by joeyballentine** [comment]
I think the issue they're running into is that the iterator hides the errors until it's done.

There's two ways we can resolve this:

1. Make the directory if it doesn't exist 
2. (Already planned) add a checkbox for whether or not the iterator hides errors until the end or not

**Comment by RunDevelopment** [comment]
I don't get *why* they get an error in the first place. Save Image should just create any necessary directory instead of erroring.

**Comment by GryllsAddons** [comment]
From further testing it looks like this problem occurs when using the image pairs iterator node. In the example chain below the "Test" directory within save image does not exist. The chain will run but the directory is not created. Once all items are processed the error screen is displayed.

![chaiNNer-test-2023-7-3_00-03](https://github.com/chaiNNer-org/chaiNNer/assets/107083057/88a589ed-1aa6-4bdc-b0ab-867fc3867017)

![image](https://github.com/chaiNNer-org/chaiNNer/assets/107083057/f5b2cd56-b023-453f-9dfd-5d2927739c0f)

**Comment by RunDevelopment** [comment]
Thanks for the additional info @GryllsAddons!

I looked more closely at the code, and we indeed currently require that Save Image's Base Directory exists. Sorry about that.

@joeyballentine Is this intended/useful behavior? Since the Save Image node will create subdirectories just fine, I would expect that it creates the base directory as well (if not present).

**Comment by joeyballentine** [comment]
I think that was just an oversight, so yes this is a bug
