### ISSUE TITLE
Error Failed to Fetch After Install pytorch 2GB

### ISSUE THREAD

**Issue by SorrHash** [chaiNNer-org/chaiNNer#1922]
my problem is weird some kind.
in begin ChaiNNer is worked perfectly but after install pytorch (2gb) the problem was show. when i deleted folder torch in
C:\Users\User name\AppData\Roaming\chaiNNer\python\python\Lib\site-packages
it's will be work again.
![1](https://github.com/chaiNNer-org/chaiNNer/assets/114016987/ad7b602b-3f96-4a7f-9fe5-d8d9db5f7426)
![2](https://github.com/chaiNNer-org/chaiNNer/assets/114016987/05a0069a-16b8-44e1-917f-94e712cc044e)

**Comment by joeyballentine** [comment]
Can you open your logs folder (help > open logs folder, or just go to roaming/chaiNNer/logs) and send your main.log file here? 

It looks like pytorch failed to actually install.

**Comment by SorrHash** [comment]
it's fix.
i just download the portable version and install pytorch
and it's work without any problems. why and how IDK
![3](https://github.com/chaiNNer-org/chaiNNer/assets/114016987/5496efdc-d21e-41a4-bfdb-b9d1ccbd7562)
![4](https://github.com/chaiNNer-org/chaiNNer/assets/114016987/1c21e3f5-88ef-4767-9140-f9f58533f420)
anyway if you want the logs of the installer version (which has that problem),that is it
[main.old.log](https://github.com/chaiNNer-org/chaiNNer/files/11974905/main.old.log)
[renderer.log](https://github.com/chaiNNer-org/chaiNNer/files/11974906/renderer.log)
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11974907/main.log)
 and Thank you for reply.

**Comment by joeyballentine** [comment]
Ah, you encountered the DLL loading error that happens on occasion to people.

I still have no idea what causes that, but basically it makes pytorch fail to import and then causes problems

**Comment by RunDevelopment** [comment]
This probably isn't an issue anymore. If it is, manually run pip commands from the dependency manager.
