### ISSUE TITLE
16 Bits per color support.

### ISSUE THREAD

**Issue by maxpiva** [chaiNNer-org/chaiNNer#1934]
**Motivation**
Currently, saving images only support saving 8 bits per color (24+alpha). 
Png & Tiff supports loading and saving (48+alpha) bit images. 
The current 8-bit per color causes issues mostly on gradients in anime, sawed colors.

**Description**
16-bit per color (R, G, B) support, in loading (not sure) and saving images, and the conversion from/to fp formats.

**Comment by 0x4E69676874466F78** [comment]
Related: #819

**Comment by RunDevelopment** [comment]
> The current 8-bit per color causes issues mostly on gradients in anime, sawed colors.

Are you sure this is caused by the 8-bit quantization? If so, then we should probably add an option to enable dithering to Save Image. I added general support for dithering a while back, but we haven't exposed that option yet.

**Comment by maxpiva** [comment]
Yes, is the 8-bit quantization. 
If making the pipe 16-bit is not feasible, dither is the second best. The only tool that was able to do the full 16-bit pipe, is waifu2x-Caffe with custom models. Gradients come out perfect. The other is, the node may or may not support 16 bits. If there are OpenCV limitations in some operations.

IE:
10-Bit Anime -> 16 Bit PNG -> waifu2x-Caffe -> 16 Bit PNG -> 10-Bit Anime.
