### ISSUE TITLE
Upscale face agressive seam

### ISSUE THREAD

**Issue by Loacoon1** [chaiNNer-org/chaiNNer#1949]
**Information:**

- Chainner version: 0.18.9
- OS: Manjaro Linux

**Description**
When upscaling face using any model, there is a clear seam where the upscaler stops, especially on the hair. It should either exclude the hair completely, or include them all (preferable but probably much harder). Right now the outputs are most of the time unsusable.

**Comment by joeyballentine** [comment]
This is an issue with the facexlib library and not something I can fix in chaiNNer (I've tried before with no luck). Please open an issue there instead: https://github.com/xinntao/facexlib
