### ISSUE TITLE
Threshold node with common thresholding algorithms

### ISSUE THREAD

**Issue by ad-si** [chaiNNer-org/chaiNNer#1955]
**Motivation**
Converting images to binary images with good auto generated threshold value.

**Description**
LIke the exisiting threshold node, but instead of picking a threshold value you pick an algorithm (e.g. following ones: https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_thresholding.html)

**Comment by RunDevelopment** [comment]
I think we should add a "Generate Threshold" (or similar) node instead. This would simply return the automatically determined threshold value, and you can then pass this value into the Threshold node. The generated threshold values could be useful for other things too.

Reference: https://en.wikipedia.org/wiki/Otsu's_method
