### ISSUE TITLE
Error report: Object has been destroyed

### ISSUE THREAD

**Issue by wilfwilson-art** [chaiNNer-org/chaiNNer#1998]
```
UnhandledRejection TypeError: Object has been destroyed

    at click (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:503740)
    at MenuItem.click (node:electron/js2c/browser_init:2:30166)
    at a._executeCommand (node:electron/js2c/browser_init:2:35562)
```
ChaiNNer: chaiNNer 0.18.9
OS: macOS 10.18

**Comment by joeyballentine** [comment]
Sorry, MacOS 10 is no longer supported.

**Comment by wilfwilson-art** [comment]
I’m running OS 13.5 Ventura. MacBook Pro 16-inch, 2021, Apple M1 Max, 64GB RAM 

￼

**Comment by wilfwilson-art** [comment]
<img width="392" alt="Screenshot 2023-07-27 at 6 14 51 PM" src="https://github.com/chaiNNer-org/chaiNNer/assets/133134986/a6682618-ca4f-4da6-8663-a54244901fb9">

**Comment by joeyballentine** [comment]
Your OS in the original message is indicated as being macOS 10.18, so sorry for that. Unfortunately this error is pretty vague and we don't know what causes it.

This is however a duplicate of #1752

**Comment by joeyballentine** [comment]
Is there something in particular you were doing when this happened?
