### ISSUE TITLE
Image upscale. So slooooooooow.  

### ISSUE THREAD

**Issue by wilfwilson-art** [chaiNNer-org/chaiNNer#2000]
I’m running OS 13.5 Ventura. MacBook Pro 16-inch, 2021, Apple M1 Max, 64GB RAM but Chainner has been going for over 3 hours without producing a single one of the 2 files in the specified folder. The Dock icon suggests its about a 3rd of the way through but after so long I'm beginning to doubt that it's actually doing anything at all. I had such great hopes for this level of automated image manipulation. Am I being too ambitious? Any suggestions?
<img width="1728" alt="Screenshot 2023-07-27 at 11 45 08 PM" src="https://github.com/chaiNNer-org/chaiNNer/assets/133134986/3862982e-da4f-4f3b-925a-5c7df41c7dbd">

**Comment by joeyballentine** [comment]
You should be using NCNN as you are on a Mac. If you do this I suggest using a small tile size to avoid any crashes. You also could take advantage of the apple MPS processing in pytorch but for that you'd need to switch to using system python and install pytoech 2.0 manually as the version installed by the dependency manager is pretty old.

**Comment by wilfwilson-art** [comment]
Many thanks for such a quick reply. Do I need to download pram and bin files like the ESGRAN files for PyTorch?

**Comment by joeyballentine** [comment]
You can convert any ESRGAN model to NCNN just through chaiNNer

**Comment by wilfwilson-art** [comment]
Hi again,

I’m now in over my head. I have been unable to install the ONNX dependency. is this an Apple Silicon issue?
Apologies for being such a newbie
￼
￼

**Comment by wilfwilson-art** [comment]
PastedGraphic-2.png
PastedGraphic-3.png

**Comment by wilfwilson-art** [comment]
<img width="1280" alt="PastedGraphic-2" src="https://github.com/chaiNNer-org/chaiNNer/assets/133134986/994f3d7c-5566-4ead-88ea-cc8cfd07da62">
![Uploading PastedGraphic-3.png…]()

**Comment by wilfwilson-art** [comment]
<img width="1280" alt="PastedGraphic-3" src="https://github.com/chaiNNer-org/chaiNNer/assets/133134986/7d8b04cd-bdeb-4176-9d5c-79a968a4b56d">

**Comment by joeyballentine** [comment]
What does it say if you click the view console button? Onnxruntime-silicon is supposed to work...

**Comment by joeyballentine** [comment]
Well regardless, it installed the regular onnx dependency fine. If you restart chaiNNer it should be able to convert to ncnn

**Comment by wilfwilson-art** [comment]
> What does it say if you click the view console button? Onnxruntime-silicon is supposed to work...

![Uploading Screenshot 2023-07-28 at 6.17.08 PM.png…]()

**Comment by wilfwilson-art** [comment]
The console doesn't let me copy the texts

**Comment by wilfwilson-art** [comment]
> Well regardless, it installed the regular onnx dependency fine. If you restart chaiNNer it should be able to convert to ncnn

I still get the exact same error

**Comment by wilfwilson-art** [comment]
<img width="1504" alt="Screenshot 2023-07-28 at 6 17 08 PM" src="https://github.com/chaiNNer-org/chaiNNer/assets/133134986/bc89667f-3d4b-418f-be5b-5e81c3de9fc3">

**Comment by joeyballentine** [comment]
That's super weird, because 1) [onnxruntime-silicon==1.13.1 definitely.exists](https://pypi.org/project/onnxruntime-silicon/1.13.1), and 2) i don't think it would need the runtime in order to convert. I'll double check the code though.

Regardless, you're currently using system python. You can try installing a later version of onnxruntime or onnxruntime-silicon via a normal terminal and that should fix it, or you can try installing pytorch 2.0 the same way and take advantage of MPS via pytorch instead of trying to use NCNN

**Comment by joeyballentine** [comment]
@wilfwilson-art is your system python arm64 or is it x86? I think it might be x86 and that's why it's not finding the version

**Comment by wilfwilson-art** [comment]
Hi Joey,

Many thanks for your ongoing support, I’m afraid I wouldn’t know how to tell you what my system python is. I’m not the kind of guy who normally looks under the hood.

I have sorted out the problem by taking your suggestion to instal pytorch 2.0. This took me down a rabbit hole of stuff way, way, way beyond my ken. To be honest I’ve just blindly followed a process I cobbled together from various websites on pytorch, homebrew, miniforge and other arcane stuff. After a long time of fearfully watching Terminal do things I had no idea it could do (while I became increasingly worried that my poor machine would turn into an incredibly expensive thin, rectangular metal placemat) and without knowing whether I was having any success at all, Chainner suddenly downloaded Onnex. The converter worked and now it all works so well with NCNN it takes my breath away! I can double upscale, add a white border, append text to name and also make a small thumbnail of an image in 5 mins/image. Impressive. 

A bit of an emotional rollercoaster but I’m where I need to be (I hope). Although I seem to have lost my flashing place marker when I type.
System report for you below if this is of any help.

 Model Name:	MacBook Pro
 Model Identifier:	MacBookPro18,2
 Model Number:	Z14X0007YB/A
 Chip:	Apple M1 Max
 Total Number of Cores:	10 (8 performance and 2 efficiency)
 Memory:	64 GB
 System Firmware Version:	8422.141.2
 OS Loader Version:	8422.141.2
 Serial Number (system):	******H22Q
 Hardware UUID:	XXXX
 Provisioning UDID:	XXXX
 Activation Lock Status:	Enabled

I’ve really appreciated your concern and involement so please feel free to reach to ask any questions if you feel you need to address specific issues.

Kind regards,

Wilf

**Comment by joeyballentine** [comment]
Glad it ended up working out for you! Let me know if you run into any other issues
