### ISSUE TITLE
Native Apple Silicon support for the main app

### ISSUE THREAD

**Issue by stonerl** [chaiNNer-org/chaiNNer#2014]
### Information:

- Chainner version: [[main 4a6c99e](https://github.com/chaiNNer-org/chaiNNer/commit/4a6c99e819b47a40522e414e8bf26359a18f3b47)]
- OS: [macOS 13.5]

### Description
Currently, the main App is built for x86 Macs, although all necessary libraries are shipped/installed have native arm64 counterparts. So I built the latest HEAD on my M2 to test it.

#### 1. The build part:

The app builds, but creating the DMG fails. (See the build log)

#### 2. Starting the app.

The app itself starts but shows a brief error message that swiftly disappears.

#### 3. Installing dependencies.

Installing the dependencies seems to work, but when installing them, an error message appears:

![CleanShot 2023-07-30 at 14 01 55@2x](https://github.com/chaiNNer-org/chaiNNer/assets/2091312/c94d3f24-cff5-4249-8257-32d8809d694c)

After waiting for a couple of seconds, the error message disappears and all dependencies seem to be installed, properly.

#### 4. Running the app.

The app seems to run without any problems, except for the STOP and PAUSE button not working 100% correctly. The UI shows that the workflow is paused or stopped, but the python process is still running in the background. It takes a couple of seconds (30–60 on my system) before the process is actually paused/stopped. But I guess this isn't a specific behavior on Apple Silicon.

#### chaiNNer logs

[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/12209224/logs.zip)

#### Build log

```
➜ npm run make

> chainner@0.18.9 make
> cross-env NODE_ENV=production electron-forge make

✔ Checking your system
✔ Loading configuration
✔ Resolving make targets
  › Making for the following targets: zip, dmg
✔ Running package command
  ✔ Preparing to package application
  ✔ Running packaging hooks
    ✔ Running generateAssets hook
    ✔ Running prePackage hook
      ✔ Running prePackage hook from forgeConfig
      ✔ [plugin-webpack] Preparing native dependencies
      ✔ [plugin-webpack] Building webpack bundles
  ✔ Packaging application
    ✔ Packaging for arm64 on darwin [1s]
  ✔ Running postPackage hook
✔ Running preMake hook
❯ Making distributables
  ✔ Making a zip distributable for darwin/arm64 [6s]
  ✖ Making a dmg distributable for darwin/arm64
    › Cannot find module 'appdmg'
      Require stack:
      - /Users/toni/Developer/chaiNNer/node_modules/electron-installer-dmg/src/index.js
      - /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/maker-dmg/dist/MakerDMG.js
      - /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/core/dist/util/require-search.js
      - /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/core/dist/util/plugin-interface.js
      - /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/core/dist/util/forge-config.js
      - /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/core/dist/util/index.js
      - /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/core/dist/api/index.js
      - /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/cli/dist/electron-forge-make.js
◼ Running postMake hook

An unhandled rejection has occurred inside Forge:
Error: Cannot find module 'appdmg'
Require stack:
- /Users/toni/Developer/chaiNNer/node_modules/electron-installer-dmg/src/index.js
- /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/maker-dmg/dist/MakerDMG.js
- /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/core/dist/util/require-search.js
- /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/core/dist/util/plugin-interface.js
- /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/core/dist/util/forge-config.js
- /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/core/dist/util/index.js
- /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/core/dist/api/index.js
- /Users/toni/Developer/chaiNNer/node_modules/@electron-forge/cli/dist/electron-forge-make.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at build (/Users/toni/Developer/chaiNNer/node_modules/electron-installer-dmg/src/index.js:9:18)
    at module.exports (/Users/toni/Developer/chaiNNer/node_modules/electron-installer-dmg/src/index.js:122:10)
    at async MakerDMG.make (/Users/toni/Developer/chaiNNer/node_modules/@electron-forge/maker-dmg/dist/MakerDMG.js:31:22)
    at async Task.task (/Users/toni/Developer/chaiNNer/node_modules/@electron-forge/core/dist/api/make.js:197:55)
    at async Task.run (/Users/toni/Developer/chaiNNer/node_modules/listr2/dist/index.cjs:978:11)
    at async /Users/toni/Developer/chaiNNer/node_modules/p-map/index.js:57:22
```

**Comment by joeyballentine** [comment]
The issue is that GitHub actions currently doesn't support running arm64 macos, so we have no way of building native arm chaiNNer builds in CI. As far as I can tell, there's no electron-forge setting to have it built for arm on x86, so I don't think I could do it that way either. If you know of some way around this, please let me know

**Comment by stonerl** [comment]
It seems that GitHub has a Public Beta for Apple Silicon runners.

https://github.com/github/roadmap/issues/528

But before providing a native build the last bugs should be ironed out (the fatal error messages).

I'm not familiar with electron-forge. Can you give me a hint how to build the in debug mode so I can maybe figure out why these error messages appear when installing the dependencies.

**Comment by joeyballentine** [comment]
Regarding the dependencies, it might be worth trying to install them manually just to see which one is causing the issues. I looked through your logs and didn't see anything that stuck out.

**Comment by stonerl** [comment]
I enabled the dev-tools: When the error appears, this is what is shown in the console:

```
15:36:37.948 › Running pip command: pip uninstall -y torch torchvision facexlib einops --disable-pip-version-check
index.js:2 
 GET http://127.0.0.1:8000/nodes net::ERR_CONNECTION_REFUSED
15:36:39.638 › TypeError: Failed to fetch
    at kb.fetchJson (index.js:2:882033)
    at kb.nodes (index.js:2:882097)
    at Object.queryFn (index.js:2:906044)
    at Object.fetchFn [as fn] (index.js:2:6090019)
    at s (index.js:2:6106965)
    at new h (index.js:2:6107733)
    at e.fetch (index.js:2:6090391)
    at index.js:2:6101828
    at Array.map (<anonymous>)
    at index.js:2:6101802
index.js:2 
 GET http://127.0.0.1:8000/dependencies net::ERR_CONNECTION_REFUSED
15:36:39.675 › TypeError: Failed to fetch
    at kb.fetchJson (index.js:2:882033)
    at kb.dependencies (index.js:2:882842)
    at Object.queryFn (index.js:2:2622856)
    at Object.fetchFn [as fn] (index.js:2:6090019)
    at s (index.js:2:6106965)
    at new h (index.js:2:6107733)
    at e.fetch (index.js:2:6090391)
    at a.executeFetch (index.js:2:6115177)
    at a.fetch (index.js:2:6115030)
    at a.refetch (index.js:2:6114713)
```

**Comment by joeyballentine** [comment]
You know, that might be intentional. We stop and restart the backend to uninstall optional dependencies, so those errors (so long as they aren't showing up in the UI) are probably fine (if the backend is down intentionally, it can't fetch the data). I think @RunDevelopment is working on something to make that happen though

**Comment by joeyballentine** [comment]
> Should I open a new Issue just for tracking purpose?

Sure

> Do you want me to provide you the Apple Silicon.dmg?

Nah, I don't need it for anything, and I'm not gonna post any builds that aren't built by CI for security purposes.
