### ISSUE TITLE
Pytorch GPU missing for MPS on Apple Silicon

### ISSUE THREAD

**Issue by stonerl** [chaiNNer-org/chaiNNer#2015]
**Information:**

- Chainner version:  [[main 4a6c99e](https://github.com/chaiNNer-org/chaiNNer/commit/4a6c99e819b47a40522e414e8bf26359a18f3b47)]
- OS: [macOS 13.5]

**Description**
Although this commit 28323e839a3d4b2ef57058180dc51a6a0ad26f70 added a newer version of pytorch that supports MPS on Apple Silicon, since no CPU is/can be selected it still falls back to the CPU.

**Logs**
<img width="752" alt="CleanShot 2023-07-30 at 15 02 42@2x" src="https://github.com/chaiNNer-org/chaiNNer/assets/2091312/7941f193-6f50-46c5-921d-a402ce183622">

**Comment by stonerl** [comment]
Found the culprit. These lines:

https://github.com/chaiNNer-org/chaiNNer/blob/4a6c99e819b47a40522e414e8bf26359a18f3b47/src/renderer/components/SettingsModal.tsx#L551-L552

Since only Nvidia GPUs are allowed, the CPU on macOS isn't used. For testing purpose, I changed them to:

```
isDisabled={ncnnGpuList.length === 0}
options={ncnnGpuList.map((gpu, i) => ({
```

and now pytorch uses the GPU.

**Comment by joeyballentine** [comment]
Ah, thank you for figuring that out

**Comment by joeyballentine** [comment]
ok so here's what doesn't make sense to me: Our execution options only use the device ID when the device is CUDA. If it's MPS, the device is just "mps", meaning that the GPU setting shouldn't have anything to do with whether or not MPS works. Would you mind reverting that change and changing [this line](https://github.com/chaiNNer-org/chaiNNer/blob/4a6c99e819b47a40522e414e8bf26359a18f3b47/backend/src/nodes/utils/exec_options.py#L36) to an info log and sending me what it outputs?

**Comment by stonerl** [comment]
I feel somewhat stupid now. 😖

I must have mixed up some pytorch libs. I completely wiped the config folder and did a fresh installation of all dependencies, and now it is using the GPU is expected.

Please excuse the confusion. Closing this one.
