### ISSUE TITLE
PyTorch to NCNN fail

### ISSUE THREAD

**Issue by RalkeyOfficial** [chaiNNer-org/chaiNNer#2021]
I am not sure if this can be classified as a bug or not, so i've decided to classify this as an "Other" issue

I am trying to convert a PyTorch model to NCNN according to [this tutorial](https://github.com/upscayl/upscayl/wiki/%F0%9F%96%A5%EF%B8%8F-Model-Conversion---Create-more-AI-models!).
However, the task ends up giving an error.

note:
I have also installed all the dependencies from the dependency manager (without using pip directly)

error:
```
An error occurred in a PyTorch Convert To NCNN node:

Exporting the operator pixel_unshuffle to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

Input values (partial):
• Data Type: fp16
```

![image](https://github.com/chaiNNer-org/chaiNNer/assets/30209145/7d2bed54-34b7-4bb7-88f7-595d448156fa)

can someone assist me with this issue.
or if this is a bug, reclassify this issue as a bug issue.

**Comment by theflyingzamboni** [comment]
Unfortunately, 2x realesrgan cannot be converted to NCNN, because the necessary operations are not supported. This is also the case for the swinir models. This is out of our control, so I'm going to go ahead and close the issue.

**Comment by Stl5n0** [comment]
here's the ncnn for realesrgan2x_plus 

i have no idea where i found this but it exists

https://drive.google.com/file/d/1UijrIs0DIEVHzxWmFTypLH1BaYhs5L7m/view?usp=drive_link
