### ISSUE TITLE
Homebrew Cask

### ISSUE THREAD

**Issue by stonerl** [chaiNNer-org/chaiNNer#2025]
I'd like to create a homebrew cask for "easier" installation on macOS.

Since chaiNNer isn't signed for macOS, it can't be added to the official repo. But you could host a homebrew tap yourself.

All you need to do is create a new repo in your chaiNNer-org account called: **homebrew-chaiNNer**

I would then open a PR with all necessary files to set up the tap.

**Comment by RunDevelopment** [comment]
May I ask how the setup would look like? I looked around a bit, and it seems like one would have to PR [homebrew-cask](https://github.com/Homebrew/homebrew-cask). Is that right?

Also, no matter the actual repo that hosts the configuration files, how will the workflow for updates look like? I would like to avoid making a new PR homebrew-cask for every release. We largely automated our release process, so it would be nice if we could automate this too. Would that be possible?

> Since chaiNNer isn't signed for macOS

@joeyballentine did something towards that end some time ago. I don't remember why it didn't work out though.

**Comment by stonerl** [comment]
@RunDevelopment 

Take a look at this repo:

https://github.com/italomandara/homebrew-CXPatcher

I helped to create this tap. It is almost fully automated. The only thing that isn't is the auto-merge for PRs when an updated cask is created.

But there you would have either to set up an auto-merge rule or just manually merge the PR (that is what we do ATM)

**Comment by joeyballentine** [comment]
@RunDevelopment I was looking into signing on windows. Signing on MacOS I think just requires you pay $100 a year for a developer account or something. Not sure. It doesn't seem worth it to me when we don't even have windows signing

**Comment by RunDevelopment** [comment]
> Take a look at this repo:

Amazing. In that case, let's do this! Thank you for suggesting this.

I created you the repo you need: [chaiNNer-org/homebrew-chaiNNer](https://github.com/chaiNNer-org/homebrew-chaiNNer). 
(I just guessed the install command based on the other repo you linked. Feel free to change to something that makes more sense.)

**Comment by stonerl** [comment]
Pull request is open. It should be working as soon as you add the secret.

**Comment by stonerl** [comment]
The cask is working:

```bash
➜ brew install --cask --no-quarantine chaiNNer-org/chaiNNer/chainner
==> Tapping chainner-org/chainner
Cloning into '/opt/homebrew/Library/Taps/chainner-org/homebrew-chainner'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 16 (delta 2), reused 13 (delta 2), pack-reused 0
Receiving objects: 100% (16/16), 4.64 KiB | 4.64 MiB/s, done.
Resolving deltas: 100% (2/2), done.
Tapped 1 cask (15 files, 11.8KB).
==> Downloading https://github.com/chaiNNer-org/chaiNNer/releases/download/v0.19.0/chaiNNer-0.19.0
Already downloaded: /Users/toni/Library/Caches/Homebrew/downloads/63cf5d3ccae1666d567fe91068d2392d48092ee79b80e763a3a17211173cd570--chaiNNer-0.19.0-x64-macos.dmg
==> Installing Cask chainner
Warning: macOS's Gatekeeper has been disabled for this Cask
==> Moving App 'chaiNNer.app' to '/Applications/chaiNNer.app'
🍺  chainner was successfully installed!
```

**Comment by RunDevelopment** [comment]
Nice. Thank you for adding all of this @stonerl!

I'm gonna keep the issue open until we tested the next release.

**Comment by stonerl** [comment]
I just read that it appears to be possible to trigger an action from one repo to another. I'll do some testing, maybe we can automate the Homebrew tap even more. Meaning, when you run the `publish` workflow in this repo, it triggers the `bump-chainner-cask`, when ran successfully.

That would result in an updated Homebrew cask, as soon as you publish a new version.

**Comment by joeyballentine** [comment]
It definitely is possible to do that. I did that recently for the chaiNNer website

**Comment by stonerl** [comment]
The bump-chaiNNer-cask workflow also ran flawless. 🎉

**Comment by RunDevelopment** [comment]
Closing this now, since everything seems to work. Thanks again @stonerl!
