### ISSUE TITLE
CodeFormer doesn't work - Failed inference for Face Upscale: ... invalid value for --gpu-architecture (-arch)

### ISSUE THREAD

**Issue by xarathos517** [chaiNNer-org/chaiNNer#2028]
**Information:**

- Chainner version: 0.19.0
- OS: Windows 11, RTX 4070 

**Description**
Attempting to use CodeFormer as a face restoration method seems to do nothing. GFPGAN executes as expected

**Logs**
Logs are attached, I believe the relevant point is: 

`[2023-07-31 23:34:51.031] [info]  Backend: [3516] [ERROR] 	Failed inference for Face Upscale: nvrtc: error: invalid value for --gpu-architecture (-arch)`

[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/12231021/logs.zip)

**Comment by joeyballentine** [comment]
Sorry for the late response. This is a bug certain people get using an old version of pytorch. We will be upgrading the version we recommend using soon (it's pretty old) but in the meantime if you want to avoid this, you can switch to using system python and install a later version of pytorch manually.
