### ISSUE TITLE
Some HAT models are not supported

### ISSUE THREAD

**Issue by Yaiol** [chaiNNer-org/chaiNNer#2032]
**Information:**

- Chainner version: 0.19.0
- OS: Windows 11

**Description**
HAT-S_SRx2.pth, HAT-S_SRx3.pth, HAT-S_SRx4.pth are not supported by chaiNNer
Official HAT models can be found [here](https://drive.google.com/drive/folders/1HpmReFfoUqUbnAOQ7rvOeNU3uf_m69w0)

**Logs**
See log for details [main.log](https://github.com/chaiNNer-org/chaiNNer/files/12237707/main.log)

**Comment by joeyballentine** [comment]
Sorry for the late response. I will try to add support for these eventually.

**Comment by Yaiol** [comment]
is fine :) i just noticed it while doing some test.

**Comment by RunDevelopment** [comment]
Fixed by https://github.com/chaiNNer-org/spandrel/pull/45

This will part of the next release
