### ISSUE TITLE
Add support for custom Automatic1111 Stable Diffusion API Address/Port

### ISSUE THREAD

**Issue by Yaiol** [chaiNNer-org/chaiNNer#2078]
**Motivation**
The current support to Automatic1111 is limited to localhost and standard port.
There is no way to change api address/port

![ChaiNNer - Stable Diffusion Webui Address-Port](https://github.com/chaiNNer-org/chaiNNer/assets/38218161/77461887-d7bc-4d6d-b2fe-ba525371ff93)

**Description**
Add ability to set Automatic1111 Stable Diffusion API Address/Port
A custom address will allow to use stable diffusion webui on a different computer than ChaiNNer
A custom port is necessary because all gradio applications are by default on 7860 which make then impossible to launch them together, is why stable diffusion webui offers the option to change default port with --port command line option.

**Comment by RunDevelopment** [comment]
We already support setting a different host + port. This is currently done via the `STABLE_DIFFUSION_HOST` and `STABLE_DIFFUSION_PORT` environment variables.

---

Documentation for this has been added recently and will be part of the next release. You can download [the latest nightly release](https://github.com/chaiNNer-org/chaiNNer-nightly/releases) if you want to try it out right now. Here's what it looks like:
![](https://user-images.githubusercontent.com/20878432/258165960-139b5c2b-87d2-4ae9-bc1c-6ed66b85087f.png)

**Comment by Yaiol** [comment]
Thank you very much ! it works

![image](https://github.com/chaiNNer-org/chaiNNer/assets/38218161/719c0cea-18c1-4560-9167-ab85a98a8232)
