### ISSUE TITLE
Resize (Resolution Node): image is not resized if width/height factor > 256

### ISSUE THREAD

**Issue by adegerard** [chaiNNer-org/chaiNNer#2100]
**Information:**
- Chainner version: 0.19.2
- OS: Windows 11

**Description**
- When width/height ratio or height/width **ratio is greater than 256**, the image is not generated. Except for width or height equal to **1, ratio is 308**
- It seems that this issue is related to PIL: not sure if this is a bug or a limitation.
![resize-resolution](https://github.com/chaiNNer-org/chaiNNer/assets/137266603/ce29ab15-901e-4cc8-aad5-ec28fdb0f106)

**Logs**
`[2023-08-15 14:23:27 +0200] [360] [ERROR] Error broadcasting output: height and width must be > 0`

**Comment by RunDevelopment** [comment]
It's a bug on our end.

**Comment by RunDevelopment** [comment]
Thanks for reporting!
