### ISSUE TITLE
While you change of Chain using a Model File Iterator node, size of previous node is kept in memory

### ISSUE THREAD

**Issue by Yaiol** [chaiNNer-org/chaiNNer#2120]
**Information:**

- Chainner version: 0.19.3
- OS: Windows 11 Pro 22H02

**Description**
Using two Chains having a Model File Iterator node

If I close ChaiNNer and load chain A it looks like this
![A](https://github.com/chaiNNer-org/chaiNNer/assets/38218161/d2a33189-e62e-4ab8-bc3e-844abd4c3b29)

If I close ChaiNNer and load chain B it looks like this
![B](https://github.com/chaiNNer-org/chaiNNer/assets/38218161/6cd45b5c-c29c-4307-bfcd-55aa68980fe8)

If I close ChaiNNer and load chain A then next chain B, size of model file iterator node is messed up (keeping A size)
![A Then B](https://github.com/chaiNNer-org/chaiNNer/assets/38218161/711a7307-b4b2-45ea-ac32-4e4666642e6e)

If I close ChaiNNer and load chain B then next chain A, size of model file iterator node is messed up (keeping B size)
![B then A](https://github.com/chaiNNer-org/chaiNNer/assets/38218161/f3a635b4-f93d-40bb-bcfb-f18145aaa5fe)

Probably some variable not cleaned correctly.

The two models (rename .chn.txt to .chn)
[A.chn.txt](https://github.com/chaiNNer-org/chaiNNer/files/12383423/A.chn.txt)
[B.chn.txt](https://github.com/chaiNNer-org/chaiNNer/files/12383424/B.chn.txt)

**Comment by joeyballentine** [comment]
Oh that's really weird, thanks for reporting. There's a lot of weirdness with iterator sizing that I'd like to fix at some point, so hopefully I'll get to this soon.

**Comment by Yaiol** [comment]
I think I found the origin of the bug, I create model B from model A
Then into the file it has the same UUI 82f8365a-bd35-4ed8-8798-de20465330a8
Using different models created at different moment I don't have the previous issue.
Probably the variables linked to 82f8365a-bd35-4ed8-8798-de20465330a8 node are kept into memory.

Modifying all occurences of 82f8365a-bd35-4ed8-8798-de20465330a8 with 92f8365a-bd35-4ed8-8798-de20465330a8 with a text editor into model B by hand fixed the issue.

**Comment by Yaiol** [comment]
> Oh that's really weird, thanks for reporting. There's a lot of weirdness with iterator sizing that I'd like to fix at some point, so hopefully I'll get to this soon.

Your are welcome, with the last information I just gave you i think you could fix many weird issues not only this one. Cleaning all nodes into memory before loading the new chain.

**Comment by joeyballentine** [comment]
Yes that sounds like we are just not clearing some state when we load a new chain. Thanks for looking into it!
