### ISSUE TITLE
Error Loading Splash Window

### ISSUE THREAD

**Issue by jfacemyer** [chaiNNer-org/chaiNNer#2121]
**Information:**

- Chainner version: 0.19.3 Portable
- OS: Linux, Manjaro

**Description**
I get this error on start:

`15:47:15.747 › Attempting to check Ffmpeg env...`
`15:47:15.748 › Integrated FFMPEG not found at /chaiNNer-linux-x64/ffmpeg/ffmpeg`
`15:47:15.748 › Downloading integrated FFMPEG...`
`15:47:15.762 › Error loading splash window. Error: ERR_FAILED (-2) loading '/chaiNNer-linux-x64/resources/app/.webpack/renderer/splash_screen/index.html'`
`    at rejectAndCleanup (node:electron/js2c/browser_init:2:84929)`
`    at WebContents.stopLoadingListener (node:electron/js2c/browser_init:2:85304)`
`    at WebContents.emit (node:events:513:28)`

It doesn't appear to download ffmpeg, not sure if that's why the splash won't load?

Thanks!

**Comment by joeyballentine** [comment]
I don't know if that's necessarily related, as the issue seems to be with actually loading the splash screen window itself. Are you able to use the non-portable version?

**Comment by joeyballentine** [comment]
I think if you're on arch you need to install xcrypt or libxcrypt or something in order for it to work right. I'm not entirely sure.

**Comment by jfacemyer** [comment]
I did install libxcrypt before submitting this - that fixed a different error.

Thoughts?

**Comment by joeyballentine** [comment]
I think someone has been publishing chaiNNer unofficial on AUR, could you try that one? Or try the portable Linux zip version? Other than that, I'm not really sure what to try as I'm not familiar with the Linux ecosystem

**Comment by jfacemyer** [comment]
The linux portable zip is what I'm using :/

I'll look for the AUR.

**Comment by RunDevelopment** [comment]
The splash screen was removed in #2731, so the splash screen not loading won't be an issue anymore.
