### ISSUE TITLE
TypeError: failed to fetch

### ISSUE THREAD

**Issue by HypnoticKing** [chaiNNer-org/chaiNNer#2135]
**Information:**

- Chainner version:0.19.3
- Windows 10, 

I checked ](https://github.com/chaiNNer-org/chaiNNer/issues) for possible fixes but didn't find anything that i quite what I am experiencing
I have been using chaiNNer for about a year.  I use it to upscale midjourney images and after banging my way though i figured out the the way that has been working for me.   I have been running my images through the following 2 series. 1 for batching and 1 for single runs.  My files are located directly on d drive so it is simply D:file name.  so on the iterator i click to find the file. click on the file and press run. it runs for 12 mins and then gives me (chaiNNer failed image)  If I try to run individual files on this set up  (chaiNNer 2 set up image) it will run for 10-12 mins and give the same error.  Was going to uninstall chaiNNer and redownload but my sysytem says it cannot find chaiNNer.exe
**Logs**

[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/12412810/logs.zip)
[images_to_go_with_12412810 logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/12412834/images_to_go_with_12412810.logs.zip)

**Comment by joeyballentine** [comment]
The error I'm seeing in your logs is that your file you're referencing doesn't exist. Can you verify that you have proper files selected?

**Comment by HypnoticKing** [comment]
I tried  a different file and it did work.  The files I was trying to render were files i made on midjourney. I brought those files into Inkscape, duplicated then flipped them and made a mirror type image.  I was these images I was trying to run through chaiNNer but I think it was searching for the individual file for some reason and having 3 more of the same images attached to it confused the program so it was saying "failed image" . I'll just run the original then do my duplicating.  Thank You for looking into it and helping me find my error. chaiNNer is amazing even though I don't know how to use most of it.  I take my files from Midjourney then convert them to jpg (the model creator says it works best on jpg images.)  Then run through my setup on chaiNNer.  That file is to big for the platform I am using so I reconvert to jpg and it brings the size down.  I need the sharpest image at 74"x74" I can create    Not a lot of info on the internet.  Thanks again Joey
