### ISSUE TITLE
error when installing framework from dependency manager

### ISSUE THREAD

**Issue by lmvgjp** [chaiNNer-org/chaiNNer#2170]
hello,

i cannot install dependencies..could you please help?
thanks

i get this error
![error](https://github.com/chaiNNer-org/chaiNNer/assets/91534245/e69dbdee-86a5-4d29-9993-0680d258cfa5)

**Comment by joeyballentine** [comment]
Can you send your logs? (Help > open logs folder)

**Comment by joeyballentine** [comment]
Unfortunately I'm not seeing any helpful info in those. What OS are you on? Does it happen with all the dependencies or just pytorch? Are you able to use pip normally on your system through a terminal?

**Comment by lmvgjp** [comment]
i tried again and it worked now :)
i am on Ubuntu
i had a process running in parallel, maybe that one interfered the  installing

thank you so much! very kind for your fast reply
