### ISSUE TITLE
Error report: Object has been destroyed

### ISSUE THREAD

**Issue by KimoSlice** [chaiNNer-org/chaiNNer#2172]
```
TypeError: Object has been destroyed
```
ChaiNNer: chaiNNer 0.17.1
OS: Windows NT 10.0.22621

**Comment by joeyballentine** [comment]
Do you actually have windows NT?

**Comment by joeyballentine** [comment]
Also, update chaiNNer please, I think we fixed this somewhere after 0.17

**Comment by KimoSlice** [comment]
Hey there,

no I actually don't, also restarted and everything worked fine :) so I
guess some mistake on my side, just thought always helps to send out
errors ✌

thanks!

Am Mi., 30. Aug. 2023 um 21:25 Uhr schrieb Joey Ballentine <
***@***.***>:

**Comment by joeyballentine** [comment]
Thanks for reporting, and if it happens again on a later version definitely let us know
