### ISSUE TITLE
Problem with onnxruntime

### ISSUE THREAD

**Issue by Sapelain** [chaiNNer-org/chaiNNer#2181]
The problem I have is that "onnxruntime" is missing. And when I go to "Manage Dependencies" it comes out as "Missing". When giving install (6 MB) I never finish installing it  .

![2](https://github.com/chaiNNer-org/chaiNNer/assets/126752527/897c827a-8c60-483d-97a5-b74b01675fab)

**Information:**

- Chainner version: [v.0.19.4]
- OS: [e.g. Windows 10 64 Bits]

**Logs**
Requirement already satisfied: onnx==1.14.0 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (1.14.0)
Requirement already satisfied: numpy in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from onnx==1.14.0) (1.23.2)
Requirement already satisfied: typing-extensions>=3.6.2.1 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from onnx==1.14.0) (4.6.3)
Requirement already satisfied: protobuf>=3.20.2 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from onnx==1.14.0) (3.20.2)
Requirement already satisfied: onnxoptimizer==0.3.13 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (0.3.13)
Requirement already satisfied: onnx in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from onnxoptimizer==0.3.13) (1.14.0)
Requirement already satisfied: protobuf>=3.20.2 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from onnx->onnxoptimizer==0.3.13) (3.20.2)
Requirement already satisfied: typing-extensions>=3.6.2.1 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from onnx->onnxoptimizer==0.3.13) (4.6.3)
Requirement already satisfied: numpy in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from onnx->onnxoptimizer==0.3.13) (1.23.2)
Collecting onnxruntime==1.15.1
  Downloading onnxruntime-1.15.1-cp39-cp39-win_amd64.whl (6.7 MB)
Downloading package from PyPi at: https://files.pythonhosted.org/packages/6a/fb/99bc0e75f3d23eab0dda640acaf23d0a3a68c3949a56ac5c25698eab4958/onnxruntime-1.15.1-cp39-cp39-win_amd64.whl
Download at: 0%
Download at: 5%
Download at: 10%
Download at: 15%
Download at: 20%
Download at: 25%
Download at: 30%
Download at: 35%
Download at: 40%
Download at: 45%
Download at: 50%
Download at: 55%
Download at: 60%
Download at: 65%
Download at: 70%
Download at: 75%
Download at: 80%
Download at: 85%
Download at: 90%
Download at: 95%
Download at: 100%
Installing package from whl...
Processing c:\users\sapelain\appdata\local\temp\onnxruntime-1.15.1-cp39-cp39-win_amd64.whl
Requirement already satisfied: coloredlogs in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from onnxruntime==1.15.1) (15.0.1)
Requirement already satisfied: protobuf in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from onnxruntime==1.15.1) (3.20.2)
Requirement already satisfied: packaging in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from onnxruntime==1.15.1) (23.1)
Requirement already satisfied: sympy in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from onnxruntime==1.15.1) (1.12)
Requirement already satisfied: flatbuffers in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from onnxruntime==1.15.1) (23.5.9)
Requirement already satisfied: numpy>=1.21.6 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from onnxruntime==1.15.1) (1.23.2)
Requirement already satisfied: humanfriendly>=9.1 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from coloredlogs->onnxruntime==1.15.1) (10.0)
Requirement already satisfied: pyreadline3 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime==1.15.1) (3.4.1)
Requirement already satisfied: mpmath>=0.19 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from sympy->onnxruntime==1.15.1) (1.3.0)
Installing collected packages: onnxruntime
Requirement already satisfied: protobuf==3.20.2 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (3.20.2)
Requirement already satisfied: numba==0.56.3 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (0.56.3)
Requirement already satisfied: numpy<1.24,>=1.18 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from numba==0.56.3) (1.23.2)
Requirement already satisfied: setuptools in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from numba==0.56.3) (58.1.0)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in h:\portableapps\chainner win x64 v0.18.7 portable (ai image upscaler)\python\python\lib\site-packages (from numba==0.56.3) (0.39.1)

**Comment by joeyballentine** [comment]
Can you go to `Help > Open Logs Folder` and send the logs from there please? My guess is that it's failing to import the dependency and i would like to see why

**Comment by Sapelain** [comment]
Sorry I can't upload the log because I deleted everything. But fix the error by deleting everything and installing everything from scratch. I reckon it would be some memory or cache because where the old facility was 16GB
