### ISSUE TITLE
Option to save DDS textures in uncompressed format

### ISSUE THREAD

**Issue by GamerzHell9137** [chaiNNer-org/chaiNNer#2184]
I'm trying to upscale some textures for games but they are using uncompressed DDS format textures which need to be saved as such.
Atm chaiNNer is forcing one of the BCN formats and its not letting save in uncompressed format or in the original format of the texture (that would be preferable since games use a mix of uncompressed and other BCN formats, DXT5 as an example)

An option to choose uncompressed format for DDS files would be nice or ideally to automatically take the format the original file and save it as such.

![image-1](https://github.com/chaiNNer-org/chaiNNer/assets/2002038/74ea7260-7106-4fa4-bb64-d3480ed51c1c)

The file uploaded is a dds uncompressed texture file so just rename the .zip to .dds or i can reupload the texture in a zip file if needed.

[tex2d_0300cae2f72ebdcda8cccfa524f66170_1440x1440x1.zip](https://github.com/chaiNNer-org/chaiNNer/files/12508829/tex2d_0300cae2f72ebdcda8cccfa524f66170_1440x1440x1.zip)

**Comment by RunDevelopment** [comment]
This should be relatively easy to add. We use `texconv` behind the scenes to write DDS files, so we just have to pass it the right arguments.

That being said, we should probably add support for uncompressed formats with multiple bit depths. DDS supports basically anything that we could every want (R32G32B32, R16G16B16, R8G8B8, R5G6B5 + alpha variants), so we have to think about how to present this.
