### ISSUE TITLE
"Failed to create CUDAExecutionProvider" Error when using CUDA with ONNX in Ubuntu 22.04

### ISSUE THREAD

**Issue by s7habo** [chaiNNer-org/chaiNNer#2188]
**Information:**

- Chainner version: Alpha 0.19.4
- OS: Ubuntu Studio 22.04

**Description**

When using CUDA in ONNX CUDA is not active although it is detected and selected in the settings:

![grafik](https://github.com/chaiNNer-org/chaiNNer/assets/38165484/1b856cb9-9e47-46f6-ad64-691f83eea380)

Processing takes a long time and only CPU is used in the display:

![grafik](https://github.com/chaiNNer-org/chaiNNer/assets/38165484/82b8b101-eb3f-497a-8345-2618af81a651)

In the log file also appears the error entry "Failed to create CUDAExecutionProvider".

in PyTorch GPU works as expected. I can see that both in the processing speed and in the load on VRAM. 

**Logs**

[main.log](https://github.com/chaiNNer-org/chaiNNer/files/12526643/main.log)

Here are some important details about my system:

Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.19.0-1028-lowlatency (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2
NVIDIA Driver Version: 535.86.05

**Comment by s7habo** [comment]
With new chainNNer version 0.20.0 and included updates of CUDA and ONNX everything works again. This bug report can now be closed.

Thanks for update!

**Comment by joeyballentine** [comment]
Great! Must have just been the older version of ONNX that was the issue
