### ISSUE TITLE
Unable to convert DAT .pth to .param/.bin

### ISSUE THREAD

**Issue by ferrosa** [chaiNNer-org/chaiNNer#2224]
**Information:**

- Chainner version: v.0.20.1
- OS: Ubuntu 22.04.3 amd64

**Description**
Unable to convert a `.pth` file in the new DAT format _[1]_ to `.param`/`.bin` needed by ncnn CLI tools.

[pth2bin.zip](https://github.com/chaiNNer-org/chaiNNer/files/12643163/pth2bin.zip)

![Screenshot from 2023-09-17 17-14-17](https://github.com/chaiNNer-org/chaiNNer/assets/20930937/d531c107-d6da-407b-a029-b667d4bf54e7)

_[1]_ model example: https://openmodeldb.info/models/4x-FaceUpLDAT

**Comment by joeyballentine** [comment]
This is not a bug. NCNN does not support the ops required to run transformer-based models. Pease open an issue in the NCNN repo about this (they'll probably tell you they won't do it though)
