### ISSUE TITLE
Support Unet models (?)

### ISSUE THREAD

**Issue by ferrosa** [chaiNNer-org/chaiNNer#2228]
**Motivation**
Trying to use this model:
https://openmodeldb.info/models/2x-VimeoScale-Unet

**Description**
chaiNNer's PyTorch model loader doesn't like the format:
![Screenshot from 2023-09-18 13-08-23](https://github.com/chaiNNer-org/chaiNNer/assets/20930937/d2e5d420-2ce4-4162-979c-adc5d944df8a)

Terminal log:
```
Backend: [22572] [ERROR] Model 2x-VimeoScale-Unet.pth is unsupported by chaiNNer. Please try another.
Traceback (most recent call last):
  File "/usr/lib/chainner/resources/src/nodes/impl/pytorch/model_loading.py", line 105, in load_state_dict
    model = ESRGAN(state_dict)
            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/nodes/impl/pytorch/architecture/RRDB.py", line 83, in __init__
    if self.state["model.0.weight"].shape[-2] == 2:
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'model.0.weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/chainner/resources/src/packages/chaiNNer_pytorch/pytorch/io/load_model.py", line 106, in load_model_node
    model = load_state_dict(state_dict)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/nodes/impl/pytorch/model_loading.py", line 108, in load_state_dict
    raise UnsupportedModel
nodes.impl.pytorch.model_loading.UnsupportedModel

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/chainner/resources/src/process.py", line 106, in run_node
    raw_output = node.run(*enforced_inputs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/packages/chaiNNer_pytorch/pytorch/io/load_model.py", line 120, in load_model_node
    raise ValueError(
ValueError: Model 2x-VimeoScale-Unet.pth is unsupported by chaiNNer. Please try another.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/chainner/resources/src/server.py", line 245, in run_individual
    output, execution_time = await app.loop.run_in_executor(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ferrosa/.config/chaiNNer/python/python/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/process.py", line 325, in wrapper
    result = supplier()
             ^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/process.py", line 115, in run_node
    raise NodeExecutionError(node_id, node, str(e), input_dict) from e
process.NodeExecutionError: Model 2x-VimeoScale-Unet.pth is unsupported by chaiNNer. Please try another.

```

**Alternatives**
As I'm fairly new to this, I'm not sure how I would go about testing this model. The "Unet" tag seems to imply something, but then again chaiNNer seems to load all other `.pth` files just fine.

**Comment by joeyballentine** [comment]
The actual model can be found here: https://openmodeldb.info/models/4x-VimeoScale

What you found was a discriminator model, which is only useful when training. This one seems to have been automatically added with the regular model's description. This is an error that should be fixed on OpenModelDB. I will open an issue there.

**Comment by joeyballentine** [comment]
And actually, that model won't be usable in chaiNNer either. It is for the SOFVSR architecture which is for videos and not images (too complicated to explain what the difference is) and as such it will not be added to chaiNNer for the foreseeable future. SOFVSR is also just kinda an old/outdated and not great architecture to begin with. I recommend just finding a different model to use

**Comment by ferrosa** [comment]
Interestingly, I can run both with https://github.com/joeyballentine/Video-Inference

`python3 run.py models/2x-VimeoScale-Unet.pth` produces actually decent results: upscaling photorealistic input without turning everyone into a plastic doll (like most SR models I've tried so far on OpenModelDB)... any pointers to a good alternative model trained on things like Vimeo?

**Comment by joeyballentine** [comment]
Well in that case, the description for the model is wrong and it's not a pretrained discriminator lol.

Anyway, yeah my video inference repo will run SOFVSR models, however it's not a very good script for doing so. I didn't know what I was doing back then, and so the script loads the entire video into RAM before processing it. So definitely don't use it for large videos.

And I'm not good at recommending models unfortunately.

**Comment by ferrosa** [comment]
I'll keep triaging models, thanks for your work and for bearing with me here.

Since that model seems fairly useful: any general pointers to how I'd convert/reuse it?
Can it be fed to https://github.com/joeyballentine/traiNNer-redux or similar? (which seems more maintained than https://github.com/XPixelGroup/BasicSR, what's up with that?)

**Comment by ferrosa** [comment]
Thanks for all the input! I'll give traiNNer (and neosr) a thorough look once I get through a few other tools (TensorRT and various stabilisers).
Single-image networks get that much more attention :( ... but it's all awesome anyway!

When looking at fork relations, I was properly confused by apparent cyclic provenance such as [traiNNer](https://github.com/victorca25/traiNNer/tree/master) -> [BasicSR](https://github.com/DinJerr/BasicSR), [BasicSR](https://github.com/XPixelGroup/BasicSR) -> [traiNNer-redux](https://github.com/joeyballentine/traiNNer-redux). These two BasicSR projects are not associated, right?

Nitpick: people might appreciate a "dormant" or "unmaintained" banner.

Also:
> the script loads the entire video into RAM before processing it. So definitely don't use it for large videos.

Got 64 gigs of RAM on that machine, and it's the best model I've found so far for upscaling my particular media, so guess who's using Video-Inference for hundreds of large videos in 2023...

**Comment by joeyballentine** [comment]
traiNNer is a fork of a really old version of BasicSR before it got rewritten a bunch. traiNNer-redux is a fork of newer basicsr where I tried to add back some of the features traiNNer added. NeoSR is kinda the same thing (fork of new basicsr) but incredibly slimmed down to just the basics + support for some newer SISR architectures

> Got 64 gigs of RAM on that machine,

Well, I guess go nuts then 😆

**Comment by FNsi** [comment]
> and so the script loads the entire video into RAM before processing it. 

Great stuff, I was hesitated to try cause I do care much of my SSD😂
