### ISSUE TITLE
Memory error with AMD Rocm

### ISSUE THREAD

**Issue by Loacoon1** [chaiNNer-org/chaiNNer#2240]
**Information:**

- Chainner version: 0.20.0
- OS: Manjaro Linux

**Description**
When doing an inference using Pytorch with an AMD card, it triggers a memory error.

**Logs**
Here is the relevant part:
```
Backend: Memory access fault by GPU node-1 (Agent handle: 0x557ad180a690) on address 0x7f909586b000. Reason: Page not present or supervisor privilege.
Python subprocess exited with code null and signal SIGABRT
```

**Comment by joeyballentine** [comment]
I'm not sure rocm is really properly supported in pytorch. Is there any other info you can give? I assume you installed the rocm version yourself? Was this on a fairly large image?

**Comment by Loacoon1** [comment]
Hi, thanks for the answer. Yeah sorry, after your message I realized that I did update Pytorch the same day I updated Chainner, so I did downgrade it and the error stopped. I made a bug report upstream. Sorry again, this can be closed.
