### ISSUE TITLE
Can't download integrated python in windows.

### ISSUE THREAD

**Issue by FNsi** [chaiNNer-org/chaiNNer#2244]
99% sure it's base on my shit "internet" 

May you offer a direct link for the whole python stuff or allow to use an local python?

**Comment by dnblank123** [comment]
You can follow this guide: https://github.com/chaiNNer-org/chaiNNer/issues/1796#issuecomment-1546782902

**Comment by joeyballentine** [comment]
@dnblank123 that's for pytorch. For python, you'll have to download python-build-standalone from here: https://github.com/indygreg/python-build-standalone/releases/download/20230826/cpython-3.11.5+20230826-x86_64-pc-windows-msvc-shared-install_only.tar.gz and extract it to the same python folder mentioned in the comment dnblank mentioned

**Comment by FNsi** [comment]
> For python, you'll have to download python-build-standalone from here: https://github.com/indygreg/python-build-standalone/releases/download/20230826/cpython-3.11.5+20230826-x86_64-pc-windows-msvc-shared-install_only.tar.gz

Nice, no clue why I couldn't download it automatically

**Comment by joeyballentine** [comment]
You can enable system python in chaiNNer's settings. We just use our own env by default so we don't screw up your system python without your consent

**Comment by FNsi** [comment]
> You can enable system python in chaiNNer's settings. We just use our own env by default so we don't screw up your system python without your consent 

that's tough enough for man like me who can't open it at the beginning 😂😂

**Comment by FNsi** [comment]
> Yeah 😂 Most people don't have that problem though. I've considered bundling the python files instead of downloading them, maybe it's time to do that

😂😂😂many thanks
