### ISSUE TITLE
replicate.com to Output

### ISSUE THREAD

**Issue by fire** [chaiNNer-org/chaiNNer#2248]
**Motivation**

I am looking for a way to easily run machine learning models in the cloud from my own chaiNNer graph. I want to be able to run both open-source models and my own public and private models.

**Description**

The proposed feature is to add Replicate to Text / Replicate to Image / Replicate to Video functionality. This would allow users to use Replicate, a tool that makes it easy to run machine learning models in the cloud, directly from a chaiNNer graph. 

Here is some example models:

1. **Replicate to Text (json)** Mediapipe Blendshape Labeler - Predicts the blend shapes of an image. https://replicate.com/fire/v-sekai.mediapipe-labeler?prediction=uhxvubzb5u5tptmcqfluyczul4
1. **Replicate to Image** Mediapipe Blendshape Labeler - Predicts the blend shapes of an image. https://replicate.com/fire/v-sekai.mediapipe-labeler?prediction=uhxvubzb5u5tptmcqfluyczul4
2. **Replicate to Text json** https://replicate.com/a16z-infra/mistral-7b-v0.1
3. **Replicate to Image** https://replicate.com/stability-ai/sdxl
4. **Replicate to Video** https://replicate.com/zsxkib/animate-diff

I can work on this if you can describe an approach to code.

**Alternatives**

An alternative solution could be to use the existing stable diffusion webui, but it may require more setup and configuration compared to Replicate.

**Comment by joeyballentine** [comment]
I don't want to integrate an external/cloud API as a main feature of chaiNNer (for various reasons). This would make a great third party plugin though, but that feature is still WIP and isn't possible right now (it's maybe 50% finished).

Feel free to work on it though, if it's useful to you then it's not a waste of time and it could eventually be converted to a plugin once that's ready. The plugin stuff is just complicated and I haven't had time to finish everything that's needed for it.

Relevant docs: https://github.com/chaiNNer-org/chaiNNer/blob/main/docs/nodes.md

**Comment by fire** [comment]
@joeyballentine Would you accept code where I find an pytorch, onnx or a ncnn model that does[image, text, video] things?

**Comment by joeyballentine** [comment]
Yes, especially for images and text. Not sure about audio or video right now as that would be adding some brand new data types to chaiNNer (and depending on what kind of video processing you're trying to do, might be too complex for chaiNNer right now), but if it's done correctly then I see no problem with it.

If it's anything diffusion related, I'd be a bit more hesitant as that opens a big can of worms with many extra dependencies. I'm always open for adding things though and I definitely don't want to discourage contributions, I just want to make you aware that that kind of thing would be a lot of work.

**Comment by fire** [comment]
I'll close this issue for now since an external/cloud API as a main feature of chaiNNer was not accepted.

Will make a new proposal for the pytorch, onnx or a ncnn model model loading.
