### ISSUE TITLE
Cast paths/directories to string

### ISSUE THREAD

**Issue by joeyballentine** [chaiNNer-org/chaiNNer#2250]
Suggested in the RTX Remix discord. Users should be able to connect directories to string inputs, or there should be a path to text node that can turn a path into a string with options for Unix or Windows formatting

**Comment by RunDevelopment** [comment]
> with options for Unix or Windows formatting

Would that even be possible? I can see how one would format a windows path (e.g. `C:\foo\bar`) in unix style (e.g. `/c/foo/bar`), but not the other way around (e.g. what is `/foo/bar` in windows style? There is no drive).

So I guess the only styles we can support are unix and "native" (= the raw path).

**Comment by joeyballentine** [comment]
> e.g. what is /foo/bar in windows style? There is no drive

`\\foo\\bar`

**Comment by RunDevelopment** [comment]
> > e.g. what is /foo/bar in windows style? There is no drive
> 
> `\\foo\\bar`

That not a valid path anywhere...

**Comment by joeyballentine** [comment]
why can't partial/relative paths be valid?

**Comment by RunDevelopment** [comment]
`/foo/bar` is an absolute path. That's why `\foo\bar` doesn't make sense.

**Comment by RunDevelopment** [comment]
Resolved by #2695.
