### ISSUE TITLE
Incorrect result of the Normalize Normal map node

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [chaiNNer-org/chaiNNer#2263]
chaiNNer 0.20.1

Files: [normalize_normalmap_test.zip](https://github.com/chaiNNer-org/chaiNNer/files/12898599/normalize_normalmap_test.zip)

![image](https://github.com/chaiNNer-org/chaiNNer/assets/4449851/fd8ee1bd-efe6-4130-927d-537c703aafbe)

Chainner:
![image](https://github.com/chaiNNer-org/chaiNNer/assets/4449851/7419bf07-5051-4250-853b-15cda2343c3e)
Substance designer:
![image](https://github.com/chaiNNer-org/chaiNNer/assets/4449851/0d2f9753-dc13-4358-858d-b5bacd07331a)

P.S.: I forgot to convert to 8-bit at Substance designer but [it doesn't matter](https://github.com/chaiNNer-org/chaiNNer/assets/4449851/00b34960-0902-4555-a109-c8b7ac1b8c51)

**Comment by RunDevelopment** [comment]
It's not incorrect, we just store the B channel differently. As you know, the X, Y, and Z components of the normals are stored in the R, G, and B color channels. Normals are normalized vectors, so all components are between -1 and 1. To convert this to the 0-1 RGB values we need, we simply do `(XYZ+1)/2`. And that is exactly what substance designer is doing. However, we know that the Z values of tangent-space normals is actually always between 0 and 1, so we don't need to apply the transformation to Z and can store it as is.

Both of these approaches are used in practice (AFAIK). Transforming all of XYZ (like substance designer does) has the advantage that you aren't limited to tangent-space normals. Storing B=Z has the advantage that we store normals with slightly more precision.

There is no best way to store normals, and there is also no real industry consensus on how to do, unfortunately. This is why some texture artists don't even try to normalize normals (some will just set B to 1 or some other value), the DDS image format for normals doesn't even store the B channel (and also doesn't re-compute it), and many game engines just completely ignore the B channel in normal textures and re-compute it on the fly (games also typically compress texture, which means that game engines can't trust the normals they read to be normalized anymore, so they have to renormalize anyway).

So, that's how it is. Not sure what to do about though.

**Comment by 0x4E69676874466F78** [comment]
Okay.
