### ISSUE TITLE
Allow forced tiling at least for scunet

### ISSUE THREAD

**Issue by SomeOrdinaryDude** [chaiNNer-org/chaiNNer#2269]
**Motivation**
Models like Scunet require a lot of memory, and I can't denoise larger images without manually splitting _(which I can't figure out how to do for multiple images/a video)_

**Description**
Scunet appears to work well with manual tiling, so I want at least scunet or perhaps a universal option allowing forced tiling for the model, even if not explicitly supported. The fact that tiling isn't supported by the standard model configuration, should be noted to the user.

**Alternatives**
I tried manually tiling the image via sprite sheet and stacked images. That way I could quickly denoise large 4K images on my GPU. I tried a similar setup with image iterators and video frame iterators, but the nodes became incompatible then, so to my understanding, it's not possible to manually tile with video frames or multiple images. 

![image](https://github.com/chaiNNer-org/chaiNNer/assets/79510944/c2956b9f-3c27-4d0e-82ca-129a9beed4f4)

This hacky method to split images worked well, but again, I only managed to get it working for single images.

**Comment by adegerard** [comment]
To simplify: this algo needs the whole image for denoising.

As explained in the original paper, and repo https://github.com/cszn/SCUNet, it uses both local and non-local values and this is why tiling should not be used. 

When denoising a tile, the algo needs the values from the whole image but it has not access to that, because it is splitter. The result is worst and tiles may become visible.

You can try with automatic 1111, I opened an issue about that artifacts.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12524

Denoising a 4K image with SCUnet is not serious. Downscaling it will give you better result.

**Comment by SomeOrdinaryDude** [comment]
> [AUTOMATIC1111/stable-diffusion-webui#12524](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12524)

That's strange, in my tests, it looked good. Maybe it's because I only have two tiles. I see most models produce seams if there are a lot of tiles.

**Comment by SomeOrdinaryDude** [comment]
> To simplify: this algo needs the whole image for denoising.
> 
> As explained in the original paper, and repo https://github.com/cszn/SCUNet, it uses both local and non-local values and this is why tiling should not be used.
> 
> When denoising a tile, the algo needs the values from the whole image but it has not access to that if you split it. The result is worst and tiles may become visible.
> 
> You can try with automatic 1111, I opened an issue about that artifacts. [AUTOMATIC1111/stable-diffusion-webui#12524](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12524)
> 
> Denoising a 4K image with SCUnet is not serious. Downscaling it will give you better result.

Thanks for informing me about the AUTOMATIC1111 option, then I can use this for now, since it supports batch processing. On the first test which for some reason picked 299 tiles, it still looked really good on my test, only a few visible artifacts.

**Comment by adegerard** [comment]
> only a few visible artifacts
Could you please describe what type of artifacts?

**Comment by SomeOrdinaryDude** [comment]
> > only a few visible artifacts
> 
> Could you please describe what kind of artifacts?

Just the usual inconsistencies where some spots are much softer than they should be. Pretty much gone when only using a few tiles.
