### ISSUE TITLE
How to download dependcy seprately

### ISSUE THREAD

**Issue by willdla** [chaiNNer-org/chaiNNer#2288]
npm run start 

when download ncnn dependcy

<img width="807" alt="image" src="https://github.com/chaiNNer-org/chaiNNer/assets/93644542/26a6f505-d37a-4167-8b93-1f6990262927">

but get 

<img width="1220" alt="image" src="https://github.com/chaiNNer-org/chaiNNer/assets/93644542/0a575c19-1397-4bea-9c60-4c7cbf5b4ef7">

so how to fix this, i can wget https://files.pythonhosted.org/packages/1e/23/96f01ea14617364a41d1653962db0ec776fb1ca195b770d43e4fcf5bdf8c/ncnn_vulkan-2023.6.18-cp311-cp311-macosx_11_0_arm64.whl in my terminal but always fail in chaiNNer.

same problem when getting pytorch and onnx.

**Comment by RunDevelopment** [comment]
Weird. Firstly, could you send us your logs? In the Menu go Help > Open log folder. We need `main.log` and `renderer.log`. Secondly, could you try enabling the "Use Pip directly" switch? It might work with that turned on.

**Comment by RunDevelopment** [comment]
Closed due to inactivity.
