### ISSUE TITLE
Interface window buttons cannot enter disabled state

### ISSUE THREAD

**Issue by hanrai** [chaiNNer-org/chaiNNer#2307]
**Information:**

- Chainner version: 0.20.2 (20231104 source code)
- OS: Windows 11 pro

**Description**
I encountered a bug when using the chainner project, which caused the interface window buttons to not enter the disabled state.Specifically, when I run a task, the buttons (Run, Pause, Stop) on the interface look all available, but clicking on them will produce an error. I expect that, when a task is running, the Run button should become disabled, and the Pause and Stop buttons should become enabled. When I pause or stop a task, the Run button should become enabled, and the Pause and Stop buttons should become disabled.

**Logs**
main.log
[2023-11-04 12:10:01.241] [info]  Cleaning up temp folders...
[2023-11-04 12:10:15.227] [info]  chaiNNer Version: 0.20.2
[2023-11-04 12:10:15.234] [info]  Attempting to setup backend from http://127.0.0.1:8000...
[2023-11-04 12:10:15.402] [info]  Successfully connected to setup SSE.
[2023-11-04 12:11:40.808] [info]  Cleaning up temp folders...
render.log: N/A

This bug was caused by a breaking change introduced by the chakra ui upgrade .I checked the chakra ui documentation and found that they made some changes to the Button component recently, one of which is changing the disabled property to the isDisabled property.
[https://github.com/chakra-ui/chakra-ui/issues/7269](url)
![20231104121542](https://github.com/chaiNNer-org/chaiNNer/assets/7495736/ebd66103-2357-4ee7-9464-6e5663cf082d)

**Comment by joeyballentine** [comment]
Thank you for noticing this and letting us know. I'll work on fixing that tomorrow
