### ISSUE TITLE
PyTorch GPU not recognized

### ISSUE THREAD

**Issue by MatthewRiley05** [chaiNNer-org/chaiNNer#2312]
**Information:**

- Chainner version: 0.20.2
- OS: Windows 11

**Description**
I am using my laptop with an integrated Radeon 780m and a dedicated 4070. For some reason, in the PyTorch panel, I'm not being allowed to pick a GPU, so the upscaling process runs on the CPU but on the NCNN page, both my GPUs show up. The PyTorch GPU selection panel is grayed out and says "no options found".

**Comment by joeyballentine** [comment]
In the dependency manager, if you expand the pytorch section, did it install the `+cu###` version of pytorch? if it didn't, then it must be thinking that your machine isn't capable of using CUDA for whatever reason. 

Could you send over your main.log file? (help > open logs folder)

**Comment by MatthewRiley05** [comment]
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/13257509/main.log)

![Screenshot 2023-11-05 025939](https://github.com/chaiNNer-org/chaiNNer/assets/52445584/cf5ca152-098b-4b1c-b615-54aaa7dfba2a)

**Comment by joeyballentine** [comment]
And no GPU appears in the pytorch GPU list at all? This is super weird. It detected that you have an nvidia gpu, but pytorch seems to not recognize it for some reason.

**Comment by MatthewRiley05** [comment]
Yes, no GPU appears. I'm going to try to reinstall it, maybe it's just a bug or something.

**Comment by MatthewRiley05** [comment]
Okay yeah for some reason, clean reinstalling worked
