### ISSUE TITLE
the animation keeps playing

### ISSUE THREAD

**Issue by hooke007** [chaiNNer-org/chaiNNer#2319]
**Information:**

- Chainner version: latest [nightly](https://github.com/chaiNNer-org/chaiNNer-nightly/releases/tag/2023-11-04)
- OS:  Windows 10

**Description**

The work seems to be actually finished but the animation keeps playing.

![Snipaste_2023-11-07_12-30-11](https://github.com/chaiNNer-org/chaiNNer/assets/41094733/a32d740c-6cc0-4eb4-8136-3d1b24881a55)

**Logs**

[main.log](https://github.com/chaiNNer-org/chaiNNer/files/13275712/main.log)
[renderer.log](https://github.com/chaiNNer-org/chaiNNer/files/13275713/renderer.log)

**Comment by joeyballentine** [comment]
Known problem that I haven't had time to fix yet. Thanks for reporting though 👍
