### ISSUE TITLE
Failed WEBP encode does not throw warning in UI

### ISSUE THREAD

**Issue by Kim2091** [chaiNNer-org/chaiNNer#2332]
**Information:**

- Chainner version: 11-10 nightly
- OS: Windows 11

**Description**
When an error occurs while encoding a WEBP file with the `Save Image` node, it does not throw an error in the UI, only in the log. This was the error in my case:

> [2023-11-21 20:51:55.063] [error] Backend: imwrite_('C:\Users\Kim\Videos\Shadow of the Tomb Raider\Shadow of the Tomb Raider Super-Resolution 2023.11.21 - 20.46.55.54-new.webp'): can't write data: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\grfmt_webp.cpp:306: error: (-215:Assertion failed) size > 0 in function 'cv::WebPEncoder::write'

It will then "finish" the chain as if it completed successfully.

**Logs**
(nothing relevant other than what's posted above)

**Comment by RunDevelopment** [comment]
Do you have an image with which I can reproduce this?

**Comment by Kim2091** [comment]
Just any image. I don't remember any particular one I used for that test, but I tried many before posting

**Comment by RunDevelopment** [comment]
Then I can't reproduce this at all. Everything works for me. What is your exact `opencv-python` version? (See `pip list`.)

**Comment by Kim2091** [comment]
> Then I can't reproduce this at all. Everything works for me. What is your exact `opencv-python` version? (See `pip list`.)

I'll have to try to reproduce it again. It's possible it was inadvertently fixed in a nightly since then? I'm not sure what build you're using

**Comment by RunDevelopment** [comment]
> It's possible it was inadvertently fixed in a nightly since then?

We haven't changed anything related to Save Image and webp for a while, so it's unlikely.

> I'm not sure what build you're using

I'm always using the main branch.

**Comment by RunDevelopment** [comment]
Wdym? I don't use any specific nightly build or similar. I always just run `npm run dev` on the main branch.

**Comment by Kim2091** [comment]
Can no longer reproduce it on my end. It was likely a bug with my install, I've updated many times since
