### ISSUE TITLE
Error occurred in a PyTorch Upscale Image node:

### ISSUE THREAD

**Issue by demoniack88** [chaiNNer-org/chaiNNer#2346]
When I want to launch my upscal I get this error, reinstalling 3 times nothing helps.
Good morning
At home it is impossible to make it work, I have:
Error
An error occurred in a PyTorch Upscale Image node:
cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
Input values:
• Image: 1024 x 1024 RGB image
• Model: value of type 'nodes.impl.pytorch.architecture.RRDB.RRDBNet'
• Tile size: Auto (estimate)
• Separate Alpha: No

**Information:**

- 
![01](https://github.com/chaiNNer-org/chaiNNer/assets/98156371/69c19012-2c4f-4de0-9bd3-80b5883d367a)
chaiNNer-windows-x64-0.20.2
- OS: [e.g. Windows 10,

**Comment by demoniack88** [comment]
Good morning thank you for the feedback, I have 4gb of ram.

Le mer. 29 nov. 2023 à 04:04, Joey Ballentine ***@***.***> a
écrit :

**Comment by joeyballentine** [comment]
4GB of RAM will not be not enough to do any meaningful work in chaiNNer unfortunately. But, if you want to continue, you could enable hardware acceleration in the settings (to offload UI rendering to your GPU) and use CPU for upscaling. Though you'll probably quickly hit an out-of-memory error
