### ISSUE TITLE
Uninstalling chaiNNer does not remove appdata files

### ISSUE THREAD

**Issue by Kim2091** [chaiNNer-org/chaiNNer#2347]
I recently uninstalled chaiNNer to diagnose some issues, and noticed that uninstalling it does not actually clear python, the dependencies, etc. stored in the AppData directory. I had to manually delete these to reinstall chaiNNer fully.

**Comment by joeyballentine** [comment]
Oof, that's definitely an issue... I think i know what i can do to fix that. I think squirrel has hooks for where you can run things on uninstall -- so i might be able to get it to clear the python folder out when that happens. Amazingly, i don't think i've ever actually even tried uninstalling chaiNNer lol

**Comment by ipeevski** [comment]
On linux, the directory is `$HOME/.config/chaiNNer`
It's north of 5Gb after uninstall ...

**Comment by ipeevski** [comment]
The patch doesn't seem to cater for linux installs?!

**Comment by joeyballentine** [comment]
I believe we only have the ability to hook into the windows installer. Nothing we can do for linux afaik

**Comment by ipeevski** [comment]
What about just `rm`?
The above two directories would be a great start.

**Comment by RunDevelopment** [comment]
The original issue was only about windows. I made a new issue for Linux #2751.

> What about just rm?

The problem isn't which command to use to remove files, but how we can run our code/commands during the uninstallation process. Electron's (un)installer for windows gives us an easy way to hook into the installation process, but we'll have to investigate how that works for Linux.
