### ISSUE TITLE
FBCNN: 'tuple' object has no attribute 'detach'

### ISSUE THREAD

**Issue by soldivelot** [chaiNNer-org/chaiNNer#2362]
when i try FBCNN model with latest nightly build (v0.20.3-nightly.2023-11-30) i got this error

```
Error

An error occurred in a Upscale Image node:

'tuple' object has no attribute 'detach'

Input values:
• Image: RGB Image 481x321
• Model: Value of type 'spandrel.__helpers.model_descriptor.ImageModelDescriptor'
• Tile Size: Auto (estimate)
• Separate Alpha: No
```

workflow

<img width="645" alt="屏幕截图 2023-12-02 032339" src="https://github.com/chaiNNer-org/chaiNNer/assets/84898012/f803f20e-7409-48fa-9385-09ed92d16383">

**Comment by joeyballentine** [comment]
With the merger of #2359 this should be fixed in tonight's nightly
