### ISSUE TITLE
ONNX inference does not work with CUDA 12

### ISSUE THREAD

**Issue by adegerard** [chaiNNer-org/chaiNNer#2416]
Exception occurs when upscaling an image with onnxruntime_gpu if execution provider is either CUDA or TensorRT.
This is a known issue because CUDA 12 it is not yet supported.
[Requirements for TensorRT execution provider](https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#requirements)
[ONNX runtime roadmap](https://github.com/microsoft/onnxruntime/wiki/Upcoming-Release-Roadmap)

**Comment by joeyballentine** [comment]
Ah this explains why it's stopped working for me... Thanks for reporting, I'll make sure to update onnx once that's supported

**Comment by RunDevelopment** [comment]
Fixed bx #2717
