### ISSUE TITLE
Masking Out images from a given mask

### ISSUE THREAD

**Issue by Lusbert** [chaiNNer-org/chaiNNer#2421]
**Motivation**
I often want to separate the background and the person, but when i have the mask of the person i don't have one from the background.

**Description**
For example i input a mask of the person, and then the original image
then i want it to remove the person from the image and give me the background

## original image
![original](https://github.com/chaiNNer-org/chaiNNer/assets/118057562/2c911777-b0e4-42a4-92e4-267dfcf143bb)
## removed background
![mask](https://github.com/chaiNNer-org/chaiNNer/assets/118057562/affb1945-5267-4656-9483-429cdf209031)

then i want to input the removed background and then separate the background as well

## Masking Out the person
![maskedOut](https://github.com/chaiNNer-org/chaiNNer/assets/118057562/74b11275-48a1-4526-8ff6-d01b20106070)

**Comment by RunDevelopment** [comment]
Use the Merge Transparency node. Convert your mask to grayscale with the Change Colorspace node, and pass the grayscale mask into the Alpha input of Merge Transparency. Depending on which parts of your mask are black, you might also have to invert the mask with the Invert Color node.

**Comment by Lusbert** [comment]
oh thanks, sorry i didn't know the Merge Transparency could do that 🙏

**Comment by RunDevelopment** [comment]
No worries. Since Merge Transparency seems to have worked for you, I'll consider this issue closed now.
