### ISSUE TITLE
something like hsv noise like in gimp 

### ISSUE THREAD

**Issue by agentduckman12** [chaiNNer-org/chaiNNer#2426]
something like this where it keeps the colors 
![image](https://github.com/chaiNNer-org/chaiNNer/assets/64278832/f6f38759-5abd-4d59-bf27-d22b02573f6a)

**Comment by RunDevelopment** [comment]
You can already do that with the Change Colorspace node. Basically, you have to convert the image to HSV (stored as R=H, G=S, B=V), apply the noise, and then convert it back to RGB. Like this:

![image](https://github.com/chaiNNer-org/chaiNNer/assets/20878432/b17ad494-f2f7-4dc9-ad94-b10146093748)
