### ISSUE TITLE
How to use in colab?

### ISSUE THREAD

**Issue by wolfkingal2000** [chaiNNer-org/chaiNNer#2431]
How to make colab for thes software or give me link  of colab notebook working thanks

**Comment by joeyballentine** [comment]
ChaiNNer is not really meant to be used in colab. It is a GUI meant to be used on a regular computer.

However, we do have an experimental CLI mode you can try using. It's just not the most user friendly feature.

https://github.com/chaiNNer-org/chaiNNer/blob/main/docs%2Fcli.md
