### ISSUE TITLE
Model 4xUltrasharp_4xUltrasharpV10.pt is unsupported by chaiNNer. 

### ISSUE THREAD

**Issue by tralala87** [chaiNNer-org/chaiNNer#2436]
Model 4xUltrasharp_4xUltrasharpV10.pt is unsupported by chaiNNer.

**Comment by joeyballentine** [comment]
Could you please link to the model in question? I'm not familiar with it

**Comment by tralala87** [comment]
https://civitai.com/models/116225/4x-ultrasharp

**Comment by joeyballentine** [comment]
I'll see if I can figure out what's wrong with it and report back. For now though just get it from here: https://openmodeldb.info/models/4x-UltraSharp
