### ISSUE TITLE
Unable to use Scunet due to a tiling isssue

### ISSUE THREAD

**Issue by jonathancolledge** [chaiNNer-org/chaiNNer#2438]
I can't seem to denoise with Scunet

Please can you help?

I have attached my logs and and my workflow
[ChaiNNer template.zip](https://github.com/chaiNNer-org/chaiNNer/files/13848436/ChaiNNer.template.zip)

**Information:**

- Chainner version: 20.2
- OS: Windows 10

**Description**
Error

An error occurred in a PyTorch Upscale Image node:

Image cannot be upscale with No Tiling mode.

Input values:
• Image: RGB Image 7136x5263
• Model: Value of type 'nodes.impl.pytorch.architecture.SCUNet.SCUNet'
• Tile Size: Auto (estimate)
• Separate Alpha: No

[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/13848430/logs.zip)

**Comment by theflyingzamboni** [comment]
Your image is too large to process without tiling.

**Comment by joeyballentine** [comment]
Use the nightly version and use tiling https://github.com/chaiNNer-org/chaiNNer-nightly

**Comment by jonathancolledge** [comment]
> Use the nightly version and use tiling https://github.com/chaiNNer-org/chaiNNer-nightly

Thank you. I have downloaded the exe, but given I have very flakey internet, where does it download the dependencies to? If I install pytorch, etc, where does that live? Currently trying to download them now but that requires quitting multiple times till I get a connection that downloads it all quick enough not to stop and hang.

**Comment by jonathancolledge** [comment]
Thank you both. I'll close this, assuming I can get the download of pyotrch not to hang.

**Comment by joeyballentine** [comment]
> where does that live?

`C://Users/[your user]/AppData/Roaming/chaiNNer/python`
