### ISSUE TITLE
Add "open in external terminal" option for installing dependencies

### ISSUE THREAD

**Issue by joeyballentine** [chaiNNer-org/chaiNNer#2447]
Some people experience issues with the current dependency install process. Instead of having the "use pip directly" option, we should have a "use external terminal" option or a button or something, that would open an external terminal with the install command, so that the user can see the pip progress bar and verify that everything works outside of chaiNNer.

Mostly, I just would like to not have to direct people on where to find the integrated python location in order to do this all manually.

**Comment by RunDevelopment** [comment]
What's the motivation for this?

**Comment by joeyballentine** [comment]
1. The current "use pip directly option" doesn't show progress. If it was run in a separate terminal it would and there would be less confusion around that 
2. Every once in a while someone runs into issues with the internal installs and I end up walking them through finding the python exe and running the command manually. This would just automate/simplify that

**Comment by joeyballentine** [comment]
Update: I don't think this is even possible. Maybe it is, but I can't figure out how to get a separate terminal window to open....

**Comment by joeyballentine** [comment]
I've got it: Instead of opening a terminal with the command, we could have a "copy command to keyboard" button
