### ISSUE TITLE
WebUI for chaiNNer

### ISSUE THREAD

**Issue by eblis88** [chaiNNer-org/chaiNNer#2454]
Dear developper:
    Would you provide a web-ui version of chaiNNer?
    How long will it take approximately if it would be released?

**Comment by RunDevelopment** [comment]
Since chaiNNer heavily relies on its python backend, a WebUI version of chaiNNer is currently impossible until support remote backend (#1875).

**Comment by joeyballentine** [comment]
We do not provide a webui, and probably will not be due to how integrated we are with electron at this point.

**Comment by joeyballentine** [comment]
@RunDevelopment I believe they mean like the stable diffusion webui where it still runs locally, but opens up in a browser rather than in an electron window. At least, that's the way I interpreted it

**Comment by RunDevelopment** [comment]
Oh. I guess that makes it more possible.

> due to how integrated we are with electron at this point

As I see it, most of that integration is due to missing abstractions in the frontend. We aren't actually very dependent on Electron, we just currently use its API directly because it's easier.

**Comment by eblis88** [comment]
What I need is running chinner on my linux server, connet it through web service, just like comfyUI or stablediffusion-webui.
Now I know that it probably impossible now.

I would try with remote desktop now.
Thankss at all.
