### ISSUE TITLE
I can't start the ChaiNNer with ROCM.

### ISSUE THREAD

**Issue by Loganavter** [chaiNNer-org/chaiNNer#2466]
**Information:**
- Chainner version: 0.21.1
- OS: Arch linux

**Description**
I created my venv in the Chainer folder and installed there the versions of torch, torch vision and torchaudio supported by my RX 6600 video card. The check for CUDA is successful, and I have already launched stable diffusion in this configuration and even krita ai diffusion. However, I can't start the Chainer, an error appears:
/home/jorj/Загрузки/chaiNNer-linux-x64/resources/src/venv/lib/python3.11/site-packages/torch/cuda/__init__.py:546 : UserWarning: Can't initialize NVML
warnings.warn("Can't initialize NVML")
apparently this is due to the fact that this was not entirely provided for in the script gpu.py

**Logs**
pip list - https://pastebin.com/5L6DKEi4
torch cuda test - https://pastebin.com/kuUytnu0
launching server.py - https://pastebin.com/bzRsyF6j

**Comment by joeyballentine** [comment]
> python3.11/site-packages/torch/cuda/init.py

This means the issue is with torch, not our gpu.py file. Torch also uses NVML to initialize cuda stuff.

In chaiNNer, are you sure you have set your custom system python path correctly? by default, chaiNNer uses its own integrated python venv, and you have to manually enable and select a different one if you want to use it.

@Kim2091 got ROCM working just yesterday, so it definitely works under normal circumstances

**Comment by Loganavter** [comment]
> @Loganavter An issue I ran into when utilizing ROCM was that I had to manually set up the AMDGPU driver using amdgpu-install. If I were you, I'd ensure ROCM is actually functional on your system using rocminfo. If you get an error while running this, chances are it's not set up properly. In that case, [this tutorial](https://www.youtube.com/watch?v=QEbI6v2oPvQ) was helpful for me, along with [this](https://www.reddit.com/r/StableDiffusion/comments/10zfnlj/novice_guide_how_to_fully_setup_linux_to_run/).

rocminfo - https://pastebin.com/6HwpSgjd
And how do you run chainner with rocm?

**Comment by Kim2091** [comment]
That output looks okay to me. I went into chaiNNer's python environment (get to it by opening the logs folder from Help->Logs, then go up a directory and enter the python folders), and ran:
`./python -m pip uninstall torch torchvision torchaudio`

I then ran the latest rocm install command from Pytorch's website. In my case, that was:
`./python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.6`

**Comment by Loganavter** [comment]
> That output looks okay to me. I went into chaiNNer's python environment (get to it by opening the logs folder from Help->Logs, then go up a directory and enter the python folders), and ran: `./python -m pip uninstall torch torchvision torchaudio`
> 
> I then ran the latest rocm install command from Pytorch's website. In my case, that was: `./python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.6`

to be honest, I don't understand how you were able to log into this venv, and there is nowhere to activate the python file.

**Comment by Kim2091** [comment]
I just found the directory with the `python` file in it, and just used it directly

**Comment by Loganavter** [comment]
> I just found the directory with the `python` file in it, and just used it directly

in short, it doesn't work that way for me, but I got out of it in a different way. I just created another standard venv next to it, installed the necessary versions of torch, torchvision and torchaudio there, and then just copied them into this strange venv from ChaiNNer. And I started ChaiNNer with this command 
`HSA_OVERRIDE_GFX_VERSION=10.3.0 LD_PRELOAD=libtcmalloc.so.4 ./ChaiNNer`
