### ISSUE TITLE
Edge filter node

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#2497]
**Motivation**
Edge detection is a pretty fundamental image operation, so we should support it.

**Description**
Implement an edge detection filter. Ideally, we could implement all of Gimp's edge detect filters.

![image](https://github.com/chaiNNer-org/chaiNNer/assets/20878432/f9c903fa-2082-4afa-a475-24a3403bf824)

**Comment by joeyballentine** [comment]
Don't we already have this? 
![image](https://github.com/chaiNNer-org/chaiNNer/assets/34788790/9ecb78e3-5124-4d1e-91bd-47a984fcd841)

**Comment by RunDevelopment** [comment]
Canny is very different from these Gimp filters.
