### ISSUE TITLE
Load and save GIF videos

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#2501]
PIL supports saving sequences of images as GIF and WebP. It would be nice to be able to create animated GIFs with chainner.

https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#gif-saving

**Comment by joeyballentine** [comment]
We can already create gifs with chaiNNer. The save video node has a gif option

**Comment by RunDevelopment** [comment]
> The save video node has a gif option

No it doesn't. There is no encoder that makes the GIF container available.

**Comment by joeyballentine** [comment]
What the hell, then we had a breaking change at some point because that used to be an option.
