### ISSUE TITLE
Perform a similarity check + inference test after converting to onnx

### ISSUE THREAD

**Issue by joeyballentine** [chaiNNer-org/chaiNNer#2585]
The main con of this would be that then onnx inference would be required for conversion. Maybe it could just be an optional thing if onnx is installed.

Why is this necessary? According to musl:

> [Check] If the converted onnx is relatively close to the outputs of pytorch inference. This is not strictly necessary, but the [documentation recommends it](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html) (np.testing.assert_allclose). It obviously won't change the model, but I found some situations where the converted onnx gave like 20% difference between pytorch and onnx, which should not be acceptable. So if this is not tested with assert_allclose, the outputs could be bad while still exporting just fine.

**Comment by Kim2091** [comment]
Is there any update on this? It'd be great to have. Some users exclusively use neosr's onnx conversion script now as it verifies conversion whereas chaiNNer does not

**Comment by RunDevelopment** [comment]
https://github.com/muslll/neosr/blob/d871e468fa9e82dc874f65b2289ad5726a5ab3b9/convert.py#L61

This is neosr's conversion btw. Should be easy to implement a similar check.
