### ISSUE TITLE
Load Video and Save Video connections trouble

### ISSUE THREAD

**Issue by bradleysepos** [chaiNNer-org/chaiNNer#2601]
**Information:**

- Chainner version: 0.22.0
- OS: Windows 10

**Description**

#2494 solved some lineage issues with connections I was having with numbers/math/iterators, so thank you for that. I have another case that seems like it should work, but does not.

Load Image and Load Images can be connected to a Switch. So can Load Image and Load Video. However, Load Images and Load Video cannot be connected. Naturally, this makes it impossible to have a Switch that handles all three input possibilities.

![chainner-check-assigned-lineage-0](https://github.com/chaiNNer-org/chaiNNer/assets/70239/5ffc3eec-8452-4a57-ac9d-3683699126dd)

**Comment by bradleysepos** [comment]
Found a similar issue with Save Video and appending image dimensions to the name. I'm doing something similar with Save Image without any issue.

![chainner-check-assigned-lineage-1](https://github.com/chaiNNer-org/chaiNNer/assets/70239/a1a2f1bf-90c5-428e-97a4-c244f5b2e79c)

I also notice Save Video does not have a Subdirectory field, which would be useful.

Anyway, it seems Load Video / Save Video might need a little help when someone has the time. Cheers.

**Comment by joeyballentine** [comment]
Technically if we separated the loading of the video and the iterating of the frames into separate nodes, we could then have a node that gets the dimensions and other metadata of the video that would be able to run before iteration starts

**Comment by bradleysepos** [comment]
Thanks for the comments. Some video formats can actually vary frame size throughout a stream, for what it's worth. It's actually very common to vary frame rate but that's a whole other can of worms.

**Comment by RunDevelopment** [comment]
I made an issue to track progress on a First node (#2761) and an issue to track the issue with Switch (#2762).

Since this issue isn't a problem with Load/Save Video, I'm going to close this issue now.
