### ISSUE TITLE
Support for Indexed Color images

### ISSUE THREAD

**Issue by SecretX33** [chaiNNer-org/chaiNNer#2620]
**Information:**

- Chainner version: v0.22.0
- OS: Windows 10

**Description**

I was trying to process some of my images, but for some reason, one of them turns dark as soon as it's processed, and it doesn't matter which image format I try to use, the output image always becomes pitch black.

Upon opening the image on Photoshop, I discovered that this image is using something called "Indexed Color", which I think chaiNNer isn't equipped to handle ATM.

Here's a quick preview of what is happening:

![results](https://github.com/chaiNNer-org/chaiNNer/assets/4389757/3f706480-fafb-4354-a242-c258e79159ef)
_On the left we see the "input" image, and on the right we see the "output" of the pipeline._

![Photoshop_Skia2lhaYI](https://github.com/chaiNNer-org/chaiNNer/assets/4389757/a4e56e0a-c95c-4de0-9e3b-53976d6b3661)
_Photoshop dialog showing that the image is using "Indexed Color"._

This is the pipeline I'm using to test:

![chaiNNer_f231xgYq2J](https://github.com/chaiNNer-org/chaiNNer/assets/4389757/d28287b3-b7d4-4244-9c01-fc3fd939dd86)
_The entire pipeline, "read from the folder, convert it to PNG then save it"._

**Logs**

Apparently, there are no errors on the log.

[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/14413100/logs.zip)

**Download images**

Here's the ZIP with the input and output images: [images.zip](https://github.com/chaiNNer-org/chaiNNer/files/14412968/images.zip)

**Comment by joeyballentine** [comment]
chaiNNer can definitely read indexed images properly, I've loaded plenty of them before.

That being said, something funky is definitely happening to these images, almost like they're being automatically inverted. We'll look into it.
