### ISSUE TITLE
Text Append Full Support of all Text Sources

### ISSUE THREAD

**Issue by Codinablack** [chaiNNer-org/chaiNNer#2621]
**Motivation**
I want to iterate over many upscale models and compare the results. While outputting the images, it would be useful to write into the name the model that was used to produce each image, but at the same time I will be doing this with multiple images as well. So to create an appropriate name I would need the name of the image **and** the name of the model used to upscale it. One would expect to be able to combine both names with the "Text Append" node as that seems to be its only job, is to combine text.

**Description**

The node should work as expected out of the box. 

Example. Say in my image folder I have 15 images each named by the subject and a number. bannana01, bannana02, bannana03, ect. Then say in my models folder I have 4 different models, 4xEsrgan, 4xRealEsrGan, 4xHat, ect.

When using the text append, while iterating through the models and the images I should get outputs like "4xEsrgan-bannana01" and "4xHat-bannana03" ect. 

The problem is when trying to use text from two separate nodes it is not possible, please see attachment:
![image](https://github.com/chaiNNer-org/chaiNNer/assets/8696596/7810a25b-5907-45a3-ab38-270952773354)

I would expect that the entire reason for having this node would be for situations like this, yet it doesn't seem to support this situation.

**Comment by joeyballentine** [comment]
ChaiNNer doesn't currently support mixing iterators/sequences together. So, this is not a text append problem, but rather chaiNNer not letting you iterate over both a folder of models and a folder of images at the same time.

This is planned, but will take significant dev work to accomplish. So, it probably will not be a feature any time soon.
