### ISSUE TITLE
Load Models Node doesn't do anything

### ISSUE THREAD

**Issue by Codinablack** [chaiNNer-org/chaiNNer#2622]
**Information:**

- Chainner version: [e 0.22.0]
- OS: [e.g. Windows 10]

**Description**
Using any node named "Load Models" with other nodes that are already connected to a different node seems to give the error "Unable to connect" with the description being "Cannot connect node to 2 sequences that don't share the same source node"

If you see in my pictures, loading a single model, and a batch of images works just fine, or loading a batch of models and connecting to "upscale image" node will work, but then im unable to connect a valid image input.

![image](https://github.com/chaiNNer-org/chaiNNer/assets/8696596/4dbace89-0639-498f-8af1-b19222e9fa3b)

I had this same issue with text append. I don't get it. Was this all intentional to keep someone from doing a batch of models on a batch of images?

**Comment by joeyballentine** [comment]
Please read the reply i posted to your last issue, as this is for the same reason: https://github.com/chaiNNer-org/chaiNNer/issues/2621#issuecomment-1968243393
