### ISSUE TITLE
App is failing to download pytorch

### ISSUE THREAD

**Issue by lavadrop** [chaiNNer-org/chaiNNer#2626]
**Information:**

- Chainner version: 0.22.1
- OS: Linux AppImage

**Description**
Chainner is stuck downloading pytorch, specifically it's stuck downloading https://files.pythonhosted.org/packages/36/7b/2147339dafe1c4800514c9c21ee4444f8b419ce51dfc7695220a8e0069a6/facexlib-0.3.0-py3-none-any.whl.metadata

[Chainner_logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/14439650/Chainner_logs.zip)

**Comment by joeyballentine** [comment]
Try restarting chaiNNer and trying again. If that doesn't work, switch the install mode to direct pip, and if that doesn't work, change it to manual/copy and then paste the command into a terminal

**Comment by RunDevelopment** [comment]
Since there was no follow up, I'm going to assume the issue was resolved.
