### ISSUE TITLE
Unable to convert PyTorch ESRGAN model to NCNN model on the latest version

### ISSUE THREAD

**Issue by vYLQs6** [chaiNNer-org/chaiNNer#2670]
**Information:**

- Chainner version: v0.22.2
- OS: Windows 11 + RTX 4060

**Description**

Unable to convert PyTorch ESRGAN model to NCNN model on the latest version

chaiNNer will always say something is wrong with `FLT_MAX`, and only the `.bin` file will be generated, the `.param` file is missing

ALL dependency are installed, and the old version `v0.18.9 still works`, v0.18.9 can successfully convert the same model to NCNN without any issue, so I think there is something wrong with the v0.22.2 update

Here is the .pth model file, you can test it yourself, this error will occur 100%

[2xNomosUni_compact_otf_medium.zip](https://github.com/chaiNNer-org/chaiNNer/files/14558014/2xNomosUni_compact_otf_medium.zip)

I alse tested several other models, all having the same issue, but I don't think it's necessary to upload all of them to here

**Logs**

Sorry I didn't keep any log because I already installed the v0.18.9

![11](https://github.com/chaiNNer-org/chaiNNer/assets/143073604/d19ad63b-6dff-4b52-bcc4-5fd818ea4654)

**Comment by joeyballentine** [comment]
We believe this is due to the updated version of onnx we use now (it's been reported a few times now). We aren't sure exactly what changed. But there has since been another update that we haven't switched to, so I will try that version and let you know if that fixes this. If so, then we can switch to it in chaiNNer and resolve this

**Comment by RunDevelopment** [comment]
Fixed by #2684. The fix in included in all versions of chainner >= v0.23.0.
