### ISSUE TITLE
Tab UI elements can be clicked with any mouse button

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#2734]
**Description**
I found a small UI bug. Tab UI elements in nodes can be clicked with any mouse button (left, right, middle, back, etc.). This interferes with using the middle mouse button to pan the viewport of the chain editor.

**Expected Behavior**
Just like other button, tabs should react to left mouse button clicks.

---

Good example nodes to test this on are Resize, Crop, and Color From:

![image](https://github.com/chaiNNer-org/chaiNNer/assets/20878432/e5c0f2a5-b321-4eda-97ff-3cc3c05efdf2)

**Comment by RaySit** [comment]
Hello, we are CS major students from Vanderbilt University. We did reproduce the bug, finding that this would also interfere with using the right mouse button to bring out the menu. We are trying to complete a pull request for our final project. Can you assign us to this issue? Thanks!

**Comment by RunDevelopment** [comment]
Thank you for working on this @RaySit!
