### ISSUE TITLE
Consider using jpegli for encoding jpegs?

### ISSUE THREAD

**Issue by xrishox** [chaiNNer-org/chaiNNer#2744]
jpegli is a library written by google that appears to be fully jpeg compliant (which maintains compatibility with pdf and other things that only work with jpeg) while also offering a high compression ratio that you would expect from a much more recent format like avif, jpegxl or webp. it appears to offer up to a 35 percent compression ratio vs standard jpeg encoders like mozjpeg or libjpeg-turbo.

https://www.phoronix.com/news/Google-Jpegli-Library
https://opensource.googleblog.com/2024/04/introducing-jpegli-new-jpeg-coding-library.html
https://github.com/libjxl/libjxl/tree/main/lib/jpegli

**Comment by joeyballentine** [comment]
There do not appear to be python bindings or rust bindings (which we could use to make python bindings) for jpegli, so we cannot use it.

**Comment by Ki-Tan2934** [comment]
Maybe keep this open, It might be good in the future for mass image creation.

**Comment by user451421541757324** [comment]
@joeyballentine would it be possible to add support for JPEG XL through [jpegxl-rs](https://github.com/inflation/jpegxl-rs)? It's a safe (Rust) JPEG XL wrapper over libjxl library.

**Comment by user451421541757324** [comment]
> There do not appear to be python bindings or rust bindings

@joeyballentine would it be possible to add support for JPEG XL through [jpegxl-rs](https://github.com/inflation/jpegxl-rs)? It's a safe (Rust) JPEG XL wrapper over libjxl library.
