### ISSUE TITLE
NCNN convert from PyTorch: "Op Clip does not have param -FLT_MAX"

### ISSUE THREAD

**Issue by draeath** [chaiNNer-org/chaiNNer#2770]
**Information:**

- Chainner version: 0.22.2
- OS: Windows 10

**Description**
When attempting to convert [RealESR-general-x4v3.pth](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-general-x4v3.pth) to NCNN and ONNX, I receive the error message:

    Error
    
    An error occurred in a ncnn Save Model node:
    
    'Op Clip does not have param -FLT_MAX, please report'
    
    Input values:
    • Model: Value of type 'nodes.impl.ncnn.model.NcnnModelWrapper'
    • Directory: "D:\\UpscaleModels\\Real-ESRGAN\\PyTorch"
    • Param/Bin Name: "RealESR-general-x4v3"

For convenience, the graph I am using is attached:
[test-sharing.zip](https://github.com/chaiNNer-org/chaiNNer/files/14913582/test-sharing.zip)

**Logs**
[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/14913576/logs.zip)

**Comment by joeyballentine** [comment]
Hi, thanks for reporting. This has already been fixed and will be included in the next release. In the meantime, feel free to try the [nightly version](https://github.com/chaiNNer-org/chaiNNer-nightly/releases/tag/2024-04-08)
