### ISSUE TITLE
Load pytorch model

### ISSUE THREAD

**Issue by peamak** [chaiNNer-org/chaiNNer#2784]
With the latest version (0.23.0), I can't find the node to load a pytorch model… it's pretty useless without it… Everything was working fine in the previous version: did I miss something? Is the node somewhere else?

**Comment by peamak** [comment]
Yes, it told me to update Pytorch indeed after I updated ChaiNNer, which I did.

Currently in the dependency Manager:
PyTorch 2.1.2

**Comment by peamak** [comment]
OK, re-restarting it seems to work… my bad, sorry for the inconvenience.

**Comment by joeyballentine** [comment]
All good. This actually is a bug. For some reason the nodes list isn't refreshing after installing the dependencies
