### ISSUE TITLE
how to apply models other than listed types (upscale, remove bg, inpaint)

### ISSUE THREAD

**Issue by Johnreidsilver** [chaiNNer-org/chaiNNer#2811]
Hi, was trying out chaiNNer (thx btw! super simple to install in Ubuntu and excellent GUI), and it works fine with upscaling models, but what about other models like deblur, dehaze, and low light correction ? I can load them, but can't figure how to apply those.

For example:
https://github.com/VITA-Group/EnlightenGAN

This one will fail on load with a "not supported" message. I tried with an ONNX version from here:
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/214_EnlightenGAN

It doesn't throw an error loading, but I can only connect it to either upscale
```
An error occurred in a onnx Upscale Image node:

Required inputs (['gray']) are missing from input feed (['input.1']).

Input values:
• Image: RGB Image 320x230
• Model: Value of type 'nodes.impl.onnx.model.OnnxGeneric'
• Tile Size: 256
• Separate Alpha: No
```

or remove bg that doesn't let the chain to be established with subtype "generic" not connectable to subtype "RemBg"

Do you plan to add support for this kind of "filtering" models or is it out of scope of chaiNNer ?

**Comment by joeyballentine** [comment]
The "upscale image" node for onnx is really just a "run model" node. That being said though, not every model is guaranteed to work. We only officially support models converted from pytorch to onnx or ncnn on either of those frameworks.

As for what's supported by pytorch, we have to add support for models manually. You can't just find some random code on GitHub and expect the model to work. If you want it to be supported, create an issue in the spandrel repo: https://github.com/chaiNNer-org/spandrel

Hopefully that clears things up a bit

**Comment by Johnreidsilver** [comment]
Thanks, been messing with different models and found one that works for dehazing:
https://github.com/AmeryXiong/MixDehazeNet
