### ISSUE TITLE
Issues with image file names after processing

### ISSUE THREAD

**Issue by airdmo** [chaiNNer-org/chaiNNer#2813]
![image](https://github.com/chaiNNer-org/chaiNNer/assets/58673476/8399a723-a11d-4678-bc11-f64bb86487f1)

Can the Image Name in the "SAVE IMAGE" be composed of the original file name + model name?
For example, abc_4x-ClearRealityV1.png
Currently, only choose from either the original filename or model name.

**Comment by joeyballentine** [comment]
Yes. Use the text append node.

**Comment by airdmo** [comment]
> Yes. Use the text append node.

Got it
thank you very much
