### ISSUE TITLE
Indexed Color .tga Files Treated as Grayscale

### ISSUE THREAD

**Issue by Keranos89** [chaiNNer-org/chaiNNer#2816]
**Information:**

- Chainner version: 0.23.1
- OS: Windows 10 64 bit

**Description**
It appears that Chainner doesn't load .tga files with indexed color correctly, instead treating them as grayscale.

When loaded into photoshop:
![IndexedTGA](https://github.com/chaiNNer-org/chaiNNer/assets/48656563/f70a6ec4-bb36-4924-9bd8-d76c09ffd8f0)

When loaded into Chainner:
![IndexedTGA2](https://github.com/chaiNNer-org/chaiNNer/assets/48656563/b07e44cd-45d0-440f-bb68-a88fe8ea3ba9)

And the original image:
[_rb_fs1_top4.zip](https://github.com/chaiNNer-org/chaiNNer/files/15095319/_rb_fs1_top4.zip)

**Comment by RunDevelopment** [comment]
Neither PIL nor OpenCV support this, apparently. However, [Rust's image crate](https://crates.io/crates/image) does seem to support indexed TGA's, so we can just add bindings for it
