### ISSUE TITLE
Play/Pause/Stop buttons revert and stop responding

### ISSUE THREAD

**Issue by OrloDavid** [chaiNNer-org/chaiNNer#2922]
**Information:**

- Chainner version: Alpha 0.23.3
- OS: Windows 11 & Linux Mint Latest

**Description**
The Play, Pause and Stop buttons will stop working after a period of time running a batch chain. They will also revert back to their default state, which means you can no longer even attempt to press the stop button or pause. The only solution is to reload the GUI which seems to stop the chain, but not always. Sometimes it will require the force reload option. 
I assume this may be the reason for the reload buttons, but I was if it would be possible to leave the buttons in their default state and if so, would it allow a stop or pause prior to the GUI reload? I think this would be preferable in most situations. The reasoning is that I cannot be sure the chain stopped itself on a reload without checking my running processes first. If it appears to be running, I have to first click on Play, then click on Stop, and sometimes on Play again to restart with any changes I may have made. 
This DDR button combo isn't always handled gracefully and requires checking back and forth between running processes to time everything as a workaround. 

Attached screenshot of the chain running with incorrect buttons showing.

![Screenshot 2024-05-29 013633](https://github.com/chaiNNer-org/chaiNNer/assets/26681128/ebf6cc75-9042-4c10-be50-0e121503ddef)

**Logs**
I cannot include my logs without scrubbing them first, the content I am working with is sensitive and relating to an investigation. Please DM me if you would like the scrubbed logs. 

Privacy information: Log files contain file paths of Chainner's application files and the files you processed with Chainner. These file paths may contain the name of your account (e.g. Users/michael/...). If your account is your real name, and you are not comfortable sharing, then do not upload your logs or replace all identifying text with something like "fake name".

**Comment by RunDevelopment** [comment]
My guess is that the cause of this bug is that we drop SSE events somewhere. If this guess is correct, then we can easily fix this by adding a `/status` endpoint to the server that we can pull. I would still keep the SSE events around simply so we don't have to pull `/status` too frequently.
