### ISSUE TITLE
read ~/.config/pip/pip.conf and use the mirror section

### ISSUE THREAD

**Issue by dontknowhy** [chaiNNer-org/chaiNNer#2926]
As for Chinese user, you basically need a mirror to download every PyPI packages.
But `chainner_pip` won't read ~/.config/pip/pip.conf and use the default [pypi.org](pypi.org) which is quite slow(20KB/s and often lose connection).
I hope there is an option to change pip's mirror.(It uses ~/.config/chainner_pip/chainner_pip.conf now).

**Comment by joeyballentine** [comment]
Can't you just copy and rename your current config to the spot and filename that it currently uses?

**Comment by dontknowhy** [comment]
> Can't you just copy and rename your current config to the spot and filename that it currently uses?

Yes I did.
And it works.
But I think it's good to have this feature since not everyone can surf the Internet freely.

**Comment by joeyballentine** [comment]
Assuming pip actually updated with the change, they now support outputting download progress, so really I should just switch back to using regular pip and get rid of my custom one

**Comment by dontknowhy** [comment]
> Assuming pip actually updated with the change, they now support outputting download progress, so really I should just switch back to using regular pip and get rid of my custom one

Probably you just need to use virtual environment instead of building another python 3.11.

**Comment by joeyballentine** [comment]
Virtual environments assume the user has python installed already, which is an assumption I don't want to make as chaiNNer is intended for general use. 

That also has nothing to do with this issue. I forked and customized pip because it was lacking a feature I needed that they refused to merge. Now that they have merged that change (done slightly differently by someone else) I can just go back to using regular pip. I just have not done so because I haven't had a reason to do that yet since from my perspective my fork was working just fine.

**Comment by dontknowhy** [comment]
> Assuming pip actually updated with the change, they now support outputting download progress, so really I should just switch back to using regular pip and get rid of my custom one

Should I mention that `OpenVINOExecutionProvider` thinks running things on CPU is really reliable and it's the default option?

> _Note that the releases from (ORT 1.10) will require explicitly setting the providers parameter if you want to use execution providers other than the default CPU provider (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession._

https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html#python-api
Probably we can add an GUI option to change the `device_type`. But I don't want to open another issue to disturb developers like you.

**Comment by joeyballentine** [comment]
I don't recall us ever adding explicit support for OpenVINO so I'm not sure why that would be showing up, unless you switched to using your system python and you had that already installed or manually installed it. In that case, there probably is just an extra step we'd need to do in order to more properly support it.

**Comment by dontknowhy** [comment]
> I don't recall us ever adding explicit support for OpenVINO so I'm not sure why that would be showing up, unless you switched to using your system python and you had that already installed or manually installed it. In that case, there probably is just an extra step we'd need to do in order to more properly support it.

Unless chaiNner will detect ExcutionProvider and I installed `onnxruntime-openvino`.
I'm sorry but it looks like `onnxruntime-openvino` is the only third-party ExcutionProvider that uses CPU by default.
I tried to add some `provider_option` in `nodes/impl/onnx/session.py` but it still wants to use CPU and it's really slow.

**Comment by joeyballentine** [comment]
> Unless chaiNner will detect ExcutionProvider and I installed onnxruntime-openvino

That's probably what happened. It detects the available execution providers automatically. You can change what device it targets in the settings. If you installed the CUDA one it should be able to use your GPU

**Comment by dontknowhy** [comment]
> > Unless chaiNner will detect ExcutionProvider and I installed onnxruntime-openvino
> 
> That's probably what happened. It detects the available execution providers automatically. You can change what device it targets in the settings. If you installed the CUDA one it should be able to use your GPU

Good news:I managed to use OpenVINO in GPU mode.
Bad news:This thing is very hungry and eat about 10G of **VIDEO** memory.And I don't know if it faster than CPU mode.(Intel Alderlake_p (Gen12))（Even in half presision mode)

**Comment by dontknowhy** [comment]
> > Unless chaiNner will detect ExcutionProvider and I installed onnxruntime-openvino
> 
> That's probably what happened. It detects the available execution providers automatically. You can change what device it targets in the settings. If you installed the CUDA one it should be able to use your GPU

Good news:I managed to use OpenVINO in GPU mode.
Bad news:This thing is very hungry and eat about 10G of **VIDEO** memory.And I don't know if it faster than CPU mode.(Intel Alderlake_p (Gen12))（Even in half presision mode)

**Comment by dontknowhy** [comment]
> > Unless chaiNner will detect ExcutionProvider and I installed onnxruntime-openvino
> 
> That's probably what happened. It detects the available execution providers automatically. You can change what device it targets in the settings. If you installed the CUDA one it should be able to use your GPU

Good news:I managed to use OpenVINO in GPU mode.
Bad news:This thing is very hungry and eat about 10G of **VIDEO** memory.And I don't know if it faster than CPU mode.(Intel Alderlake_p (Gen12))（Even in half presision mode)

**Comment by dontknowhy** [comment]
> > Unless chaiNner will detect ExcutionProvider and I installed onnxruntime-openvino
> 
> That's probably what happened. It detects the available execution providers automatically. You can change what device it targets in the settings. If you installed the CUDA one it should be able to use your GPU

Good news:I managed to use OpenVINO in GPU mode.
Bad news:This thing is very hungry and eat about 10G of **VIDEO** memory.And I don't know if it faster than CPU mode.(Intel Alderlake_p (Gen12))（Even in half presision mode)

**Comment by dontknowhy** [comment]
There is still some issue when upscaling image using ncnn（both latest git version and pip version).
The output image has a resonable file size but always blank.
Tried reconvert models or using different models(already converted).
`realesr-ncnn-vulkan` can run properly(modified to compile with latest git version).

**Comment by joeyballentine** [comment]
Are you sure you're using ncnn_vulkan and not the regular NCNN package? Also, what GPU do you have?

**Comment by dontknowhy** [comment]
> Are you sure you're using ncnn_vulkan and not the regular NCNN package? Also, what GPU do you have?

I'm sure I'm using `ncnn_vulkan` and chaiNNer's python environment doesn't have `ncnn` package.
![image](https://github.com/chaiNNer-org/chaiNNer/assets/85813508/e07f500c-0d42-4f81-83c2-233207806a51)
![image](https://github.com/chaiNNer-org/chaiNNer/assets/85813508/a5ed6380-81ef-4d60-b483-64b0f15d9600)
Also, I switched to system's python's virtual environment.
If you cares about the output:
![image](https://github.com/chaiNNer-org/chaiNNer/assets/85813508/10f67967-5bcb-4e5e-aa32-1b4eb95a26ce)
I recompiled `ncnn_vulkan` because my driver only wants to run ncnn that compiled in a same machine.
The original version from pip won't work either:
![image](https://github.com/chaiNNer-org/chaiNNer/assets/85813508/e3c82cc7-78f2-4a6d-98c0-c8603eaa6a63)

**Comment by joeyballentine** [comment]
Yeah that's really weird -- I'm not sure why that would be happening, so I also don't know what I could potentially do to fix it unfortunately

**Comment by dontknowhy** [comment]
> Yeah that's really weird -- I'm not sure why that would be happening, so I also don't know what I could potentially do to fix it unfortunately

Can we just invoke a native binary like [Real-ESRGAN-ncnn-vulkan](https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan) or third-party py bindings（but it will increase the chance to have dependency issue and we need to install many packages）?
If all models can work with vallina ncnn,there won't be any special program to run these upscale models.

**Comment by dontknowhy** [comment]
I tested the original RealESRGAN-x4plus model and it doesn't work either

**Comment by dontknowhy** [comment]
Closing this issue because it is now off topic.
Opening another issue to start a new topic :(
