### ISSUE TITLE
Errors during Onnx inference

### ISSUE THREAD

**Issue by zelenooki87** [chaiNNer-org/chaiNNer#2939]
tried different onnx models on random image sizes.
for example. 640x480 runs fine 800x600 throws error... and so on...
`An error occurred in a onnx Upscale Image node:

[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Concat node. Name:'Concat_39' Status Message: concat.cc:157 onnxruntime::ConcatBase::PrepareForCompute Non concat axis dimensions must match: Axis 2 has mismatched dimensions of 680 and 681

Input values:
• Image: RGB Image 2048x1362
• Model: Value of type 'nodes.impl.onnx.model.OnnxGeneric'
• Tile Size: No Tiling
• Custom Tile Size: 256px
• Separate Alpha: No`

```py
Traceback (most recent call last):
  File "C:\Users\Miki\chaiNNer-windows-x64STABLE-0.23.3-portable\resources\src\process.py", line 174, in run_node
    raw_output = node.run(context, *enforced_inputs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miki\chaiNNer-windows-x64STABLE-0.23.3-portable\resources\src\packages\chaiNNer_onnx\onnx\processing\upscale_image.py", line 140, in upscale_image_node
    return convenient_upscale(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miki\chaiNNer-windows-x64STABLE-0.23.3-portable\resources\src\nodes\impl\upscale\convenient_upscale.py", line 58, in convenient_upscale
    return upscale(img)
           ^^^^^^^^^^^^
  File "C:\Users\Miki\chaiNNer-windows-x64STABLE-0.23.3-portable\resources\src\nodes\impl\image_op.py", line 18, in <lambda>
    return lambda i: np.clip(op(i), 0, 1)
                             ^^^^^
  File "C:\Users\Miki\chaiNNer-windows-x64STABLE-0.23.3-portable\resources\src\packages\chaiNNer_onnx\onnx\processing\upscale_image.py", line 144, in <lambda>
    lambda i: upscale(
              ^^^^^^^^
  File "C:\Users\Miki\chaiNNer-windows-x64STABLE-0.23.3-portable\resources\src\packages\chaiNNer_onnx\onnx\processing\upscale_image.py", line 52, in upscale
    return onnx_auto_split(img, session, change_shape=change_shape, tiler=tiler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miki\chaiNNer-windows-x64STABLE-0.23.3-portable\resources\src\nodes\impl\onnx\auto_split.py", line 103, in onnx_auto_split
    return auto_split(img, upscale, tiler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miki\chaiNNer-windows-x64STABLE-0.23.3-portable\resources\src\nodes\impl\upscale\auto_split.py", line 45, in auto_split
    return split(
           ^^^^^^
  File "C:\Users\Miki\chaiNNer-windows-x64STABLE-0.23.3-portable\resources\src\nodes\impl\upscale\auto_split.py", line 117, in _max_split
    upscale_result = upscale(img, img_region)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miki\chaiNNer-windows-x64STABLE-0.23.3-portable\resources\src\nodes\impl\onnx\auto_split.py", line 84, in upscale
    output: np.ndarray = session.run([output_name], {input_name: lr_img})[0]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miki\chaiNNer-windows-x64STABLE-0.23.3-portable\python\python\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Concat node. Name:'Concat_39' Status Message: concat.cc:157 onnxruntime::ConcatBase::PrepareForCompute Non concat axis dimensions must match: Axis 2 has mismatched dimensions of 680 and 681
```

same behaviour in nightly and stable.

**Comment by zelenooki87** [comment]
same error I got in manually inferencing onnx model, and not only in chainner.
Gemini Pro solved error for me, there are need to bee some extra lines for inference onnx model with non standard dimensions. It would be great if you could include solution like this in Chainner to natively inference images of all sizes.
If you do not beleve me that chainner does not inference in onnx runtime, with random images size, i will send you examples.

`import argparse
import cv2
import glob
import numpy as np
import os
import onnxruntime

from drct.archs.DRCT_arch import DRCT  # Pretpostavka: DRCT klasa je dostupna

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--model_path',
        type=str,
        default='model.onnx',  # Putanja do ONNX modela
        help='Putanja do ONNX modela'
    )
    parser.add_argument('--input', type=str, default='input', help='Ulazni folder sa slikama')
    parser.add_argument('--output', type=str, default='output', help='Izlazni folder')
    parser.add_argument('--scale', type=int, default=4, help='Faktor skaliranja: 1, 2, 3, 4')
    parser.add_argument('--tile', type=int, default=1000, help='Veličina pločice, None za obradu cele slike')
    parser.add_argument('--tile_overlap', type=int, default=32, help='Preklapanje pločica')
    args = parser.parse_args()

    # Definisanje dostupnih provajdera - forsiranje CUDA Execution Providera
    providers = ['CUDAExecutionProvider']

    # Učitavanje ONNX modela sa odabranim provajderima
    ort_session = onnxruntime.InferenceSession(args.model_path, providers=providers)

    # Postavljanje input imena
    input_name = ort_session.get_inputs()[0].name

    os.makedirs(args.output, exist_ok=True)
    for idx, path in enumerate(sorted(glob.glob(os.path.join(args.input, '*')))):
        imgname = os.path.splitext(os.path.basename(path))[0]
        print('Testing', idx, imgname)

        # Učitavanje slike
        img = cv2.imread(path, cv2.IMREAD_COLOR).astype(np.float32) / 255.
        original_height, original_width = img.shape[:2]

        # Inicijalizacija izlazne slike
        output_shape = (original_height * args.scale, original_width * args.scale, 3)
        output_img = np.zeros(output_shape, dtype=np.float32)

        # Tiling
        tile_size = args.tile
        tile_overlap = args.tile_overlap
        if tile_size is None:
            tile_size = max(original_height, original_width)

        for y in range(0, original_height, tile_size - tile_overlap):
            for x in range(0, original_width, tile_size - tile_overlap):
                # Izračunavanje koordinata pločice
                x1 = x
                y1 = y
                x2 = min(x + tile_size, original_width)
                y2 = min(y + tile_size, original_height)

                # Izdvajanje pločice iz ulazne slike
                tile_img = img[y1:y2, x1:x2, :]

                # Dopunjavanje pločice
                tile_img = pad_image(tile_img, 16)

                # Inferencija nad pločicom
                tile_img = np.transpose(tile_img[:, :, [2, 1, 0]], (2, 0, 1))
                tile_img = np.expand_dims(tile_img, axis=0)
                try:
                    output_tile = ort_session.run(None, {input_name: tile_img})[0]
                except Exception as error:
                    print('Greška', error, imgname)
                    continue

                # Obrada izlazne pločice
                output_tile = np.clip(output_tile, 0, 1)
                output_tile = np.transpose(output_tile[0, :, :, :], (1, 2, 0))

                # Uklanjanje dodatih ivica sa pločice
                output_tile = output_tile[:(y2 - y1) * args.scale, :(x2 - x1) * args.scale, :]

                # Dodavanje obrađene pločice na izlaznu sliku
                output_img[y1 * args.scale:y2 * args.scale, x1 * args.scale:x2 * args.scale, :] = output_tile

        # Konverzija izlazne slike u 8-bitni RGB format
        output_img = (output_img * 255.0).round().astype(np.uint8)
        output_img = cv2.cvtColor(output_img, cv2.COLOR_BGR2RGB)

        cv2.imwrite(os.path.join(args.output, f'{imgname}_DRCT-L_X4.png'), output_img)

def pad_image(img, factor):
    """Dopunjava sliku tako da visina i širina budu deljive sa faktorom."""
    height, width = img.shape[:2]
    pad_height = (factor - (height % factor)) % factor
    pad_width = (factor - (width % factor)) % factor
    padded_img = cv2.copyMakeBorder(img, 0, pad_height, 0, pad_width, cv2.BORDER_REFLECT_101)
    return padded_img

if __name__ == '__main__':
    main()`

**Comment by zelenooki87** [comment]
and more robust code for correct tiling and progress bar
https://pastebin.com/uU4Wu2g9

**Comment by zelenooki87** [comment]
ONNX inference much is much slower than in anaconda environment.
I checked cuda, cudnn zlibwapi.dll they are all there.
Gpu is used during inference but I repeat much slower than in anaconda environment.
Test:
converted real gan DRCT model to fp16 onnx and optimized it
https://mega.nz/file/J4QQVSQA#ihEL_lxQhblpGZ3OFO-XjrCMxt0mFphIOFcRRrP3w68
code for execution in conda environment
https://pastebin.com/ArHEgBmR

much much faster in conda environment. check it yourself

and for image sizes error during onnx inference, see screenshot. not standard dimensions cropped images:
![SNAG-0000](https://github.com/chaiNNer-org/chaiNNer/assets/75204635/57bf7c19-bcb4-4514-ba52-4b3268f9a701)
![SNAG-0001](https://github.com/chaiNNer-org/chaiNNer/assets/75204635/e775a9e5-4f3e-4ec1-8f90-508ac5d86789)

with my example of code (pastebin link) I am not getting this errors. With any images sizes.
see codes added borders from the tile/"""Pads an image so that the height and width are divisible by factor.

I am not expert but with chatbot I have solved this issue. At least in conda environment. Hope you do also in chainner.
:)

**Comment by RunDevelopment** [comment]
Just an idea: We already use ONNX shape inference to detect the number input/output channels + scale. Assuming the shape inference fails when upscaling fails, we could systematically run shape inference to figure out which input sizes work. 

Since these types of valid sizes are typically of the form `2^n` or `k*2^n`, we can drastically reduce the input sizes we have to test to maybe 10 at most for most models. It's also important to note that we **don't** have to figure the smallest possible valid input size. We tile input images anyway, so it's fine if we find any valid input size <= tile size.

**Comment by joeyballentine** [comment]
that sounds reasonable

**Comment by RunDevelopment** [comment]
I reproduced the bug, and my shape inference idea does not work at all. Shape inference succeeds and gives the correct expected output size, even though the model will crash when actually run.
