### ISSUE TITLE
ROCM AMD chainner requierment file 

### ISSUE THREAD

**Issue by Loganavter** [chaiNNer-org/chaiNNer#2941]
Hello, if I try to replace the pytorch version on the latest version of ChaiNNer, then when the script starts, it still replaces it with the newest one. There was no such problem on previous versions of ChaiNNer. How can this be fixed? Is there any file in the plan that is responsible for choosing dependency versions?

**Comment by joeyballentine** [comment]
That definitely should not be happening. Pytorch and torchvision are the only dependencies we specifically don't auto update. Are you sure that you've installed it to chainners's integrated python?

**Comment by joeyballentine** [comment]
I will change that to not auto-update in order to avoid that issue.

**Comment by Loganavter** [comment]
thanks
