### ISSUE TITLE
Converting  ncnn and onnx model to a PyTorch model 

### ISSUE THREAD

**Issue by wolfkingal2000** [chaiNNer-org/chaiNNer#2942]
add Converting  ncnn and onnx model to a PyTorch model

**Comment by joeyballentine** [comment]
Not possible

**Comment by joeyballentine** [comment]
Sorry, I feel like I owe you an explanation. NCNN and ONNX work in a fundamentally different way to pytorch, and as a result only one-way conversion is possible.
