### ISSUE TITLE
An error occurred in a Upscale Face node

### ISSUE THREAD

**Issue by Euanggelos** [chaiNNer-org/chaiNNer#2951]
Hi! I am on win11, chaiNNer 0.24.0 Alpha portable, Installed everything in Dependency Manager with  RTX3090 x2 & 2950x. While upscale and other nodes works fine the Upscale Face node get the error (with a visible face)

An error occurred in a Upscale Face node:

Failed to run Face Upscale.

Input values:
• Image: RGB Image 1000x540
• Model: Value of type 'spandrel.__helpers.model_descriptor.ImageModelDescriptor'
• Upscaled Background: None
• Output Scale: 2x
• Weight: 0.7

Attached log file :)
[main.log](https://github.com/user-attachments/files/15798153/main.log)

**Comment by joeyballentine** [comment]
Unfortunately it doesn't appear to be logging what the actual error is which is a shame. For a sanity check, could you try upscaling a smaller picture with a very clearly defined face? just to be sure it works under "easy" circumstances (where it should for sure work)?

**Comment by Euanggelos** [comment]
Same error.... Any ideas? install an older version?

**Comment by joeyballentine** [comment]
Did it previously work on an older version for you? Also, what model are you using

**Comment by Euanggelos** [comment]
I have Install it first time a week ago...All 3 face Models codeformer, GFPGANv1.4, RestoreFormer give the same error.

**Comment by joeyballentine** [comment]
That's really odd. I'll look into it when I have time to be sure we didn't accidentally introduce a bug to face upscaling

**Comment by joeyballentine** [comment]
I'm still able to face upscale fine. Not really sure what that means for you, but I suppose it does mean that its something specific to you rather than a general issue with chaiNNer.

**Comment by Euanggelos** [comment]
Hi Updating to version v0.24.1 seems to solve the problem. Just to let you know! :)
