### ISSUE TITLE
cli fetch timeout error, reversion of PR-1853

### ISSUE THREAD

**Issue by nikkuexe** [chaiNNer-org/chaiNNer#2957]
**Description**
When using the CLI on MacOS I get the 5 minute timeout mentioned in [PR-1853 ](https://github.com/chaiNNer-org/chaiNNer/pull/1853)

It seems these changes were recently reverted.

https://github.com/chaiNNer-org/chaiNNer/commit/270ab746b47d99ecb7001f85e9763782972c6195#diff-247357a19207f9fd53e150436a901b3a7005aa8614004edce4968d7d0dbd00b8L158

**Comment by joeyballentine** [comment]
Whoops -- I will attempt to put this back and make a note of why it's necessary. Thanks!
