### ISSUE TITLE
"Custom scale to longer side" functionality

### ISSUE THREAD

**Issue by zelenooki87** [chaiNNer-org/chaiNNer#2988]
Is it possible in PyTorch to implement a "custom scale to longer side" functionality using a machine learning model for upscaling instead of standard interpolation filters?

While custom upscaling factors like 1x, 2x, 4x exist, a more useful option would allow specifying the desired longer side length and have the program:

Calculate the required upscaling factor (potentially involving multiple passes through the ML model).

Upscale the image using the ML model.

Downscale using standard filters only if the upscaled image exceeds the target size.

This is particularly relevant for batch processing and scenarios requiring multiple upscaling operations, for example, upscaling a 960x720 image with a 2x model to achieve a longer side of 4000 pixels.

**Comment by joeyballentine** [comment]
Use the "resize to side" node

**Comment by zelenooki87** [comment]
@joeyballentine 
My apologies for the lack of clarity. I need a function that, for x2 and x4 models, upscales the image multiple times to best approximate a "resize to longer side" operation. This would involve several upscaling passes, followed by downscaling if necessary. This approach yields higher quality output for certain models.

For example, with a custom longer side set to 2160 and an input file of 640x480 pixels, the function should recognize the model's 2x structure (e.g., SwinIR M x2) and upscale the image twice before downscaling it to 2160x1620 using a "resize to longer side" filter.

This method produces noticeably better results compared to a simple 2x upscale followed by resizing. The additional upscaling passes significantly improve the final output quality. Please refer to the provided screenshots and example for a visual comparison.

![1stpass](https://github.com/chaiNNer-org/chaiNNer/assets/75204635/d2c648b8-a47e-4784-a658-00d56ce77231)
![2ndpass](https://github.com/chaiNNer-org/chaiNNer/assets/75204635/dfe156b1-26fd-4ef0-8246-88f882bab69b)
![0](https://github.com/chaiNNer-org/chaiNNer/assets/75204635/8de7b403-2499-4baa-b81e-dd3ea297c9bd)
![1](https://github.com/chaiNNer-org/chaiNNer/assets/75204635/bd65cc91-8118-426c-ab4d-fc956c7245b5)

**Comment by joeyballentine** [comment]
What you're describing is already possible by just using multiple upscale nodes and then downscaling with resize to side. We are not going to be making the upscale node more complicated when this functionality already exists.

**Comment by zelenooki87** [comment]
Yes, I think you're right. But maybe it could still be useful for some people doing batch inferences, where the input files have different dimensions and vary from small to large. Thanks anyway! Best regards.
