### ISSUE TITLE
Shape not currently supported by NCNN

### ISSUE THREAD

**Issue by Kongsea** [chaiNNer-org/chaiNNer#3020]
![image](https://github.com/user-attachments/assets/4c731f14-f59e-43ad-a31c-2379099ddf85)

![image](https://github.com/user-attachments/assets/8dae8b8d-b8f6-43bd-a3fb-27061980102c)

**Information:**

- Chainner version: [0.24.1]
- OS: [Windows 10]

**Description**

When converted [the official Real-ESRGAN model](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth) to NCNN format, the error was raised:

An error occurred in a pytorch Convert To NCNN node:

Shape not currently supported by NCNN.

Input values:
• PyTorch Model: Value of type 'spandrel.__helpers.model_descriptor.ImageModelDescriptor'
• Data Type: fp16

**Logs**

Error

An error occurred in a pytorch Convert To NCNN node:

Shape not currently supported by NCNN.

Input values:
• PyTorch Model: Value of type 'spandrel.__helpers.model_descriptor.ImageModelDescriptor'
• Data Type: fp16

Stack Trace:
Traceback (most recent call last):
  File "C:\Users\A\AppData\Local\chaiNNer\app-0.24.1\resources\src\process.py", line 174, in run_node
    raw_output = node.run(context, *enforced_inputs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\chaiNNer\app-0.24.1\resources\src\packages\chaiNNer_pytorch\pytorch\utility\convert_to_ncnn.py", line 77, in convert_to_ncnn_node
    ncnn_model, fp_mode = onnx_convert_to_ncnn_node(onnx_model, is_fp16)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\chaiNNer\app-0.24.1\resources\src\packages\chaiNNer_onnx\onnx\utility\convert_to_ncnn.py", line 45, in convert_to_ncnn_node
    ncnn_model = NcnnModelWrapper(converter.convert(fp16, False))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\chaiNNer\app-0.24.1\resources\src\nodes\impl\onnx\onnx_to_ncnn.py", line 2852, in convert
    raise ValueError(error_msg)
ValueError: Shape not currently supported by NCNN.

**Comment by Kongsea** [comment]
**Update:**
[Real-ESRGAN x2plus model](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth) cannot be converted successfully.
However, [Real-ESRGAN x4plus](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x4plus.pth) can be converted successfully.

**Comment by joeyballentine** [comment]
that model is just incompatible with ncnn. this is not a chainner issue
