### ISSUE TITLE
is there a video player node ? or can be implemented ?

### ISSUE THREAD

**Issue by NeverBeLazyG** [chaiNNer-org/chaiNNer#3033]
hey guys, i want to use this as a video player or a view video node? is there a way to use this tool as an videoplayer for bad quality films. letz say i have a bad video with low resolution, and i want to watch it with high quality in real time, not encoding the complete video first, just on the fly, like a video player. it it possible ?

wondering why no one already made an ai video player like vlc, where you can just use different models to watch bad quality input films.

any idea how to do that ?

**Comment by joeyballentine** [comment]
chaiNNer cannot be used this way. Even if it could, there's no way you'd be able to upscale in real-time
