### ISSUE TITLE
Add percentage to blend?

### ISSUE THREAD

**Issue by mr-september** [chaiNNer-org/chaiNNer#3037]
**Motivation**
I would like a node-based workflow to blend images. For example, a base image goes through upscaling with 2 different models, and then blended together with the Overlay layer at 80% opacity/strength.

**Description**
Add a percentage slider to the Blend node.

**Alternatives**
Open both images in photoshop, and set the top image transparency to anything other than 50%.

**Comment by yukihina** [comment]
Use **opacity** node. Example Upscale image #1 connects to Opacity (example 20.0). That node connects to overlay layer in Blend Image Node (as Base layer you connect Upscale Image #2, that would work as 80.0).

**Comment by mr-september** [comment]
Excellent. Thank you!
