### ISSUE TITLE
Vapoursynth/avisynth Filtering

### ISSUE THREAD

**Issue by LuisB79** [chaiNNer-org/chaiNNer#381]
if possible, adding vapoursynth/avisynth filtering for denoising or debanding video, would be a great addition

**Comment by LuisB79** [comment]
Hi!, i've seen lot's of improvement since then, keep up the good work!, are there plans for this?

**Comment by joeyballentine** [comment]
Eventually, but probably not soon. First I need to change how I handle video processing in general. There's also a lot of other things I wanna get done before adding stuff like this. Not saying it won't happen, it's just gonna take a while.

**Comment by LuisB79** [comment]
it's ok, take your time

**Comment by LuisB79** [comment]
hey if posible just add avisynth, vapoursynth is unnecessarily complex

**Comment by joeyballentine** [comment]
Isn't avisynth a lot older?

Also, sorry but this still probably won't be coming for quite some time. There are still many more important things to get done before I take on something this large.

**Comment by LuisB79** [comment]
oh yeah no worries, avisynth+ is the upgraded version

**Comment by LuisB79** [comment]
hi!, is this still not planned for  near future development?

**Comment by joeyballentine** [comment]
I would still like to add this at some point, but we're still not in a position where it makes sense to add. Ideally we would wait until our iterator rewrite to add any new kinds of iterable processing

**Comment by LuisB79** [comment]
aight

**Comment by joeyballentine** [comment]
I still want to do this, there's no reason to close it yet.

**Comment by LuisB79** [comment]
oh sure, its just that is not planned atm, and well i kinda have an ocd for my notifications xd

**Comment by joeyballentine** [comment]
You get active notifications from this? That's odd if there isn't any activity... Anyway, I'll close this and just open a separate issue for it

**Comment by LuisB79** [comment]
thanks c:
