### ISSUE TITLE
Sprite sheet iterator and generator

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#564]
Add 2 nodes for iterating (splitting) and generating (combining) sprites.

1. An "Iterate Sprite Sheet" node that takes one image and its dimensions, and returns an image iterator of all sprites in the sheet.
2. A "Generate Sprite Sheet" node that takes an image iterator and dimensions, and returns one image that is the sprite sheet of all images in the iterator.

This requires the new iterator concept we've been talking about.

**Comment by joeyballentine** [comment]
It actually wouldn't be impossible with the current system, just convoluted. I just thought of a way to do it

**Comment by joeyballentine** [comment]
On second thought, I misunderstood the concept and yeah, we're currently only able to take a spritesheet in and put a spritesheet out, not do one without the other
