### ISSUE TITLE
Add a "Create Overlay" node

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#676]
Sometimes, I want to create overlays from the high-frequency details of a texture. We already support the "Overlay" blend mode which consumes overlays, but we don't have a node to create them yet.

**Comment by joeyballentine** [comment]
I'm confused by what exactly you mean by an overlay here. What do you have in mind exactly for "creating" an overlay?

**Comment by RunDevelopment** [comment]
Just a node that given 2 images A and B returns `(A - B + 1) / 2`.

**Comment by joeyballentine** [comment]
Can't you basically already do that by combining some blend modes?

**Comment by RunDevelopment** [comment]
I was mistaken over how the Overlay blend mode works. The actual result would be more complex than just `(A - B + 1) / 2`.

**Comment by joeyballentine** [comment]
@RunDevelopment could you elaborate on what you mean by an overlay? I can't implement this until I understand what you're attempting to do here

**Comment by RunDevelopment** [comment]
We have an overlay blend mode, so for 2 images O, B and `overlay(O, B) = C`, I wanted a node that does `createOverlay(B, C) = O`. So it's kind of an inverse to the overlay blend mode.

I already worked out the formula to calculate O. Unfortunately, O is not unique and not in always possible in certain edge cases because of how the overlay blend mode works. That's why I haven't implemented it yet.

Honestly, we can probably close this.
