### ISSUE TITLE
“chainner.app” cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by manoel-andre** [chaiNNer-org/chaiNNer#761]
Hi, just wondering if you're planning on registering as a developer so we can install it easier on macs. I can't override this settings on my macbook since it's from work. Thank you!

**Comment by joeyballentine** [comment]
What's funny is I literally just got the same thing on my work MacBook attempting to look into these macOS issues haha. 

I'm really hesitant to spend money on something like this but I might just have to bite the bullet and pay for it (as well as a code signing certificate on windows). It is only $99 a year, which isn't that much money in the grand scheme of things. We just never really had macOS users before this new influx of users so there was not really a need to get the developer registration.  I'll consider it.

**Comment by hopelesscase** [comment]
You can actually get it to open without verifying the developer. Right-click to open the context menu and hit Open. It'll throw an alert. Clear the alert and go again with right-click and open. You should now see an "Open" button.

Additional reading:
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by joeyballentine** [comment]
Unfortunately the way my work laptop is set up prevents that from happening, for security reasons. And it's the only Mac laptop I have access to.

**Comment by hopelesscase** [comment]
I see. My personal Mac is really the only computer I can run stuff like this on. I'm lucky to watch YouTube videos on my Windows. XP

**Comment by stonerl** [comment]
This problem is kind of resolved when installing from homebrew.
