### ISSUE TITLE
Make splash screen more detailed 

### ISSUE THREAD

**Issue by joeyballentine** [chaiNNer-org/chaiNNer#772]
We should do a few things:
- be more verbose about what is going on at the current moment 
- be clear what's installing and what progress it's at 
- have some sort of better error handling and what to do when something breaks at this step. "Reset all settings" might be a good option to have if an error occurs as well

**Comment by RunDevelopment** [comment]
Why not just get rid of the splash screen and do it all in the main window? We already have a loading animation there anyway.

**Comment by joeyballentine** [comment]
That's a good idea actually

**Comment by RunDevelopment** [comment]
The splash screen was removed in #2731.
