### ISSUE TITLE
 failed to fetch with ChaiNNER 0.11.2 on Mac OS 10.14.6 Mojave

### ISSUE THREAD

**Issue by predmunds** [chaiNNer-org/chaiNNer#780]
Fetch error again (as with v 00.11.1) - on V 00.11.2 on Mac OS 10.14.6 Mojave

I’m using an iMac late 2015. Intel. 

ZIP Copy of Main.log attached
[main copy.log.zip](https://github.com/joeyballentine/chaiNNer/files/9386892/main.copy.log.zip)

**Comment by LeuschkeTressa** [comment]
The same for me.

Using the Dependency Manager I can download PyTorch, but not NCNN or ONNX.

Full logs attached.

version: 0.11.2
OS: macOS 12.4 (Monterey)
machine: MBP M1

[logs.zip](https://github.com/joeyballentine/chaiNNer/files/9388046/logs.zip)

**Comment by joeyballentine** [comment]
This is a known issue with M1 MacBooks. It seems ncnn and onnx do not currently support these platforms. I'm looking into how to beat address this.

**Comment by RunDevelopment** [comment]
@joeyballentine Maybe we could dry-run install packages to test whether they are installable? I don't know if that'll work, but it might.

**Comment by joeyballentine** [comment]
@RunDevelopment I think the real fix might be checking to make sure pip finds a valid wheel. If it doesn't then that means it can't be installed

**Comment by joeyballentine** [comment]
@LeuschkeTressa Are you in the Discord server and would you mind testing a possibly working M1 version of NCNN for me?

**Comment by joeyballentine** [comment]
@predmunds Would you mind testing the [latest release](https://github.com/joeyballentine/chaiNNer/releases/tag/v0.11.4)?

**Comment by LeuschkeTressa** [comment]
> @LeuschkeTressa Are you in the Discord server and would you mind testing a possibly working M1 version of NCNN for me?

I'm not in the Discord server, but I'm more than happy to test a possibly working version! Just send me/point me to an installation file.

**Comment by joeyballentine** [comment]
@LeuschkeTressa see if this installs for you at all. It's built specifically for arm macos https://cdn.discordapp.com/attachments/930878114299539536/1011707278367391814/ncnn_vulkan-2022.8.23-cp39-cp39-macosx_11_0_arm64.whl

Install it by running `pip install path/to/the.whl` with the actual path. If you want to try installing to chaiNNer's python rather than your system python, use `full/path/to/your/Application Support/chaiNNer/python/python/python3.9 -m pip install full/path/to/the.whl` with the actual path to your Application support folder and the whl file.

Please let me know if it works or if you have trouble with it

**Comment by joeyballentine** [comment]
@artphotolab ok so it looks like upgrading opencv didn't change the fact that it doesn't natively support macos 10. I'm not sure what to do about that then.

**Comment by LeuschkeTressa** [comment]
@joeyballentine seems to work fine:

![CleanShot 2022-08-24 at 18 48 35](https://user-images.githubusercontent.com/76884940/186476597-ff30dd26-0adb-4c7d-a271-0223c712552d.jpg)

Thanks!

**Comment by LeuschkeTressa** [comment]
@joeyballentine seems to work fine:

![CleanShot 2022-08-24 at 18 48 35](https://user-images.githubusercontent.com/76884940/186476597-ff30dd26-0adb-4c7d-a271-0223c712552d.jpg)

Thanks!

**Comment by LeuschkeTressa** [comment]
@joeyballentine Actually I don't have a need for this myself right now and had to switch focus to other stuff - but if you want to point me to a downloadable NCNN model to try I'll happily do so and report back!

**Comment by joeyballentine** [comment]
This is one I always use for testing: https://github.com/nihui/realsr-ncnn-vulkan/tree/master/models/models-DF2K

**Comment by joeyballentine** [comment]
@LeuschkeTressa That wheel most likely won't actually work if you try to run an NCNN model. This one should though: https://cdn.discordapp.com/attachments/930878114299539536/1012105794738724955/ncnn_vulkan-2022.8.24-cp39-cp39-macosx_11_0_arm64.whl

**Comment by joeyballentine** [comment]
Though this issue wasn't originally about M1 macs, I amclosing this issue as it has been confirmed that the M1 versions of ncnn work fine under the right conditions.

@predmunds feel free to let me know if this is still an issue for you and I can re-open the issue.

**Comment by joeyballentine** [comment]
Recently, opencv updated with <10.15 support, and we updated chaiNNer with it. If you're still willing, could you give it a try?

**Comment by predmunds** [comment]
Thanks for the info Joey. I'll try it out and let you know how it goes. Cheers. P.

**Comment by predmunds** [comment]
result of testing with latest ChaiNNer.  [Alpha v0.17.1](https://github.com/chaiNNer-org/chaiNNer/releases/tag/v0.17.1)

"Critical Error

A critical error occurred while processing the node data returned by the backend. Error: Failed to fetch"

See main.log attached.

**Comment by joeyballentine** [comment]
Thanks. I've got not clue what the error in the log means but it looks like something is still incompatible with old macos. :(

**Comment by joeyballentine** [comment]
According to users who have tested it, macos < 10.15 still doesn't work. I will just officially say that it will never be supported.
