### ISSUE TITLE
Moving around the canvas by holding down the middle mouse button

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [chaiNNer-org/chaiNNer#784]
This will allow you to click anywhere on the canvas, including the nodes themselves, without hitting them.

**Comment by RunDevelopment** [comment]
While I do like the feature, this might be something that we can't implement ourselves.

@joeyballentine, you know React flow better. Is this possible for us, or does this have to be added to RF itself?

**Comment by joeyballentine** [comment]
I don't think this is possible for us

**Comment by RunDevelopment** [comment]
It seems like RF already has an issue for this https://github.com/wbkd/react-flow/issues/1767. Given the recent activity, it might be resolved soonish(?).

**Comment by moklick** [comment]
Drag pane by middle mouse is the new default behaviour in v11.

**Comment by RunDevelopment** [comment]
@joeyballentine just merged #1063. Paning with the middle mouse button will be available in the next release (maybe 2~4 weeks from now).
