### ISSUE TITLE
Combobox node (list images with one selected as output)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [chaiNNer-org/chaiNNer#785]
The node is similar to stack images, only in the list we choose which image to send to the output.
This would make it easier to save only the desired image.

**Comment by RunDevelopment** [comment]
I think you just suggested a subset of what #148 would be able to do.

**Comment by 0x4E69676874466F78** [comment]
@RunDevelopment To some extent, yes, I also wanted to say about the conditions, it's cool that you think about it too.
But this is all complicated, so for now I decided to proposal a more simple/specific function.

**Comment by joeyballentine** [comment]
Implemented by #1945
