### ISSUE TITLE
Error report for chaiNNer 0.11.2

### ISSUE THREAD

**Issue by kirkartwork** [chaiNNer-org/chaiNNer#791]
I emailed my log files (I think) from the Application Support folder. Hope that helps. 

Error:
```UnhandledRejection Error: Attempted to register a second handler for 'get-port'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:189:337)
    at /Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:72010
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:71513
```
OS: macOS 10.13

**Comment by joeyballentine** [comment]
@RunDevelopment looks like the fix doesn't always work. Maybe we should make a safe handler registrator after all...

**Comment by RunDevelopment** [comment]
Do you mean the `trueOnce`?

**Comment by joeyballentine** [comment]
@kirkartwork , please test the [latest release](https://github.com/joeyballentine/chaiNNer/releases/tag/v0.11.3) and let me know if this issue is fixed.

**Comment by kirkartwork** [comment]
This is the screenshot I got before getting a chance to Quit the
application.


---
Lorenzo Kirkpatrick
[image: Facebook] <https://www.facebook.com/lorenzo.kirkpatrick/>[image:
Instagram] <https://www.instagram.com/kirkcartoons>

**Comment by kirkartwork** [comment]
After that, I have to click Quit, for the app to quit. Then, I delete the
app and the Application Support folder.


---
Lorenzo Kirkpatrick
[image: Facebook] <https://www.facebook.com/lorenzo.kirkpatrick/>[image:
Instagram] <https://www.instagram.com/kirkcartoons>

**Comment by joeyballentine** [comment]
@kirkartwork would you mind testing the [latest release](https://github.com/joeyballentine/chaiNNer/releases/tag/v0.11.4)?

**Comment by kirkartwork** [comment]
Still getting the same hangup. It will not install dependencies. Maybe my
MacOS is too old?


---
Lorenzo Kirkpatrick
[image: Facebook] <https://www.facebook.com/lorenzo.kirkpatrick/>[image:
Instagram] <https://www.instagram.com/kirkcartoons>

**Comment by kirkartwork** [comment]
Yep. I think that would be best. Thanks for getting it a try. Once I
upgrade my machine (hopefully by Christmas), I look forward to trying out
your app. Cheers!


---
Lorenzo Kirkpatrick
[image: Facebook] <https://www.facebook.com/lorenzo.kirkpatrick/>[image:
Instagram] <https://www.instagram.com/kirkcartoons>

**Comment by kirkartwork** [comment]
Not working. Attached is a screenshot of what's going on. No loading bar,
just the red line in the logo stuck at the top and trying to install
dependencies. It seems like it can't find where the dependencies are
located. Could it be an issue with where the application is looking for the
downloaded dependencies? Or, is it trying to install dependencies from an
online source?



---
Lorenzo Kirkpatrick
[image: Facebook] <https://www.facebook.com/lorenzo.kirkpatrick/>[image:
Instagram] <https://www.instagram.com/kirkcartoons>

**Comment by kirkartwork** [comment]
I would normally wait about 30 minutes for the app to find and install
dependencies, then I just Force Quit the app. Thanks.


---
Lorenzo Kirkpatrick
[image: Facebook] <https://www.facebook.com/lorenzo.kirkpatrick/>[image:
Instagram] <https://www.instagram.com/kirkcartoons>

**Comment by joeyballentine** [comment]
Update on this issue btw: We can't support macos versions lower than 10.15 at the moment due to a critical dependency we need (opencv-python) not supporting < 10.15 yet. Their next update should support it (I worked out the problem with them), but they are taking a long time to release an update. So, eventually older macos versions _might_  work, but at this time we do not officially support them. I am going to close this issue as it is something that is currently out of my control. Just stay tuned for an update that mentions theoretical older macos support, and I will also try to find all the old issues and make comments about it when it happens.

**Comment by kirkartwork** [comment]
I tried the chainner.app again and got the following error and log file.
[image: Screen Shot 2023-02-07 at 2.25.55 PM.png]



---
Lorenzo Kirkpatrick
[image: Facebook] <https://www.facebook.com/lorenzo.kirkpatrick/>[image:
Instagram] <https://www.instagram.com/kirkcartoons>

**Comment by kirkartwork** [comment]
It definitely was an improvement, just not all the way.


---
Lorenzo Kirkpatrick
[image: Facebook] <https://www.facebook.com/lorenzo.kirkpatrick/>[image:
Instagram] <https://www.instagram.com/kirkcartoons>

**Comment by joeyballentine** [comment]
Could you share the actual text if possible? Your screenshot did not properly send. Are you replying to these via email?

**Comment by joeyballentine** [comment]
And thanks for taking the time to investigate. I don't wanna say we have <10.15 support until it's truly verifiably working

**Comment by kirkartwork** [comment]
The was as follows: Critical Error: A critical error occurred while
processing the node data returned by the backend. Error: Failed to fetch.


---
Lorenzo Kirkpatrick
[image: Facebook] <https://www.facebook.com/lorenzo.kirkpatrick/>[image:
Instagram] <https://www.instagram.com/kirkcartoons>

**Comment by joeyballentine** [comment]
would you mind sending a zip file of your logs? Would be really helpful. Unfortunately I'm guessing another dependency just doesn't support that low of a macos version :(

**Comment by kirkartwork** [comment]
Sure, here you go!


---
Lorenzo Kirkpatrick
[image: Facebook] <https://www.facebook.com/lorenzo.kirkpatrick/>[image:
Instagram] <https://www.instagram.com/kirkcartoons>

**Comment by joeyballentine** [comment]
According to users who have tested it, macos < 10.15 still doesn't work. I will just officially say that it will never be supported.
