### ISSUE TITLE
Error report for chaiNNer 0.11.3

### ISSUE THREAD

**Issue by modulator** [chaiNNer-org/chaiNNer#800]
Error:
```UnhandledRejection TypeError: Object has been destroyed
    at n.loadURL (node:electron/js2c/browser_init:33:1843)
    at /Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:77327
```
OS: macOS 10.13

**Comment by modulator** [comment]
Thanks SO much for the work you're doing to get this Mac OS issue resolved!

**Comment by joeyballentine** [comment]
Unfortunately it seems like it just never actually gets fixed :(

Is it the same full error message as before?

**Comment by joeyballentine** [comment]
Recently, opencv updated with <10.15 support, and we updated chaiNNer with it. If you're still willing, could you give it a try?

**Comment by joeyballentine** [comment]
According to users who have tested it, macos < 10.15 still doesn't work. I will just officially say that it will never be supported.
