### ISSUE TITLE
Fetch error again (as with v 00.11.1/2/3) - on V 00.11.4 on Mac OS 10.14.6 Mojave.

### ISSUE THREAD

**Issue by predmunds** [chaiNNer-org/chaiNNer#820]
Fetch error again (as with v 00.11.1/2/3) - on V 00.11.4 on Mac OS 10.14.6 Mojave. I cant upgrade.

I’m using an iMac late 2015. Intel.

ZIP Copy of Main.log attached
[main copy.log.zip](https://github.com/joeyballentine/chaiNNer/files/9416574/main.copy.log.zip)
<img width="542" alt="Screenshot 2022-08-24 at 14 39 07" src="https://user-images.githubusercontent.com/111522998/186433948-516c3913-9534-4f0d-bb57-66b3fdbf2bca.png">

**Comment by joeyballentine** [comment]
Same error as before. I'm going to attempt to just compile opencv-python myself specifically for macos 10

**Comment by joeyballentine** [comment]
You can't upgrade to at least 10.15? That appears to be the lowest version opencv-python supports

**Comment by predmunds** [comment]
Mac OS 10.14.6 Mojave is the last version that supports 32 bit apps. So it will be on many systems still for a while to come. I need to stay on it as I still use some 32 bit apps.

**Comment by joeyballentine** [comment]
I see. Well, I'm testing compiling with an older macos target, but I have no idea if it'll end up working.

**Comment by joeyballentine** [comment]
If it ends up not working, I may have to just say that anything lower than 10.15 is not supported by chaiNNer. Opencv is a critical part of chaiNNer as we use it all over, so if it can't work below 10.15, neither can chaiNNer

**Comment by artphotolab** [comment]
Hi Joey, 
I just read the topic you linked that is now closed. As I'm not into coding or software, what can we conclude about the utilisation of chaiNNer on Mac OS x 10.14.6 ?

**Comment by joeyballentine** [comment]
@artphotolab currently you can't use it, unless you can get opencv to compile for you on 10.14. However, they just merged my PR that lowers the build target to 10.13, meaning that once their next update comes out, I will be able to update chaiNNer to use that version which should work on your system.

**Comment by artphotolab** [comment]
Ok perfect then it may come to life one day ! :)
Thanks a lot for your work !

**Comment by predmunds** [comment]
Thanks for your efforts Joey. That sounds promising!

**Comment by joeyballentine** [comment]
Closing this issue as there is nothing I can do about it until opencv releases an update.
