### ISSUE TITLE
Resize node aspect ratio

### ISSUE THREAD

**Issue by Kessinen** [chaiNNer-org/chaiNNer#821]
I would like to be able to resize the image while respecting aspect ratio. Resize by factor already exists, but what if I want an image that is 952x720 to be 1080 pixels high and maintain the aspect ratio. Currently I have to calculate the correct value manually.

Fix suggestions:
- A button to toggle a dimension to auto.
- Set value to zero and it is considered as auto
- Gimp has a chain icon that locks aspect ratio

**Comment by joeyballentine** [comment]
I actually want to implement this into the resize (resolution) node, with a chain icon button thingy like you suggested. This just requires implementing a general input linking mechanism which will take some work. There are other nodes that will benefit from that too, like ncnn/s load model node.

**Comment by theflyingzamboni** [comment]
Tbh, I would like to at some point find a way to fuse duplicate node versions (resize and crop). I've never liked that we had all those separate, we just haven't had a way to combine them properly.

**Comment by joeyballentine** [comment]
I have an idea for that actually. I'll message you on discord

**Comment by RunDevelopment** [comment]
This functionality is implemented by Resize To Side.
