### ISSUE TITLE
Video frame iterator doesn't write the output video

### ISSUE THREAD

**Issue by Kessinen** [chaiNNer-org/chaiNNer#823]
**Information:**
- Chainner version: [e.g. 0.11.4]
- OS: Manjaro Linux

**Description**
Video frame iterator does not write the final video. I am able to save it frame by frame as images, but not as video file.

I have included a screenshot as an example. I have tried to connect the input video straight to output, but nothing is written. I've removed the save image node, but the result is the same.
![image](https://user-images.githubusercontent.com/46515609/186515501-4922df66-71ce-447c-9a56-9bb90cf655e8.png)

**Comment by Kessinen** [comment]
Chainner version is 0.11.4

**Comment by joeyballentine** [comment]
Can you send your logs? I have a hunch this is an issue with ffmpeg/codecs

**Comment by Kessinen** [comment]
Should have checked the logs. There's an error with the codec as you said. Is there a way to set a desired codec or is it hard coded? The log was really long and I removed all but entries from the last video write operation.
[main.log](https://github.com/joeyballentine/chaiNNer/files/9419319/main.log)

**Comment by joeyballentine** [comment]
There's currently no way to set a codec in chainner. I struggled to even get one to work most of the time. I think the reason is because opencv can't bundle codecs due to licensing issues. The real fix for this is to not use the opencv video reader/writer and to instead use a direct ffmpeg binding that has all the codecs bundled. I just haven't gotten around to it yet

**Comment by Kessinen** [comment]
Yeah. Found a post: "Turns out open cv install via pip does not have access to the avc1 codec because of licensing issues."
So I tried to install python opencv from os repository with pacman, but still no-go. So I guess I just have to wait for an update. Still, chainner is an absolute diamond!

**Comment by joeyballentine** [comment]
I'll be replacing the current video functionality as my next priority
