### ISSUE TITLE
Can't allocate memory beyond 16Gb of RAM

### ISSUE THREAD

**Issue by badnazo** [chaiNNer-org/chaiNNer#826]
**Information:**
{
  "app": {
    "version": "0.11.3",
    "packaged": true,
    "path": "C:\\Users\\Fledge4tw\\AppData\\Local\\chainner\\app-0.11.3\\resources\\app"
  },
  "process": {
    "cwd": "C:\\Users\\Fledge4tw\\AppData\\Local\\chainner\\app-0.11.3",
    "argv": [
      "C:\\Users\\Fledge4tw\\AppData\\Local\\chainner\\app-0.11.3\\chainner.exe"
    ]
  },
  "os": {
    "version": "Windows 10 Pro N",
    "release": "10.0.19044",
    "arch": "x64",
    "endianness": "LE"
  },
  "cpu": {
    "manufacturer": "Intel",
    "brand": "Gen Intel® Core™ i9-12900K",
    "vendor": "GenuineIntel",
    "family": "6",
    "model": "151",
    "stepping": "2",
    "revision": "",
    "voltage": "",
    "speed": 3.19,
    "speedMin": 3.19,
    "speedMax": 3.19,
    "governor": "",
    "cores": 24,
    "physicalCores": 16,
    "processors": 1,
    "socket": "Other",
    "flags": "de pse tsc msr mce sep mtrr mca cmov psn clfsh ds acpi mmx fxsr sse sse2 ss htt tm ia64 pbe",
    "virtualization": false,
    "cache": {
      "l1d": 256,
      "l1i": 512,
      "l2": 4194304,
      "l3": 31457280
    }
  },
  "gpus": [
    {
      "vendor": "Intel Corporation",
      "model": "Intel(R) UHD Graphics 770",
      "bus": "PCI",
      "vram": 1024,
      "vramDynamic": true,
      "subDeviceId": "7D321462"
    },
    {
      "vendor": "NVIDIA",
      "model": "NVIDIA GeForce RTX 3070 Ti",
      "bus": "PCI",
      "vram": 8192,
      "vramDynamic": false,
      "subDeviceId": "0x50511462",
      "driverVersion": "516.94",
      "name": "NVIDIA GeForce RTX 3070 Ti",
      "pciBus": "00000000:01:00.0",
      "fanSpeed": 32,
      "memoryTotal": 8192,
      "memoryUsed": 2222,
      "memoryFree": 5819,
      "utilizationGpu": 1,
      "utilizationMemory": 1,
      "temperatureGpu": 50,
      "powerDraw": 97.03,
      "powerLimit": 310,
      "clockCore": 1992,
      "clockMemory": 9242
    }
  ],
  "settings": {
    "animate-chain": "true",
    "disable-hw-accel": "false",
    "is-cpu": "false",
    "is-fp16": "false",
    "node-favorites": "[]",
    "node-selector-collapsed": "false",
    "snap-to-grid": "false",
    "snap-to-grid-amount": "15",
    "startup-template": "\"\"",
    "use-dark-mode": "true",
    "use-system-python": "false"
  }
}

**Description**
As soon as i hit 16Gb of ram utilization when processing a workload, ChaiNNer drop with an exception.

Checked my rams, both 16Gb modules works fine under Memtest86.

**Logs**
An error occurred in a Upscale Image node:

[enforce fail at ..\c10\core\CPUAllocator.cpp:76] data. DefaultCPUAllocator: not enough memory: you tried to allocate 456855552 bytes.

Input values (partial):
• Image: RGB image 7680x4800

**Comment by joeyballentine** [comment]
Could you send a screenshot of the chain you're using? This is a bit unsurprising as the image you're working with is very large, and if you're going to be upscaling that, it's going to require a lot of ram to keep the results in memory.

One of the reasons so much memory is used is the cache we have of each node result, which prevents nodes from having to run more than ones and also allows the pause/resume feature. I'm currently working on optimizing this a bit so remove anything that isn't needed so the total ram usage is less. Hopefully that will be something included in the next version.

For now, I'd say maybe upscale smaller images. Just as a sanity check, pytorch is using your GPU and not CPU, right?

**Comment by badnazo** [comment]
Sorry to have left the issue without update

Here is a screenshot of the chain i'm using to get this bug. I've found a workaround, mainly resizing the image to 50% after each step.

![chainner_LxjiwEAOLW](https://user-images.githubusercontent.com/2779921/187800710-761ce2ba-ff0b-4d20-bf64-8ed4348576fa.png)

VRAM get's used to 100% when i start the chain. RAM get filled a big chunk at start, then slowly fill up at each upscale step, and crash as soon as i hit 15.9Gb. I don't mind the software using much ram, but the crash at exactly 16Gb was kinda odd. If i close as many apps as i can (mainly my web browser, how surprising) and i manage to stay under 16Gb, render works properly (under two or three minutes)

I have memory compression and swap disabled on my current configuration, might have an impact. CPU mode for PyTorch is disabled

**Comment by badnazo** [comment]
Don't know if relevant, but I updated to v0.12.1 and I've got the same error

An error occurred in a Upscale Image node:

[enforce fail at ..\c10\core\CPUAllocator.cpp:76] data. DefaultCPUAllocator: not enough memory: you tried to allocate 793491456 bytes.

Input values (partial):
• Image: RGB image 3392x4796
• Number of Tiles: Auto

But seems like the software was able to allocate RAM up to 16.7Gb, so root cause might not be what i first described.

![image](https://user-images.githubusercontent.com/2779921/188521079-868e7cdb-b22f-4391-9614-e159aa0095cb.png)

![image](https://user-images.githubusercontent.com/2779921/188521108-08c50be4-4314-41a4-8eaf-cf5923ef4662.png)

**Comment by joeyballentine** [comment]
@badnazo can you send a screenshot of your dependency manager? Is the cuda version of pytorch installed?

**Comment by badnazo** [comment]
![image](https://user-images.githubusercontent.com/2779921/188751446-8f2e22b1-7789-4da4-a594-bcf426618273.png)

**Comment by joeyballentine** [comment]
You definitely have CUDA PyTorch installed, so it's not that. I honestly have no clue. It could be that python itself just doesn't like allocating more than 16GB for itself? If that's the case, there isn't much I can do. Is it always when it hits 16GB exactly?

**Comment by badnazo** [comment]
Updated to 0.12.4
I've tried to enable FP16 mode to see if it would change anything
I have been able to use up to 9Gb of Ram in chaiNNer and more than 18Gb of RAM of total RAM, but i keep crashing with the same error message.
VRAM usage is now about 50-60% during the whole process, was 98% before this version.

**Comment by joeyballentine** [comment]
Are you able to upscale images this large with other applications?

**Comment by badnazo** [comment]
Any recomandations of apps i could try ?
I tried cupscale, but i can't seem go get it not rescaling the image to the original size

**Comment by 0x4E69676874466F78** [comment]
As a workaround, you can split the images into pieces, upscale them and then merge them.
Such as: https://www.reddit.com/r/StableDiffusion/comments/xa48o6/enhancing_local_detail_and_cohesion_by_mosaicing/

**Comment by joeyballentine** [comment]
Merging them though is still going to require having all the pieces in memory at the same time, otherwise you won't be able to combine all the pieces together.

Splitting the image up like that is great for saving VRAM (chaiNNer does that internally), but since this is a RAM issue I don't think it will necessarily help, that is unless you want to save each tile to disk and use a different tool to stitch them all together (and hope that the tool uses less memory than chaiNNer does)

**Comment by 0x4E69676874466F78** [comment]
Look at the [libvips](https://github.com/libvips/libvips) library.

**Comment by badnazo** [comment]
To be fair, i don't need an image this large. I just happened to play with the software and stumble upon this bug.
My actual workaround is to resize the output image at each step by 50% and I'm very satisfied with the end result.
Still, I'm curious why this happen, and if i can help improve the software with my feedback and continous test, I'm happy. But this issue isn't really bothering me

**Comment by badnazo** [comment]
I think you can clear this issue. Just reinstalled my windows after loads of shenanigans to try fixing the issue. Just finished reinstalling my windows and works perfectly now.
Sorry for this useless bug report

**Comment by uftrvbnv** [comment]
Same issue with my device, but my pc just freezes and i need to restart to do anything
When image is being saved at 16 bg ram usage pc freezes.

**Comment by badnazo** [comment]
@uftrvbnv 
Look at your System paged memory and try to let it be managed by windows ... found out it could take up to total GB or memory when processing images twice with x4 models.
Looks like it was my issue since the beginning.
