### ISSUE TITLE
Option to use homebrew's python?

### ISSUE THREAD

**Issue by hopelesscase** [chaiNNer-org/chaiNNer#828]
**Motivation**
Is it possible to use homebrew's python instead the bundled python (looks like 3.9?) or the system python (3.8.9)?

The reason I ask is I can only get ONNX to load and work by using the system python and despite having NCNN saying it's install via the dependancies manager I can't use any of the nodes. That's only after switching to the system's python. I tried to use the bundled python, but then neither ONNX nor NCNN would install at all. However, via homebrew I have the latest python (3.10.6), NCNN, ONNX, PyTorch, etc. and it's easier to keep everything updated and manage in case things get screwy. Which with me is almost a certainty.

**Description**
If it's at all possible, in addition to having option for the bundled python or the system python maybe an option to use homebrew's python. Homebrew is saved in slightly different locations between the Intel Macs and the silicon Macs though and I've no idea how difficult it would be to implement something like that… Or maybe a way to manually interface the bundled python to troubleshoot… It's not a fully fleshed out idea. Just throwing it out there. 

**Alternatives**
I'm not really sure of alternatives. I've used homebrew's python to run your forked BlueAmulet/ESRGAN and other upscalers without much issue outside of having to use cpu and run outta of memory or whatever.

Oh, speaking of memory I have a side note question of sorts… Could this relate to this project at all? https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/

Totally random question/request and I don't mind if it's not acted on.
Again, just throwing it out there. (＾ᴗ＾;;)

**Comment by joeyballentine** [comment]
The pytorch apple silicon support isn't released yet. It will be a long time before that's supported in chainner.

As for supporting homebrew python, I guess I could look into that. I had no idea homebrew had something for a separate python instance. I can't personally test that so the fact that you said M1 saves that slightly differently makes me worried about implementing that (again since I can't test it myself)

**Comment by hopelesscase** [comment]
Would this help? 
https://docs.brew.sh/Homebrew-and-Python

As for location, homebrew says it "installs Homebrew to its preferred prefix (/usr/local for macOS Intel, /opt/homebrew for Apple Silicon and /home/linuxbrew/.linuxbrew for Linux) so that you don’t need sudo(https://docs.brew.sh/FAQ#why-does-homebrew-say-sudo-is-bad) when you brew install."

I won't mention it more because you said you can't test it and there's nothing for that. It is what it is and that's cool.

Otherwise, thank you for this awesome app! It's been so much easier to use and saves so much more time with repetitive scaling and junk. Thank you, thank you!

**Comment by joeyballentine** [comment]
I can do my best to attempt to implement it. i just won't be able to guarantee that it works for everyone.

**Comment by Athari** [comment]
In addition to system and bundled Pythons, I'd like to be able to choose _any_ Python installation on my drive by specifying a custom path. Currently I have to run ChaiNNer with `set path=mypython;%path% && start chainner` which is cumbersome. I assume this covers using Homebrew's Python too.
