### ISSUE TITLE
[macOS x86_64] ChaiNNer doesn't close when the initial download at first startup fails

### ISSUE THREAD

**Issue by alsa64** [chaiNNer-org/chaiNNer#891]
**Information:**
- Chainner version: [0.12.0]
- OS: [macOS 12.5.1]

**Description**
Do a fresh installation of ChaiNNer and launch it for the first time and have internet problems, disconnecting the connection is likely easiest

**What I expected to happen:**
After showing an error message, the app should fully quit itself instead of just closing the window.

**Comment by RunDevelopment** [comment]
We have long refactored and improved upon the setup process multiples times since 0.12.0, so this shouldn't be an issue anymore, I think.
