### ISSUE TITLE
Delay update dialog until after chaiNNer is initialized

### ISSUE THREAD

**Issue by Kim2091** [chaiNNer-org/chaiNNer#903]
**Motivation**
The update dialog currently pops up when chaiNNer is loading. 

**Description**
This is great to prevent unnecessary loading on the user's end, but the way the dialog functions makes it quite frustrating. It easily gets "lost" behind other windows, and it does not show in Windows as a proper Window.

**Alternatives**
Either change the way the dialog functions to make it larger and more detailed (including the current app version would be a nice touch) or delay it until after chaiNNer is initialized.

**Comment by joeyballentine** [comment]
Closing this as it was completed by #1232
