### ISSUE TITLE
TensorRT: save conversion model into caching file

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [chaiNNer-org/chaiNNer#959]
TensorRT works for me with no problem! Thank you very much.
At the beginning, it compiles the model for a long time (some models over 230 seconds), but then it works quickly (slightly faster than CUDA).
Is conversion caching possible? so that after restarting each time you do not have to wait.

**Comment by joeyballentine** [comment]
Actually yes, they provide an option for this. They did however say that you have to manage clearing that cache manually, which is why I did not turn that on. However, I could add a "clear onnx model cache" option to settings maybe. Or just turn it on and not worry about it for now.
