### ISSUE TITLE
Feature - More Blend Modes and Image Filters

### ISSUE THREAD

**Issue by jpassos92** [chaiNNer-org/chaiNNer#977]
I just found a python library that enables support to all blend modes in Photoshop, brightness, contrast, hue, saturation, lightness adjustments, and curve adjustments on separate RGB channels.

https://github.com/subwaymatch/layer-is-python

Some of them we already have in channer, but there are some missing features.

**Comment by theflyingzamboni** [comment]
I intend to continue implementing more blend modes, but they'll be implemented directly in chainner, rather than requiring another dependency. We've also talked about having a curve adjustment node, but that's a little more complicated to implement, so may be further down the line.

**Comment by RunDevelopment** [comment]
With #1072, #1080, and #1081, only curve adjustment thingy is still missing.

**Comment by RunDevelopment** [comment]
I'm closing this now in favor of #1082.
