### ISSUE TITLE
Error report for chaiNNer 0.11.6

### ISSUE THREAD

**Issue by DPG7332** [chaiNNer-org/chaiNNer#983]
Error:
```UnhandledRejection TypeError: Object has been destroyed
    at EventEmitter.<anonymous> (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:72152)
```
OS: macOS 10.17

**Comment by joeyballentine** [comment]
Can you please upgrade to the latest version and let me know if you still get that error?

**Comment by joeyballentine** [comment]
@DPG7332 Hello. Did you test the latest version?

**Comment by joeyballentine** [comment]
Closing this issue due to inacitivy. Feel free to reply and I'll open it back up.
