### ISSUE TITLE
Ctrl + R reload loses "load image" input in the node.

### ISSUE THREAD

**Issue by ratherrandomaccname9000** [chaiNNer-org/chaiNNer#994]
After reloading or force reloading with shortcut ctrl+r I lose the "load image" nodes input. It shows in the node "image not available" Even after file > open. The only way to fix is to load some other image and then the one I am using.
0.12.7 win 10 PNG file.

**Comment by RunDevelopment** [comment]
I think manual reloading (#732) will be a fix for this.

@joeyballentine Is force reloading even a feature we want to support? I always saw it as a debugging tool.

**Comment by joeyballentine** [comment]
Yeah I forgot the end user could even do this. Is there a reason you were refreshing?

**Comment by ratherrandomaccname9000** [comment]
Working on a texture that I am upscaling. So basically iteration. I modify it in krita, export and want it to upscale new version and because there is no autodetect of changes to the input file I use ctrl+R as the fastest method for now.

**Comment by joeyballentine** [comment]
I was working on adding an "auto reload when file changes" feature. Ran into a couple blockers though. I can try to give that another go and hopefully get that in soon

**Comment by theflyingzamboni** [comment]
I've used it sometimes when the viewport locks up, which still happens on occasion.

**Comment by RunDevelopment** [comment]
Is this still an issue? I tried to replicate it, but everything worked as expected.

Also, you'll be able to manually reload nodes with #1194, so there's no need for Ctrl+R anymore.

**Comment by RunDevelopment** [comment]
I tested this on 2 computers now and the issue seems to be fixed. I'll close this now. If the issue still persists, please comment on this issue and we'll reopen it.
